octomap: src/binvox2bt.cpp File Reference
binvox2bt.cpp File Reference
Read files generated by Patrick Min's 3D mesh voxelizer ("binvox", available at: http://www.cs.princeton.edu/~min/binvox/) and convert the voxel meshes to a single bonsai tree file.
Macros
#define M_PI_2 1.5707963267948966192E0
Typedefs
typedef unsigned char byte
Functions
int main (int argc, char **argv)
Detailed Description
Read files generated by Patrick Min's 3D mesh voxelizer ("binvox", available at: http://www.cs.princeton.edu/~min/binvox/) and convert the voxel meshes to a single bonsai tree file.
This file is based on code from http://www.cs.princeton.edu/~min/binvox/read_binvox.cc
Author
S. Osswald, University of Freiburg, Copyright (C) 2010.
See Also
http://octomap.sourceforge.net/ License: New BSD License
Macro Definition Documentation
#define M_PI_2 1.5707963267948966192E0
Referenced by main().
Typedef Documentation
typedef unsigned char byte
Function Documentation
int main (int argc, char ** argv)
References M_PI_2, octomap::OcTreeBaseImpl< NODE, INTERFACE >::prune(), octomath::Vector3::rotate_IP(), octomap::OccupancyOcTreeBase< NODE >::updateInnerOccupancy(), and octomap::OccupancyOcTreeBase< NODE >::updateNode().