octomap: src/bt2vrml.cpp File Reference
bt2vrml.cpp File Reference
Functions
int main (int argc, char **argv)
void printUsage (char *self)
Function Documentation
int main (int argc, char ** argv)
References octomap::OcTreeBaseImpl< NODE, INTERFACE >::begin(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::end(), octomap::AbstractOccupancyOcTree::isNodeOccupied(), and printUsage().
void printUsage (char * self)
Referenced by main().