octomap: octomap::OcTree Class Reference
octomap::OcTree Class Reference abstract
octomap main map data structure, stores 3D occupancy grid map in an OcTree.
Data Structures
class StaticMemberInitializer
Static member object which ensures that this OcTree's prototype ends up in the classIDMapping only once.
Public Types
typedef leaf_iterator iterator
typedef OcTreeNode NodeType
Make the templated NODE type available from the outside.
Public Member Functions
OcTreeKey adjustKeyAtDepth (const OcTreeKey &key, unsigned int depth) const
Adjusts a 3D key from the lowest level to correspond to a higher depth (by shifting the key values)
key_type adjustKeyAtDepth (key_type key, unsigned int depth) const
Adjusts a single key value from the lowest level to correspond to a higher depth (by shifting the key value)
bool bbxSet () const
iterator begin (unsigned char maxDepth=0) const
leaf_iterator begin_leafs (unsigned char maxDepth=0) const
leaf_bbx_iterator begin_leafs_bbx (const OcTreeKey &min, const OcTreeKey &max, unsigned char maxDepth=0) const
leaf_bbx_iterator begin_leafs_bbx (const point3d &min, const point3d &max, unsigned char maxDepth=0) const
tree_iterator begin_tree (unsigned char maxDepth=0) const
size_t calcNumNodes () const
Traverses the tree to calculate the total number of nodes.
virtual bool castRay (const point3d &origin, const point3d &direction, point3d &end, bool ignoreUnknownCells=false, double maxRange=-1.0) const
Performs raycasting in 3d, similar to computeRay().
KeyBoolMap::const_iterator changedKeysBegin () const
Iterator to traverse all keys of changed nodes.
KeyBoolMap::const_iterator changedKeysEnd () const
Iterator to traverse all keys of changed nodes.
void clear ()
Deletes the complete tree structure.
void clearKeyRays ()
Clear KeyRay vector to minimize unneeded memory.
void computeDiscreteUpdate (const Pointcloud &scan, const octomap::point3d &origin, KeySet &free_cells, KeySet &occupied_cells, double maxrange)
Helper for insertPointCloud().
bool computeRay (const point3d &origin, const point3d &end, std::vector< point3d > &ray)
Traces a ray from origin to end (excluding), returning the coordinates of all nodes traversed by the beam.
bool computeRayKeys (const point3d &origin, const point3d &end, KeyRay &ray) const
Traces a ray from origin to end (excluding), returning an OcTreeKey of all nodes traversed by the beam.
void computeUpdate (const Pointcloud &scan, const octomap::point3d &origin, KeySet &free_cells, KeySet &occupied_cells, double maxrange)
Helper for insertPointCloud().
OcTreeKey coordToKey (const point3d &coord) const
Converts from a 3D coordinate into a 3D addressing key.
OcTreeKey coordToKey (const point3d &coord, unsigned depth) const
Converts from a 3D coordinate into a 3D addressing key at a given depth.
key_type coordToKey (double coordinate) const
Converts from a single coordinate into a discrete key.
key_type coordToKey (double coordinate, unsigned depth) const
Converts from a single coordinate into a discrete key at a given depth.
OcTreeKey coordToKey (double x, double y, double z) const
Converts from a 3D coordinate into a 3D addressing key.
OcTreeKey coordToKey (double x, double y, double z, unsigned depth) const
Converts from a 3D coordinate into a 3D addressing key at a given depth.
bool coordToKeyChecked (const point3d &coord, OcTreeKey &key) const
Converts a 3D coordinate into a 3D OcTreeKey, with boundary checking.
bool coordToKeyChecked (const point3d &coord, unsigned depth, OcTreeKey &key) const
Converts a 3D coordinate into a 3D OcTreeKey at a certain depth, with boundary checking.
bool coordToKeyChecked (double coordinate, key_type &key) const
Converts a single coordinate into a discrete addressing key, with boundary checking.
bool coordToKeyChecked (double coordinate, unsigned depth, key_type &key) const
Converts a single coordinate into a discrete addressing key, with boundary checking.
bool coordToKeyChecked (double x, double y, double z, OcTreeKey &key) const
Converts a 3D coordinate into a 3D OcTreeKey, with boundary checking.
bool coordToKeyChecked (double x, double y, double z, unsigned depth, OcTreeKey &key) const
Converts a 3D coordinate into a 3D OcTreeKey at a certain depth, with boundary checking.
OcTree * create () const
virtual constructor: creates a new object of same type (Covariant return type requires an up-to-date compiler)
OcTreeNode * createNodeChild (OcTreeNode *node, unsigned int childIdx)
Creates (allocates) the i-th child of the node.
bool deleteNode (const OcTreeKey &key, unsigned int depth=0)
Delete a node (if exists) given an addressing key.
bool deleteNode (const point3d &value, unsigned int depth=0)
Delete a node (if exists) given a 3d point.
bool deleteNode (double x, double y, double z, unsigned int depth=0)
Delete a node (if exists) given a 3d point.
void deleteNodeChild (OcTreeNode *node, unsigned int childIdx)
Deletes the i-th child of the node.
void enableChangeDetection (bool enable)
track or ignore changes while inserting scans (default: ignore)
const iterator end () const
const leaf_iterator end_leafs () const
const leaf_bbx_iterator end_leafs_bbx () const
const tree_iterator end_tree () const
virtual void expand ()
Expands all pruned nodes (reverse of prune())
virtual void expandNode (OcTreeNode *node)
Expands a node (reverse of pruning): All children are created and their occupancy probability is set to the node's value.
point3d getBBXBounds () const
point3d getBBXCenter () const
point3d getBBXMax () const
point3d getBBXMin () const
double getClampingThresMax () const
float getClampingThresMaxLog () const
double getClampingThresMin () const
float getClampingThresMinLog () const
virtual void getMetricMax (double &x, double &y, double &z)
maximum value of the bounding box of all known space in x, y, z
void getMetricMax (double &x, double &y, double &z) const
maximum value of the bounding box of all known space in x, y, z
virtual void getMetricMin (double &x, double &y, double &z)
minimum value of the bounding box of all known space in x, y, z
void getMetricMin (double &x, double &y, double &z) const
minimum value of the bounding box of all known space in x, y, z
virtual void getMetricSize (double &x, double &y, double &z)
Size of OcTree (all known space) in meters for x, y and z dimension.
virtual void getMetricSize (double &x, double &y, double &z) const
Size of OcTree (all known space) in meters for x, y and z dimension.
const OcTreeNode * getNodeChild (const OcTreeNode *node, unsigned int childIdx) const
OcTreeNode * getNodeChild (OcTreeNode *node, unsigned int childIdx) const
double getNodeSize (unsigned depth) const
bool getNormals (const point3d &point, std::vector< point3d > &normals, bool unknownStatus=true) const
Performs a step of the marching cubes surface reconstruction algorithm to retrieve the normal of the triangles that fall in the cube formed by the voxels located at the vertex of a given voxel.
size_t getNumLeafNodes () const
Traverses the tree to calculate the total number of leaf nodes.
double getOccupancyThres () const
float getOccupancyThresLog () const
double getProbHit () const
float getProbHitLog () const
double getProbMiss () const
float getProbMissLog () const
virtual bool getRayIntersection (const point3d &origin, const point3d &direction, const point3d &center, point3d &intersection, double delta=0.0) const
Retrieves the entry point of a ray into a voxel.
double getResolution () const
virtual double getResolution () const =0
OcTreeNode * getRoot () const
unsigned int getTreeDepth () const
std::string getTreeType () const
returns actual class name as string for identification
std::string getTreeType () const
void getUnknownLeafCenters (point3d_list &node_centers, point3d pmin, point3d pmax, unsigned int depth=0) const
return centers of leafs that do NOT exist (but could) in a given bounding box
bool inBBX (const OcTreeKey &key) const
bool inBBX (const point3d &p) const
virtual void insertPointCloud (const Pointcloud &scan, const octomap::point3d &sensor_origin, double maxrange=-1., bool lazy_eval=false, bool discretize=false)
Integrate a Pointcloud (in global reference frame), parallelized with OpenMP.
virtual void insertPointCloud (const Pointcloud &scan, const point3d &sensor_origin, const pose6d &frame_origin, double maxrange=-1., bool lazy_eval=false, bool discretize=false)
Integrate a 3d scan (transform scan before tree update), parallelized with OpenMP.
virtual void insertPointCloud (const ScanNode &scan, double maxrange=-1., bool lazy_eval=false, bool discretize=false)
Insert a 3d scan (given as a ScanNode) into the tree, parallelized with OpenMP.
virtual void insertPointCloudRays (const Pointcloud &scan, const point3d &sensor_origin, double maxrange=-1., bool lazy_eval=false)
Integrate a Pointcloud (in global reference frame), parallelized with OpenMP.
virtual bool insertRay (const point3d &origin, const point3d &end, double maxrange=-1.0, bool lazy_eval=false)
Insert one ray between origin and end into the tree.
virtual void integrateHit (OcTreeNode *occupancyNode) const
integrate a "hit" measurement according to the tree's sensor model
virtual void integrateMiss (OcTreeNode *occupancyNode) const
integrate a "miss" measurement according to the tree's sensor model
bool isChangeDetectionEnabled () const
bool isNodeAtThreshold (const OcTreeNode &occupancyNode) const
queries whether a node is at the clamping threshold according to the tree's parameter
bool isNodeAtThreshold (const OcTreeNode *occupancyNode) const
queries whether a node is at the clamping threshold according to the tree's parameter
virtual bool isNodeCollapsible (const OcTreeNode *node) const
A node is collapsible if all children exist, don't have children of their own and have the same occupancy value.
bool isNodeOccupied (const OcTreeNode &occupancyNode) const
queries whether a node is occupied according to the tree's parameter for "occupancy"
bool isNodeOccupied (const OcTreeNode *occupancyNode) const
queries whether a node is occupied according to the tree's parameter for "occupancy"
point3d keyToCoord (const OcTreeKey &key) const
converts from an addressing key at the lowest tree level into a coordinate corresponding to the key's center
point3d keyToCoord (const OcTreeKey &key, unsigned depth) const
converts from an addressing key at a given depth into a coordinate corresponding to the key's center
double keyToCoord (key_type key) const
converts from a discrete key at the lowest tree level into a coordinate corresponding to the key's center
double keyToCoord (key_type key, unsigned depth) const
converts from a discrete key at a given depth into a coordinate corresponding to the key's center
unsigned long long memoryFullGrid () const
virtual size_t memoryUsage () const
virtual size_t memoryUsage () const =0
virtual size_t memoryUsageNode () const
virtual size_t memoryUsageNode () const =0
bool nodeChildExists (const OcTreeNode *node, unsigned int childIdx) const
Safe test if node has a child at index childIdx.
bool nodeHasChildren (const OcTreeNode *node) const
Safe test if node has any children.
virtual void nodeToMaxLikelihood (OcTreeNode &occupancyNode) const
converts the node to the maximum likelihood value according to the tree's parameter for "occupancy"
virtual void nodeToMaxLikelihood (OcTreeNode *occupancyNode) const
converts the node to the maximum likelihood value according to the tree's parameter for "occupancy"
size_t numChangesDetected () const
Number of changes since last reset.
OcTree (double resolution)
Default constructor, sets resolution of leafs.
OcTree (std::string _filename)
Reads an OcTree from a binary file.
bool operator== (const OcTreeBaseImpl< OcTreeNode, AbstractOccupancyOcTree > &rhs) const
Comparison between two octrees, all meta data, all nodes, and the structure must be identical.
virtual void prune ()
Lossless compression of the octree: A node will replace all of its eight children if they have identical values.
virtual bool pruneNode (OcTreeNode *node)
Prunes a node when it is collapsible.
bool readBinary (const std::string &filename)
Reads OcTree from a binary file.
bool readBinary (std::istream &s)
Reads an OcTree from an input stream.
std::istream & readBinaryData (std::istream &s)
Reads only the data (=complete tree structure) from the input stream.
std::istream & readBinaryNode (std::istream &s, OcTreeNode *node)
Read node from binary stream (max-likelihood value), recursively continue with all children.
std::istream & readData (std::istream &s)
Read all nodes from the input stream (without file header), for this the tree needs to be already created.
void resetChangeDetection ()
Reset the set of changed keys. Call this after you obtained all changed nodes.
OcTreeNode * search (const OcTreeKey &key, unsigned int depth=0) const
Search a node at specified depth given an addressing key (depth=0: search full tree depth) You need to check if the returned node is NULL, since it can be in unknown space.
OcTreeNode * search (const point3d &value, unsigned int depth=0) const
Search node at specified depth given a 3d point (depth=0: search full tree depth) You need to check if the returned node is NULL, since it can be in unknown space.
OcTreeNode * search (double x, double y, double z, unsigned int depth=0) const
Search node at specified depth given a 3d point (depth=0: search full tree depth).
void setBBXMax (const point3d &max)
sets the maximum for a query bounding box to use
void setBBXMin (const point3d &min)
sets the minimum for a query bounding box to use
void setClampingThresMax (double thresProb)
sets the maximum threshold for occupancy clamping (sensor model)
void setClampingThresMin (double thresProb)
sets the minimum threshold for occupancy clamping (sensor model)
virtual OcTreeNode * setNodeValue (const OcTreeKey &key, float log_odds_value, bool lazy_eval=false)
Set log_odds value of voxel to log_odds_value.
virtual OcTreeNode * setNodeValue (const point3d &value, float log_odds_value, bool lazy_eval=false)
Set log_odds value of voxel to log_odds_value.
virtual OcTreeNode * setNodeValue (double x, double y, double z, float log_odds_value, bool lazy_eval=false)
Set log_odds value of voxel to log_odds_value.
void setOccupancyThres (double prob)
sets the threshold for occupancy (sensor model)
void setProbHit (double prob)
sets the probability for a "hit" (will be converted to logodds) - sensor model
void setProbMiss (double prob)
sets the probability for a "miss" (will be converted to logodds) - sensor model
void setResolution (double r)
Change the resolution of the octree, scaling all voxels. This will not preserve the (metric) scale!
virtual size_t size () const
virtual size_t size () const =0
void swapContent (OcTreeBaseImpl< OcTreeNode, AbstractOccupancyOcTree > &rhs)
Swap contents of two octrees, i.e., only the underlying pointer / tree structure.
virtual void toMaxLikelihood ()
Creates the maximum likelihood map by calling toMaxLikelihood on all tree nodes, setting their occupancy to the corresponding occupancy thresholds.
void updateInnerOccupancy ()
Updates the occupancy of all inner nodes to reflect their children's occupancy.
virtual OcTreeNode * updateNode (const OcTreeKey &key, bool occupied, bool lazy_eval=false)
Integrate occupancy measurement.
virtual OcTreeNode * updateNode (const OcTreeKey &key, float log_odds_update, bool lazy_eval=false)
Manipulate log_odds value of a voxel by changing it by log_odds_update (relative).
virtual OcTreeNode * updateNode (const point3d &value, bool occupied, bool lazy_eval=false)
Integrate occupancy measurement.
virtual OcTreeNode * updateNode (const point3d &value, float log_odds_update, bool lazy_eval=false)
Manipulate log_odds value of a voxel by changing it by log_odds_update (relative).
virtual OcTreeNode * updateNode (double x, double y, double z, bool occupied, bool lazy_eval=false)
Integrate occupancy measurement.
virtual OcTreeNode * updateNode (double x, double y, double z, float log_odds_update, bool lazy_eval=false)
Manipulate log_odds value of a voxel by changing it by log_odds_update (relative).
virtual void updateNodeLogOdds (OcTreeNode *occupancyNode, const float &update) const
update logodds value of node by adding to the current value.
void useBBXLimit (bool enable)
use or ignore BBX limit (default: ignore)
double volume ()
bool write (const std::string &filename) const
Write file header and complete tree to file (serialization)
bool write (std::ostream &s) const
Write file header and complete tree to stream (serialization)
bool writeBinary (const std::string &filename)
Writes OcTree to a binary file using writeBinary().
bool writeBinary (std::ostream &s)
Writes compressed maximum likelihood OcTree to a binary stream.
bool writeBinaryConst (const std::string &filename) const
Writes OcTree to a binary file using writeBinaryConst().
bool writeBinaryConst (std::ostream &s) const
Writes the maximum likelihood OcTree to a binary stream (const variant).
std::ostream & writeBinaryData (std::ostream &s) const
Writes the data of the tree (without header) to the stream, recursively calling writeBinaryNode (starting with root)
std::ostream & writeBinaryNode (std::ostream &s, const OcTreeNode *node) const
Write node to binary stream (max-likelihood value), recursively continue with all children.
std::ostream & writeData (std::ostream &s) const
Write complete state of tree to stream (without file header) unmodified. Pruning the tree first produces smaller files (lossless compression)
virtual ~OcTree ()
Static Public Member Functions
static AbstractOcTree * createTree (const std::string id, double res)
Creates a certain OcTree (factory pattern)
static AbstractOcTree * read (const std::string &filename)
Read the file header, create the appropriate class and deserialize.
static AbstractOcTree * read (std::istream &s)
Read the file header, create the appropriate class and deserialize. This creates a new octree which you need to delete yourself.
Protected Member Functions
void allocNodeChildren (OcTreeNode *node)
void calcMinMax ()
recalculates min and max in x, y, z. Does nothing when tree size didn't change.
void calcNumNodesRecurs (OcTreeNode *node, size_t &num_nodes) const
void deleteNodeRecurs (OcTreeNode *node)
Recursively delete a node and all children. Deallocates memory but does NOT set the node ptr to NULL nor updates tree size.
bool deleteNodeRecurs (OcTreeNode *node, unsigned int depth, unsigned int max_depth, const OcTreeKey &key)
recursive call of deleteNode()
void expandRecurs (OcTreeNode *node, unsigned int depth, unsigned int max_depth)
recursive call of expand()
size_t getNumLeafNodesRecurs (const OcTreeNode *parent) const
void init ()
initialize non-trivial members, helper for constructors
bool integrateMissOnRay (const point3d &origin, const point3d &end, bool lazy_eval=false)
Traces a ray from origin to end and updates all voxels on the way as free.
void pruneRecurs (OcTreeNode *node, unsigned int depth, unsigned int max_depth, unsigned int &num_pruned)
recursive call of prune()
bool readBinaryLegacyHeader (std::istream &s, unsigned int &size, double &res)
Try to read the old binary format for conversion, will be removed in the future.
std::istream & readNodesRecurs (OcTreeNode *, std::istream &s)
recursive call of readData()
OcTreeNode * setNodeValueRecurs (OcTreeNode *node, bool node_just_created, const OcTreeKey &key, unsigned int depth, const float &log_odds_value, bool lazy_eval=false)
void toMaxLikelihoodRecurs (OcTreeNode *node, unsigned int depth, unsigned int max_depth)
void updateInnerOccupancyRecurs (OcTreeNode *node, unsigned int depth)
OcTreeNode * updateNodeRecurs (OcTreeNode *node, bool node_just_created, const OcTreeKey &key, unsigned int depth, const float &log_odds_update, bool lazy_eval=false)
std::ostream & writeNodesRecurs (const OcTreeNode *, std::ostream &s) const
recursive call of writeData()
Static Protected Member Functions
static bool readHeader (std::istream &s, std::string &id, unsigned &size, double &res)
static void registerTreeType (AbstractOcTree *tree)
Protected Attributes
point3d bbx_max
OcTreeKey bbx_max_key
point3d bbx_min
OcTreeKey bbx_min_key
KeyBoolMap changed_keys
Set of leaf keys (lowest level) which changed since last resetChangeDetection.
float clamping_thres_max
float clamping_thres_min
std::vector< KeyRay > keyrays
data structure for ray casting, array for multithreading
const leaf_bbx_iterator leaf_iterator_bbx_end
const leaf_iterator leaf_iterator_end
double max_value [3]
max in x, y, z
double min_value [3]
min in x, y, z contains the size of a voxel at level i (0: root node). tree_depth+1 levels (incl. 0)
float occ_prob_thres_log
float prob_hit_log
float prob_miss_log
double resolution
in meters
double resolution_factor
= 1. / resolution
OcTreeNode * root
Pointer to the root NODE, NULL for empty tree.
bool size_changed
std::vector< double > sizeLookupTable
point3d tree_center
const unsigned int tree_depth
Maximum tree depth is fixed to 16 currently.
const tree_iterator tree_iterator_end
const unsigned int tree_max_val
size_t tree_size
number of nodes in tree flag to denote whether the octree extent changed (for lazy min/max eval)
bool use_bbx_limit
use bounding box for queries (needs to be set)?
bool use_change_detection
Static Protected Attributes
static const std::string binaryFileHeader = "# Octomap OcTree binary file"
static const std::string fileHeader = "# Octomap OcTree file"
static StaticMemberInitializer ocTreeMemberInit
to ensure static initialization (only once)
Detailed Description
octomap main map data structure, stores 3D occupancy grid map in an OcTree.
Basic functionality is implemented in OcTreeBase.
Member Typedef Documentation
iterator
typedef leaf_iterator octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::iterator inherited
NodeType
typedef OcTreeNode octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::NodeType inherited
Make the templated NODE type available from the outside.
Constructor & Destructor Documentation
OcTree() [1/2]
octomap::OcTree::OcTree (double resolution)
Default constructor, sets resolution of leafs.
References octomap::OcTree::StaticMemberInitializer::ensureLinking(), and ocTreeMemberInit.
Referenced by create(), and octomap::OcTree::StaticMemberInitializer::StaticMemberInitializer().
OcTree() [2/2]
octomap::OcTree::OcTree (std::string _filename)
Reads an OcTree from a binary file.
Parameters
_filename
References octomap::AbstractOccupancyOcTree::readBinary().
~OcTree()
virtual octomap::OcTree::~OcTree () inline virtual
Member Function Documentation
adjustKeyAtDepth() [1/2]
OcTreeKey octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::adjustKeyAtDepth (const OcTreeKey & key, unsigned int depth) const inline inherited
Adjusts a 3D key from the lowest level to correspond to a higher depth (by shifting the key values)
Parameters
key Input key, at the lowest tree level
depth Target depth level for the new key
Returns
Key for the new depth level
adjustKeyAtDepth() [2/2]
key_type octomap::OcTreeBaseImpl< OcTreeNode , I >::adjustKeyAtDepth (key_type key, unsigned int depth) const inherited
Adjusts a single key value from the lowest level to correspond to a higher depth (by shifting the key value)
Parameters
key Input key, at the lowest tree level
depth Target depth level for the new key
Returns
Key for the new depth level
allocNodeChildren()
void octomap::OcTreeBaseImpl< OcTreeNode , I >::allocNodeChildren (OcTreeNode * node) protected inherited
bbxSet()
bool octomap::OccupancyOcTreeBase< OcTreeNode >::bbxSet inline inherited
begin()
iterator octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::begin (unsigned char maxDepth = 0) const inline inherited
Returns
beginning of the tree as leaf iterator
begin_leafs()
leaf_iterator octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::begin_leafs (unsigned char maxDepth = 0) const inline inherited
Returns
beginning of the tree as leaf iterator
begin_leafs_bbx() [1/2]
leaf_bbx_iterator octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::begin_leafs_bbx (const OcTreeKey & min, const OcTreeKey & max, unsigned char maxDepth = 0) const inline inherited
Returns
beginning of the tree as leaf iterator in a bounding box
begin_leafs_bbx() [2/2]
leaf_bbx_iterator octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::begin_leafs_bbx (const point3d & min, const point3d & max, unsigned char maxDepth = 0) const inline inherited
Returns
beginning of the tree as leaf iterator in a bounding box
begin_tree()
tree_iterator octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::begin_tree (unsigned char maxDepth = 0) const inline inherited
Returns
beginning of the tree as iterator to all nodes (incl. inner)
calcMinMax()
void octomap::OcTreeBaseImpl< OcTreeNode , I >::calcMinMax protected inherited
recalculates min and max in x, y, z. Does nothing when tree size didn't change.
calcNumNodes()
size_t octomap::OcTreeBaseImpl< OcTreeNode , I >::calcNumNodes inherited
Traverses the tree to calculate the total number of nodes.
calcNumNodesRecurs()
void octomap::OcTreeBaseImpl< OcTreeNode , I >::calcNumNodesRecurs (OcTreeNode * node, size_t & num_nodes) const protected inherited
castRay()
bool octomap::OccupancyOcTreeBase< OcTreeNode >::castRay (const point3d & origin, const point3d & direction, point3d & end, bool ignoreUnknownCells = false, double maxRange = -1.0) const virtual inherited
Performs raycasting in 3d, similar to computeRay().
Can be called in parallel e.g. with OpenMP for a speedup.
A ray is cast from 'origin' with a given direction, the first non-free cell is returned in 'end' (as center coordinate). This could also be the origin node if it is occupied or unknown. castRay() returns true if an occupied node was hit by the raycast. If the raycast returns false you can search() the node at 'end' and see whether it's unknown space.
Parameters
[in] origin starting coordinate of ray
[in] direction A vector pointing in the direction of the raycast (NOT a point in space). Does not need to be normalized.
[out] end returns the center of the last cell on the ray. If the function returns true, it is occupied.
[in] ignoreUnknownCells whether unknown cells are ignored (= treated as free). If false (default), the raycast aborts when an unknown cell is hit and returns false.
[in] maxRange Maximum range after which the raycast is aborted (<= 0: no limit, default)
Returns
true if an occupied cell was hit, false if the maximum range or octree bounds are reached, or if an unknown node was hit.
-------— see OcTreeBase::computeRayKeys --------—
changedKeysBegin()
KeyBoolMap::const_iterator octomap::OccupancyOcTreeBase< OcTreeNode >::changedKeysBegin inline inherited
Iterator to traverse all keys of changed nodes.
you need to enableChangeDetection() first. Here, an OcTreeKey always refers to a node at the lowest tree level (its size is the minimum tree resolution)
changedKeysEnd()
KeyBoolMap::const_iterator octomap::OccupancyOcTreeBase< OcTreeNode >::changedKeysEnd inline inherited
Iterator to traverse all keys of changed nodes.
clear()
void octomap::OcTreeBaseImpl< OcTreeNode , I >::clear virtual inherited
Deletes the complete tree structure.
Implements octomap::AbstractOcTree.
clearKeyRays()
void octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::clearKeyRays inline inherited
Clear KeyRay vector to minimize unneeded memory.
This is only useful for the StaticMemberInitializer classes, don't call it for an octree that is actually used.
computeDiscreteUpdate()
void octomap::OccupancyOcTreeBase< OcTreeNode >::computeDiscreteUpdate (const Pointcloud & scan, const octomap::point3d & origin, KeySet & free_cells, KeySet & occupied_cells, double maxrange) inherited
Helper for insertPointCloud().
Computes all octree nodes affected by the point cloud integration at once. Here, occupied nodes have a preference over free ones. This function first discretizes the scan with the octree grid, which results in fewer raycasts (=speedup) but a slightly different result than computeUpdate().
Parameters
scan point cloud measurement to be integrated
origin origin of the sensor for ray casting
free_cells keys of nodes to be cleared
occupied_cells keys of nodes to be marked occupied
maxrange maximum range for raycasting (-1: unlimited)
computeRay()
bool octomap::OcTreeBaseImpl< OcTreeNode , I >::computeRay (const point3d & origin, const point3d & end, std::vector< point3d > & ray) inherited
Traces a ray from origin to end (excluding), returning the coordinates of all nodes traversed by the beam.
You still need to check if a node at that coordinate exists (e.g. with search()).
Note
: use the faster computeRayKeys method if possible.
Parameters
origin start coordinate of ray
end end coordinate of ray
ray KeyRay structure that holds the keys of all nodes traversed by the ray, excluding "end"
Returns
Success of operation. Returning false usually means that one of the coordinates is out of the OcTree's range
computeRayKeys()
bool octomap::OcTreeBaseImpl< OcTreeNode , I >::computeRayKeys (const point3d & origin, const point3d & end, KeyRay & ray) const inherited
Traces a ray from origin to end (excluding), returning an OcTreeKey of all nodes traversed by the beam.
You still need to check if a node at that coordinate exists (e.g. with search()).
Parameters
origin start coordinate of ray
end end coordinate of ray
ray KeyRay structure that holds the keys of all nodes traversed by the ray, excluding "end"
Returns
Success of operation. Returning false usually means that one of the coordinates is out of the OcTree's range
computeUpdate()
void octomap::OccupancyOcTreeBase< OcTreeNode >::computeUpdate (const Pointcloud & scan, const octomap::point3d & origin, KeySet & free_cells, KeySet & occupied_cells, double maxrange) inherited
Helper for insertPointCloud().
Computes all octree nodes affected by the point cloud integration at once. Here, occupied nodes have a preference over free ones.
Parameters
scan point cloud measurement to be integrated
origin origin of the sensor for ray casting
free_cells keys of nodes to be cleared
occupied_cells keys of nodes to be marked occupied
maxrange maximum range for raycasting (-1: unlimited)
coordToKey() [1/6]
OcTreeKey octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::coordToKey (const point3d & coord) const inline inherited
Converts from a 3D coordinate into a 3D addressing key.
coordToKey() [2/6]
OcTreeKey octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::coordToKey (const point3d & coord, unsigned depth) const inline inherited
Converts from a 3D coordinate into a 3D addressing key at a given depth.
coordToKey() [3/6]
key_type octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::coordToKey (double coordinate) const inline inherited
Converts from a single coordinate into a discrete key.
coordToKey() [4/6]
key_type octomap::OcTreeBaseImpl< OcTreeNode , I >::coordToKey (double coordinate, unsigned depth) const inline inherited
Converts from a single coordinate into a discrete key at a given depth.
coordToKey() [5/6]
OcTreeKey octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::coordToKey (double x, double y, double z) const inline inherited
Converts from a 3D coordinate into a 3D addressing key.
coordToKey() [6/6]
OcTreeKey octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::coordToKey (double x, double y, double z, unsigned depth) const inline inherited
Converts from a 3D coordinate into a 3D addressing key at a given depth.
coordToKeyChecked() [1/6]
bool octomap::OcTreeBaseImpl< OcTreeNode , I >::coordToKeyChecked (const point3d & coord, OcTreeKey & key) const inherited
Converts a 3D coordinate into a 3D OcTreeKey, with boundary checking.
Parameters
coord 3d coordinate of a point
key values that will be computed, an array of fixed size 3.
Returns
true if point is within the octree (valid), false otherwise
coordToKeyChecked() [2/6]
bool octomap::OcTreeBaseImpl< OcTreeNode , I >::coordToKeyChecked (const point3d & coord, unsigned depth, OcTreeKey & key) const inherited
Converts a 3D coordinate into a 3D OcTreeKey at a certain depth, with boundary checking.
Parameters
coord 3d coordinate of a point
depth level of the key from the top
key values that will be computed, an array of fixed size 3.
Returns
true if point is within the octree (valid), false otherwise
coordToKeyChecked() [3/6]
bool octomap::OcTreeBaseImpl< OcTreeNode , I >::coordToKeyChecked (double coordinate, key_type & key) const inherited
Converts a single coordinate into a discrete addressing key, with boundary checking.
Parameters
coordinate 3d coordinate of a point
key discrete 16 bit adressing key, result
Returns
true if coordinate is within the octree bounds (valid), false otherwise
coordToKeyChecked() [4/6]
bool octomap::OcTreeBaseImpl< OcTreeNode , I >::coordToKeyChecked (double coordinate, unsigned depth, key_type & key) const inherited
Converts a single coordinate into a discrete addressing key, with boundary checking.
Parameters
coordinate 3d coordinate of a point
depth level of the key from the top
key discrete 16 bit adressing key, result
Returns
true if coordinate is within the octree bounds (valid), false otherwise
coordToKeyChecked() [5/6]
bool octomap::OcTreeBaseImpl< OcTreeNode , I >::coordToKeyChecked (double x, double y, double z, OcTreeKey & key) const inherited
Converts a 3D coordinate into a 3D OcTreeKey, with boundary checking.
Parameters
x
y
z
key values that will be computed, an array of fixed size 3.
Returns
true if point is within the octree (valid), false otherwise
coordToKeyChecked() [6/6]
bool octomap::OcTreeBaseImpl< OcTreeNode , I >::coordToKeyChecked (double x, double y, double z, unsigned depth, OcTreeKey & key) const inherited
Converts a 3D coordinate into a 3D OcTreeKey at a certain depth, with boundary checking.
Parameters
x
y
z
depth level of the key from the top
key values that will be computed, an array of fixed size 3.
Returns
true if point is within the octree (valid), false otherwise
create()
OcTree* octomap::OcTree::create () const inline virtual
virtual constructor: creates a new object of same type (Covariant return type requires an up-to-date compiler)
Implements octomap::AbstractOcTree.
References OcTree(), and octomap::OcTreeBaseImpl< OcTreeNode, AbstractOccupancyOcTree >::resolution.
createNodeChild()
OcTreeNode * octomap::OcTreeBaseImpl< OcTreeNode , I >::createNodeChild (OcTreeNode * node, unsigned int childIdx) inherited
Creates (allocates) the i-th child of the node.
Returns
ptr to newly create NODE
createTree()
AbstractOcTree * octomap::AbstractOcTree::createTree (const std::string id, double res) static inherited
Creates a certain OcTree (factory pattern)
Parameters
id unique ID of OcTree
res resolution of OcTree
Returns
pointer to newly created OcTree (empty). NULL if the ID is unknown!
References OCTOMAP_ERROR, and octomap::AbstractOcTree::setResolution().
Referenced by octomap::AbstractOcTree::read().
deleteNode() [1/3]
bool octomap::OcTreeBaseImpl< OcTreeNode , I >::deleteNode (const OcTreeKey & key, unsigned int depth = 0) inherited
Delete a node (if exists) given an addressing key.
Will always delete at the lowest level unless depth !=0, and expand pruned inner nodes as needed. Pruned nodes at level "depth" will directly be deleted as a whole.
deleteNode() [2/3]
bool octomap::OcTreeBaseImpl< OcTreeNode , I >::deleteNode (const point3d & value, unsigned int depth = 0) inherited
Delete a node (if exists) given a 3d point.
Will always delete at the lowest level unless depth !=0, and expand pruned inner nodes as needed. Pruned nodes at level "depth" will directly be deleted as a whole.
deleteNode() [3/3]
bool octomap::OcTreeBaseImpl< OcTreeNode , I >::deleteNode (double x, double y, double z, unsigned int depth = 0) inherited
Delete a node (if exists) given a 3d point.
Will always delete at the lowest level unless depth !=0, and expand pruned inner nodes as needed. Pruned nodes at level "depth" will directly be deleted as a whole.
deleteNodeChild()
void octomap::OcTreeBaseImpl< OcTreeNode , I >::deleteNodeChild (OcTreeNode * node, unsigned int childIdx) inherited
Deletes the i-th child of the node.
deleteNodeRecurs() [1/2]
void octomap::OcTreeBaseImpl< OcTreeNode , I >::deleteNodeRecurs (OcTreeNode * node) protected inherited
Recursively delete a node and all children. Deallocates memory but does NOT set the node ptr to NULL nor updates tree size.
deleteNodeRecurs() [2/2]
bool octomap::OcTreeBaseImpl< OcTreeNode , I >::deleteNodeRecurs (OcTreeNode * node, unsigned int depth, unsigned int max_depth, const OcTreeKey & key) protected inherited
recursive call of deleteNode()
enableChangeDetection()
void octomap::OccupancyOcTreeBase< OcTreeNode >::enableChangeDetection (bool enable) inline inherited
track or ignore changes while inserting scans (default: ignore)
end()
const iterator octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::end inline inherited
Returns
end of the tree as leaf iterator
end_leafs()
const leaf_iterator octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::end_leafs inline inherited
Returns
end of the tree as leaf iterator
end_leafs_bbx()
const leaf_bbx_iterator octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::end_leafs_bbx inline inherited
Returns
end of the tree as leaf iterator in a bounding box
end_tree()
const tree_iterator octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::end_tree inline inherited
Returns
end of the tree as iterator to all nodes (incl. inner)
expand()
void octomap::OcTreeBaseImpl< OcTreeNode , I >::expand virtual inherited
Expands all pruned nodes (reverse of prune())
Note
This is an expensive operation, especially when the tree is nearly empty!
Implements octomap::AbstractOcTree.
expandNode()
void octomap::OcTreeBaseImpl< OcTreeNode , I >::expandNode (OcTreeNode * node) virtual inherited
Expands a node (reverse of pruning): All children are created and their occupancy probability is set to the node's value.
You need to verify that this is indeed a pruned node (i.e. not a leaf at the lowest level)
expandRecurs()
void octomap::OcTreeBaseImpl< OcTreeNode , I >::expandRecurs (OcTreeNode * node, unsigned int depth, unsigned int max_depth) protected inherited
recursive call of expand()
getBBXBounds()
point3d octomap::OccupancyOcTreeBase< OcTreeNode >::getBBXBounds inherited
getBBXCenter()
point3d octomap::OccupancyOcTreeBase< OcTreeNode >::getBBXCenter inherited
getBBXMax()
point3d octomap::OccupancyOcTreeBase< OcTreeNode >::getBBXMax inline inherited
Returns
the currently set maximum for bounding box queries, if set
getBBXMin()
point3d octomap::OccupancyOcTreeBase< OcTreeNode >::getBBXMin inline inherited
Returns
the currently set minimum for bounding box queries, if set
getClampingThresMax()
double octomap::AbstractOccupancyOcTree::getClampingThresMax () const inline inherited
Returns
maximum threshold for occupancy clamping in the sensor model (probability)
References octomap::AbstractOccupancyOcTree::clamping_thres_max, and octomap::probability().
Referenced by main().
getClampingThresMaxLog()
float octomap::AbstractOccupancyOcTree::getClampingThresMaxLog () const inline inherited
Returns
maximum threshold for occupancy clamping in the sensor model (logodds)
References octomap::AbstractOccupancyOcTree::clamping_thres_max.
getClampingThresMin()
double octomap::AbstractOccupancyOcTree::getClampingThresMin () const inline inherited
Returns
minimum threshold for occupancy clamping in the sensor model (probability)
References octomap::AbstractOccupancyOcTree::clamping_thres_min, and octomap::probability().
Referenced by main().
getClampingThresMinLog()
float octomap::AbstractOccupancyOcTree::getClampingThresMinLog () const inline inherited
Returns
minimum threshold for occupancy clamping in the sensor model (logodds)
References octomap::AbstractOccupancyOcTree::clamping_thres_min.
getMetricMax() [1/2]
void octomap::OcTreeBaseImpl< OcTreeNode , I >::getMetricMax (double & x, double & y, double & z) virtual inherited
maximum value of the bounding box of all known space in x, y, z
Implements octomap::AbstractOcTree.
getMetricMax() [2/2]
void octomap::OcTreeBaseImpl< OcTreeNode , I >::getMetricMax (double & x, double & y, double & z) const virtual inherited
maximum value of the bounding box of all known space in x, y, z
Implements octomap::AbstractOcTree.
getMetricMin() [1/2]
void octomap::OcTreeBaseImpl< OcTreeNode , I >::getMetricMin (double & x, double & y, double & z) virtual inherited
minimum value of the bounding box of all known space in x, y, z
Implements octomap::AbstractOcTree.
getMetricMin() [2/2]
void octomap::OcTreeBaseImpl< OcTreeNode , I >::getMetricMin (double & x, double & y, double & z) const virtual inherited
minimum value of the bounding box of all known space in x, y, z
Implements octomap::AbstractOcTree.
getMetricSize() [1/2]
void octomap::OcTreeBaseImpl< OcTreeNode , I >::getMetricSize (double & x, double & y, double & z) virtual inherited
Size of OcTree (all known space) in meters for x, y and z dimension.
Implements octomap::AbstractOcTree.
getMetricSize() [2/2]
void octomap::OcTreeBaseImpl< OcTreeNode , I >::getMetricSize (double & x, double & y, double & z) const virtual inherited
Size of OcTree (all known space) in meters for x, y and z dimension.
getNodeChild() [1/2]
const OcTreeNode * octomap::OcTreeBaseImpl< OcTreeNode , I >::getNodeChild (const OcTreeNode * node, unsigned int childIdx) const inherited
Returns
const ptr to child number childIdx of node
getNodeChild() [2/2]
OcTreeNode * octomap::OcTreeBaseImpl< OcTreeNode , I >::getNodeChild (OcTreeNode * node, unsigned int childIdx) const inherited
Returns
ptr to child number childIdx of node
getNodeSize()
double octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::getNodeSize (unsigned depth) const inline inherited
getNormals()
bool octomap::OccupancyOcTreeBase< OcTreeNode >::getNormals (const point3d & point, std::vector< point3d > & normals, bool unknownStatus = true) const inherited
Performs a step of the marching cubes surface reconstruction algorithm to retrieve the normal of the triangles that fall in the cube formed by the voxels located at the vertex of a given voxel.
Parameters
[in] point voxel for which retrieve the normals
[out] normals normals of the triangles
[in] unknownStatus consider unknown cells as free (false) or occupied (default, true).
Returns
True if the input voxel is known in the occupancy grid, and false if it is unknown.
getNumLeafNodes()
size_t octomap::OcTreeBaseImpl< OcTreeNode , I >::getNumLeafNodes inherited
Traverses the tree to calculate the total number of leaf nodes.
getNumLeafNodesRecurs()
size_t octomap::OcTreeBaseImpl< OcTreeNode , I >::getNumLeafNodesRecurs (const OcTreeNode * parent) const protected inherited
getOccupancyThres()
double octomap::AbstractOccupancyOcTree::getOccupancyThres () const inline inherited
Returns
threshold (probability) for occupancy - sensor model
References octomap::AbstractOccupancyOcTree::occ_prob_thres_log, and octomap::probability().
getOccupancyThresLog()
float octomap::AbstractOccupancyOcTree::getOccupancyThresLog () const inline inherited
Returns
threshold (logodds) for occupancy - sensor model
References octomap::AbstractOccupancyOcTree::occ_prob_thres_log.
getProbHit()
double octomap::AbstractOccupancyOcTree::getProbHit () const inline inherited
Returns
probability for a "hit" in the sensor model (probability)
References octomap::AbstractOccupancyOcTree::prob_hit_log, and octomap::probability().
Referenced by main().
getProbHitLog()
float octomap::AbstractOccupancyOcTree::getProbHitLog () const inline inherited
Returns
probability for a "hit" in the sensor model (logodds)
References octomap::AbstractOccupancyOcTree::prob_hit_log.
getProbMiss()
double octomap::AbstractOccupancyOcTree::getProbMiss () const inline inherited
Returns
probability for a "miss" in the sensor model (probability)
References octomap::AbstractOccupancyOcTree::prob_miss_log, and octomap::probability().
Referenced by main().
getProbMissLog()
float octomap::AbstractOccupancyOcTree::getProbMissLog () const inline inherited
Returns
probability for a "miss" in the sensor model (logodds)
References octomap::AbstractOccupancyOcTree::prob_miss_log.
getRayIntersection()
bool octomap::OccupancyOcTreeBase< OcTreeNode >::getRayIntersection (const point3d & origin, const point3d & direction, const point3d & center, point3d & intersection, double delta = 0.0) const virtual inherited
Retrieves the entry point of a ray into a voxel.
This is the closest intersection point of the ray originating from origin and a plane of the axis aligned cube.
Parameters
[in] origin Starting point of ray
[in] direction A vector pointing in the direction of the raycast. Does not need to be normalized.
[in] center The center of the voxel where the ray terminated. This is the output of castRay.
[out] intersection The entry point of the ray into the voxel, on the voxel surface.
[in] delta A small increment to avoid ambiguity of beeing exactly on a voxel surface. A positive value will get the point out of the hit voxel, while a negative valuewill get it inside.
Returns
Whether or not an intesection point has been found. Either, the ray never cross the voxel or the ray is exactly parallel to the only surface it intersect.
getResolution() [1/2]
double octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::getResolution inline inherited
getResolution() [2/2]
virtual double octomap::AbstractOcTree::getResolution () const pure virtual inherited
Referenced by main(), octomap::AbstractOcTree::write(), and octomap::AbstractOccupancyOcTree::writeBinaryConst().
getRoot()
OcTreeNode * octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::getRoot inline inherited
Returns
Pointer to the root node of the tree. This pointer should not be modified or deleted externally, the OcTree manages its memory itself. In an empty tree, root is NULL.
getTreeDepth()
unsigned int octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::getTreeDepth inline inherited
getTreeType() [1/2]
std::string octomap::OcTree::getTreeType () const inline virtual
returns actual class name as string for identification
Implements octomap::AbstractOcTree.
getTreeType() [2/2]
std::string octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::getTreeType inline inherited
getUnknownLeafCenters()
void octomap::OcTreeBaseImpl< OcTreeNode , I >::getUnknownLeafCenters (point3d_list & node_centers, point3d pmin, point3d pmax, unsigned int depth = 0) const inherited
return centers of leafs that do NOT exist (but could) in a given bounding box
inBBX() [1/2]
bool octomap::OccupancyOcTreeBase< OcTreeNode >::inBBX (const OcTreeKey & key) const inherited
Returns
true if key is in the currently set bounding box
inBBX() [2/2]
bool octomap::OccupancyOcTreeBase< OcTreeNode >::inBBX (const point3d & p) const inherited
Returns
true if point is in the currently set bounding box
init()
void octomap::OcTreeBaseImpl< OcTreeNode , I >::init protected inherited
initialize non-trivial members, helper for constructors
insertPointCloud() [1/3]
void octomap::OccupancyOcTreeBase< OcTreeNode >::insertPointCloud (const Pointcloud & scan, const octomap::point3d & sensor_origin, double maxrange = -1., bool lazy_eval = false, bool discretize = false) virtual inherited
Integrate a Pointcloud (in global reference frame), parallelized with OpenMP.
Special care is taken that each voxel in the map is updated only once, and occupied nodes have a preference over free ones. This avoids holes in the floor from mutual deletion and is more efficient than the plain ray insertion in insertPointCloudRays().
Note
replaces insertScan()
Parameters
scan Pointcloud (measurement endpoints), in global reference frame
sensor_origin measurement origin in global reference frame
maxrange maximum range for how long individual beams are inserted (default -1: complete beam)
lazy_eval whether update of inner nodes is omitted after the update (default: false). This speeds up the insertion, but you need to call updateInnerOccupancy() when done.
discretize whether the scan is discretized first into octree key cells (default: false). This reduces the number of raycasts using computeDiscreteUpdate(), resulting in a potential speedup.*
insertPointCloud() [2/3]
void octomap::OccupancyOcTreeBase< OcTreeNode >::insertPointCloud (const Pointcloud & scan, const point3d & sensor_origin, const pose6d & frame_origin, double maxrange = -1., bool lazy_eval = false, bool discretize = false) virtual inherited
Integrate a 3d scan (transform scan before tree update), parallelized with OpenMP.
Special care is taken that each voxel in the map is updated only once, and occupied nodes have a preference over free ones. This avoids holes in the floor from mutual deletion and is more efficient than the plain ray insertion in insertPointCloudRays().
Note
replaces insertScan()
Parameters
scan Pointcloud (measurement endpoints) relative to frame origin
sensor_origin origin of sensor relative to frame origin
frame_origin origin of reference frame, determines transform to be applied to cloud and sensor origin
maxrange maximum range for how long individual beams are inserted (default -1: complete beam)
lazy_eval whether update of inner nodes is omitted after the update (default: false). This speeds up the insertion, but you need to call updateInnerOccupancy() when done.
discretize whether the scan is discretized first into octree key cells (default: false). This reduces the number of raycasts using computeDiscreteUpdate(), resulting in a potential speedup.*
insertPointCloud() [3/3]
void octomap::OccupancyOcTreeBase< OcTreeNode >::insertPointCloud (const ScanNode & scan, double maxrange = -1., bool lazy_eval = false, bool discretize = false) virtual inherited
Insert a 3d scan (given as a ScanNode) into the tree, parallelized with OpenMP.
Note
replaces insertScan
Parameters
scan ScanNode contains Pointcloud data and frame/sensor origin
maxrange maximum range for how long individual beams are inserted (default -1: complete beam)
lazy_eval whether the tree is left 'dirty' after the update (default: false). This speeds up the insertion by not updating inner nodes, but you need to call updateInnerOccupancy() when done.
discretize whether the scan is discretized first into octree key cells (default: false). This reduces the number of raycasts using computeDiscreteUpdate(), resulting in a potential speedup.
insertPointCloudRays()
void octomap::OccupancyOcTreeBase< OcTreeNode >::insertPointCloudRays (const Pointcloud & scan, const point3d & sensor_origin, double maxrange = -1., bool lazy_eval = false) virtual inherited
Integrate a Pointcloud (in global reference frame), parallelized with OpenMP.
This function simply inserts all rays of the point clouds as batch operation. Discretization effects can lead to the deletion of occupied space, it is usually recommended to use insertPointCloud() instead.
Parameters
scan Pointcloud (measurement endpoints), in global reference frame
sensor_origin measurement origin in global reference frame
maxrange maximum range for how long individual beams are inserted (default -1: complete beam)
lazy_eval whether update of inner nodes is omitted after the update (default: false). This speeds up the insertion, but you need to call updateInnerOccupancy() when done.
insertRay()
bool octomap::OccupancyOcTreeBase< OcTreeNode >::insertRay (const point3d & origin, const point3d & end, double maxrange = -1.0, bool lazy_eval = false) virtual inherited
Insert one ray between origin and end into the tree.
integrateMissOnRay() is called for the ray, the end point is updated as occupied. It is usually more efficient to insert complete pointcloudsm with insertPointCloud() or insertPointCloudRays().
Parameters
origin origin of sensor in global coordinates
end endpoint of measurement in global coordinates
maxrange maximum range after which the raycast should be aborted
lazy_eval whether update of inner nodes is omitted after the update (default: false). This speeds up the insertion, but you need to call updateInnerOccupancy() when done.
Returns
success of operation
integrateHit()
void octomap::OccupancyOcTreeBase< OcTreeNode >::integrateHit (OcTreeNode * occupancyNode) const virtual inherited
integrate a "hit" measurement according to the tree's sensor model
integrateMiss()
void octomap::OccupancyOcTreeBase< OcTreeNode >::integrateMiss (OcTreeNode * occupancyNode) const virtual inherited
integrate a "miss" measurement according to the tree's sensor model
integrateMissOnRay()
bool octomap::OccupancyOcTreeBase< OcTreeNode >::integrateMissOnRay (const point3d & origin, const point3d & end, bool lazy_eval = false) inline protected inherited
Traces a ray from origin to end and updates all voxels on the way as free.
The volume containing "end" is not updated.
isChangeDetectionEnabled()
bool octomap::OccupancyOcTreeBase< OcTreeNode >::isChangeDetectionEnabled inline inherited
isNodeAtThreshold() [1/2]
bool octomap::AbstractOccupancyOcTree::isNodeAtThreshold (const OcTreeNode & occupancyNode) const inline inherited
queries whether a node is at the clamping threshold according to the tree's parameter
References octomap::OcTreeNode::getLogOdds().
isNodeAtThreshold() [2/2]
bool octomap::AbstractOccupancyOcTree::isNodeAtThreshold (const OcTreeNode * occupancyNode) const inline inherited
queries whether a node is at the clamping threshold according to the tree's parameter
References octomap::OcTreeNode::getLogOdds().
Referenced by calcThresholdedNodes().
isNodeCollapsible()
bool octomap::OcTreeBaseImpl< OcTreeNode , I >::isNodeCollapsible (const OcTreeNode * node) const virtual inherited
A node is collapsible if all children exist, don't have children of their own and have the same occupancy value.
isNodeOccupied() [1/2]
bool octomap::AbstractOccupancyOcTree::isNodeOccupied (const OcTreeNode & occupancyNode) const inline inherited
queries whether a node is occupied according to the tree's parameter for "occupancy"
References octomap::OcTreeNode::getLogOdds().
isNodeOccupied() [2/2]
bool octomap::AbstractOccupancyOcTree::isNodeOccupied (const OcTreeNode * occupancyNode) const inline inherited
queries whether a node is occupied according to the tree's parameter for "occupancy"
References octomap::OcTreeNode::getLogOdds().
Referenced by octomap::OcTreeStamped::degradeOutdatedNodes(), getLeafNodesRecurs(), main(), and printChanges().
keyToCoord() [1/4]
point3d octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::keyToCoord (const OcTreeKey & key) const inline inherited
converts from an addressing key at the lowest tree level into a coordinate corresponding to the key's center
keyToCoord() [2/4]
point3d octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::keyToCoord (const OcTreeKey & key, unsigned depth) const inline inherited
converts from an addressing key at a given depth into a coordinate corresponding to the key's center
keyToCoord() [3/4]
double octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::keyToCoord (key_type key) const inline inherited
converts from a discrete key at the lowest tree level into a coordinate corresponding to the key's center
keyToCoord() [4/4]
double octomap::OcTreeBaseImpl< OcTreeNode , I >::keyToCoord (key_type key, unsigned depth) const inherited
converts from a discrete key at a given depth into a coordinate corresponding to the key's center
memoryFullGrid()
unsigned long long octomap::OcTreeBaseImpl< OcTreeNode , I >::memoryFullGrid inherited
Returns
Memory usage of a full grid of the same size as the OcTree in bytes (for comparison)
Note
this can be larger than the adressable memory - size_t may not be enough to hold it!
memoryUsage() [1/2]
size_t octomap::OcTreeBaseImpl< OcTreeNode , I >::memoryUsage virtual inherited
Returns
Memory usage of the complete octree in bytes (may vary between architectures)
memoryUsage() [2/2]
virtual size_t octomap::AbstractOcTree::memoryUsage () const pure virtual inherited
memoryUsageNode() [1/2]
virtual size_t octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::memoryUsageNode inline virtual inherited
Returns
Memory usage of a single octree node
memoryUsageNode() [2/2]
virtual size_t octomap::AbstractOcTree::memoryUsageNode () const pure virtual inherited
nodeChildExists()
bool octomap::OcTreeBaseImpl< OcTreeNode , I >::nodeChildExists (const OcTreeNode * node, unsigned int childIdx) const inherited
Safe test if node has a child at index childIdx.
First tests if there are any children. Replaces node->childExists(...)
Returns
true if the child at childIdx exists
nodeHasChildren()
bool octomap::OcTreeBaseImpl< OcTreeNode , I >::nodeHasChildren (const OcTreeNode * node) const inherited
Safe test if node has any children.
Replaces node->hasChildren(...)
Returns
true if node has at least one child
nodeToMaxLikelihood() [1/2]
void octomap::OccupancyOcTreeBase< OcTreeNode >::nodeToMaxLikelihood (OcTreeNode & occupancyNode) const virtual inherited
converts the node to the maximum likelihood value according to the tree's parameter for "occupancy"
nodeToMaxLikelihood() [2/2]
void octomap::OccupancyOcTreeBase< OcTreeNode >::nodeToMaxLikelihood (OcTreeNode * occupancyNode) const virtual inherited
converts the node to the maximum likelihood value according to the tree's parameter for "occupancy"
numChangesDetected()
size_t octomap::OccupancyOcTreeBase< OcTreeNode >::numChangesDetected inline inherited
Number of changes since last reset.
operator==()
bool octomap::OcTreeBaseImpl< OcTreeNode , I >::operator== (const OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree > & rhs) const inherited
Comparison between two octrees, all meta data, all nodes, and the structure must be identical.
prune()
void octomap::OcTreeBaseImpl< OcTreeNode , I >::prune virtual inherited
Lossless compression of the octree: A node will replace all of its eight children if they have identical values.
You usually don't have to call prune() after a regular occupancy update, updateNode() incrementally prunes all affected nodes.
Implements octomap::AbstractOcTree.
pruneNode()
bool octomap::OcTreeBaseImpl< OcTreeNode , I >::pruneNode (OcTreeNode * node) virtual inherited
Prunes a node when it is collapsible.
Returns
true if pruning was successful
pruneRecurs()
void octomap::OcTreeBaseImpl< OcTreeNode , I >::pruneRecurs (OcTreeNode * node, unsigned int depth, unsigned int max_depth, unsigned int & num_pruned) protected inherited
recursive call of prune()
read() [1/2]
AbstractOcTree * octomap::AbstractOcTree::read (const std::string & filename) static inherited
Read the file header, create the appropriate class and deserialize.
This creates a new octree which you need to delete yourself. If you expect or requre a specific kind of octree, use dynamic_cast afterwards:
AbstractOcTree* tree = AbstractOcTree::read("filename.ot");
OcTree* octree = dynamic_cast<OcTree*>(tree);
References OCTOMAP_ERROR_STR.
read() [2/2]
AbstractOcTree * octomap::AbstractOcTree::read (std::istream & s) static inherited
Read the file header, create the appropriate class and deserialize. This creates a new octree which you need to delete yourself.
References octomap::AbstractOcTree::createTree(), octomap::AbstractOcTree::fileHeader, OCTOMAP_DEBUG_STR, OCTOMAP_ERROR_STR, octomap::AbstractOcTree::readData(), octomap::AbstractOcTree::readHeader(), and octomap::AbstractOcTree::size().
readBinary() [1/2]
bool octomap::AbstractOccupancyOcTree::readBinary (const std::string & filename) inherited
Reads OcTree from a binary file.
Existing nodes of the tree are deleted before the tree is read.
Returns
success of operation
References OCTOMAP_ERROR_STR, and octomap::AbstractOccupancyOcTree::readBinary().
readBinary() [2/2]
bool octomap::AbstractOccupancyOcTree::readBinary (std::istream & s) inherited
Reads an OcTree from an input stream.
Existing nodes of the tree are deleted before the tree is read.
Returns
success of operation
References octomap::AbstractOccupancyOcTree::binaryFileHeader, octomap::AbstractOcTree::clear(), OCTOMAP_DEBUG_STR, OCTOMAP_ERROR, OCTOMAP_ERROR_STR, OCTOMAP_WARNING_STR, octomap::AbstractOccupancyOcTree::readBinaryData(), octomap::AbstractOccupancyOcTree::readBinaryLegacyHeader(), octomap::AbstractOcTree::readHeader(), octomap::AbstractOcTree::setResolution(), and octomap::AbstractOcTree::size().
Referenced by main(), OcTree(), and octomap::AbstractOccupancyOcTree::readBinary().
readBinaryData()
std::istream & octomap::OccupancyOcTreeBase< OcTreeNode >::readBinaryData (std::istream & s) virtual inherited
Reads only the data (=complete tree structure) from the input stream.
The tree needs to be constructed with the proper header information beforehand, see readBinary().
Implements octomap::AbstractOccupancyOcTree.
readBinaryLegacyHeader()
bool octomap::AbstractOccupancyOcTree::readBinaryLegacyHeader (std::istream & s, unsigned int & size, double & res) protected inherited
Try to read the old binary format for conversion, will be removed in the future.
References octomap::AbstractOcTree::clear(), OCTOMAP_ERROR, OCTOMAP_ERROR_STR, OCTOMAP_WARNING_STR, and octomap::AbstractOcTree::size().
Referenced by octomap::AbstractOccupancyOcTree::readBinary().
readBinaryNode()
std::istream & octomap::OccupancyOcTreeBase< OcTreeNode >::readBinaryNode (std::istream & s, OcTreeNode * node) inherited
Read node from binary stream (max-likelihood value), recursively continue with all children.
This will set the log_odds_occupancy value of all leaves to either free or occupied.
readData()
std::istream & octomap::OcTreeBaseImpl< OcTreeNode , I >::readData (std::istream & s) virtual inherited
Read all nodes from the input stream (without file header), for this the tree needs to be already created.
For general file IO, you should probably use AbstractOcTree::read() instead.
Implements octomap::AbstractOcTree.
readHeader()
bool octomap::AbstractOcTree::readHeader (std::istream & s, std::string & id, unsigned & size, double & res) static protected inherited
References OCTOMAP_ERROR_STR, OCTOMAP_WARNING, OCTOMAP_WARNING_STR, and octomap::AbstractOcTree::size().
Referenced by octomap::AbstractOcTree::read(), and octomap::AbstractOccupancyOcTree::readBinary().
readNodesRecurs()
std::istream & octomap::OcTreeBaseImpl< OcTreeNode , I >::readNodesRecurs (OcTreeNode * node, std::istream & s) protected inherited
recursive call of readData()
registerTreeType()
void octomap::AbstractOcTree::registerTreeType (AbstractOcTree * tree) static protected inherited
References octomap::AbstractOcTree::getTreeType().
Referenced by octomap::OcTree::StaticMemberInitializer::StaticMemberInitializer(), octomap::CountingOcTree::StaticMemberInitializer::StaticMemberInitializer(), octomap::OcTreeStamped::StaticMemberInitializer::StaticMemberInitializer(), and octomap::ColorOcTree::StaticMemberInitializer::StaticMemberInitializer().
resetChangeDetection()
void octomap::OccupancyOcTreeBase< OcTreeNode >::resetChangeDetection inline inherited
Reset the set of changed keys. Call this after you obtained all changed nodes.
search() [1/3]
OcTreeNode * octomap::OcTreeBaseImpl< OcTreeNode , I >::search (const OcTreeKey & key, unsigned int depth = 0) const inherited
Search a node at specified depth given an addressing key (depth=0: search full tree depth) You need to check if the returned node is NULL, since it can be in unknown space.
Returns
pointer to node if found, NULL otherwise
search() [2/3]
OcTreeNode * octomap::OcTreeBaseImpl< OcTreeNode , I >::search (const point3d & value, unsigned int depth = 0) const inherited
Search node at specified depth given a 3d point (depth=0: search full tree depth) You need to check if the returned node is NULL, since it can be in unknown space.
Returns
pointer to node if found, NULL otherwise
search() [3/3]
OcTreeNode * octomap::OcTreeBaseImpl< OcTreeNode , I >::search (double x, double y, double z, unsigned int depth = 0) const inherited
Search node at specified depth given a 3d point (depth=0: search full tree depth).
You need to check if the returned node is NULL, since it can be in unknown space.
Returns
pointer to node if found, NULL otherwise
setBBXMax()
void octomap::OccupancyOcTreeBase< OcTreeNode >::setBBXMax (const point3d & max) inherited
sets the maximum for a query bounding box to use
setBBXMin()
void octomap::OccupancyOcTreeBase< OcTreeNode >::setBBXMin (const point3d & min) inherited
sets the minimum for a query bounding box to use
setClampingThresMax()
void octomap::AbstractOccupancyOcTree::setClampingThresMax (double thresProb) inline inherited
sets the maximum threshold for occupancy clamping (sensor model)
References octomap::AbstractOccupancyOcTree::clamping_thres_max, and octomap::logodds().
Referenced by octomap::AbstractOccupancyOcTree::AbstractOccupancyOcTree(), and main().
setClampingThresMin()
void octomap::AbstractOccupancyOcTree::setClampingThresMin (double thresProb) inline inherited
sets the minimum threshold for occupancy clamping (sensor model)
References octomap::AbstractOccupancyOcTree::clamping_thres_min, and octomap::logodds().
Referenced by octomap::AbstractOccupancyOcTree::AbstractOccupancyOcTree(), and main().
setNodeValue() [1/3]
OcTreeNode * octomap::OccupancyOcTreeBase< OcTreeNode >::setNodeValue (const OcTreeKey & key, float log_odds_value, bool lazy_eval = false) virtual inherited
Set log_odds value of voxel to log_odds_value.
This only works if key is at the lowest octree level
Parameters
key OcTreeKey of the NODE that is to be updated
log_odds_value value to be set as the log_odds value of the node
lazy_eval whether update of inner nodes is omitted after the update (default: false). This speeds up the insertion, but you need to call updateInnerOccupancy() when done.
Returns
pointer to the updated NODE
setNodeValue() [2/3]
OcTreeNode * octomap::OccupancyOcTreeBase< OcTreeNode >::setNodeValue (const point3d & value, float log_odds_value, bool lazy_eval = false) virtual inherited
Set log_odds value of voxel to log_odds_value.
Looks up the OcTreeKey corresponding to the coordinate and then calls setNodeValue() with it.
Parameters
value 3d coordinate of the NODE that is to be updated
log_odds_value value to be set as the log_odds value of the node
lazy_eval whether update of inner nodes is omitted after the update (default: false). This speeds up the insertion, but you need to call updateInnerOccupancy() when done.
Returns
pointer to the updated NODE
setNodeValue() [3/3]
OcTreeNode * octomap::OccupancyOcTreeBase< OcTreeNode >::setNodeValue (double x, double y, double z, float log_odds_value, bool lazy_eval = false) virtual inherited
Set log_odds value of voxel to log_odds_value.
Looks up the OcTreeKey corresponding to the coordinate and then calls setNodeValue() with it.
Parameters
x
y
z
log_odds_value value to be set as the log_odds value of the node
lazy_eval whether update of inner nodes is omitted after the update (default: false). This speeds up the insertion, but you need to call updateInnerOccupancy() when done.
Returns
pointer to the updated NODE
setNodeValueRecurs()
OcTreeNode * octomap::OccupancyOcTreeBase< OcTreeNode >::setNodeValueRecurs (OcTreeNode * node, bool node_just_created, const OcTreeKey & key, unsigned int depth, const float & log_odds_value, bool lazy_eval = false) protected inherited
setOccupancyThres()
void octomap::AbstractOccupancyOcTree::setOccupancyThres (double prob) inline inherited
sets the threshold for occupancy (sensor model)
References octomap::logodds(), and octomap::AbstractOccupancyOcTree::occ_prob_thres_log.
Referenced by octomap::AbstractOccupancyOcTree::AbstractOccupancyOcTree().
setProbHit()
void octomap::AbstractOccupancyOcTree::setProbHit (double prob) inline inherited
sets the probability for a "hit" (will be converted to logodds) - sensor model
References octomap::logodds(), and octomap::AbstractOccupancyOcTree::prob_hit_log.
Referenced by octomap::AbstractOccupancyOcTree::AbstractOccupancyOcTree(), and main().
setProbMiss()
void octomap::AbstractOccupancyOcTree::setProbMiss (double prob) inline inherited
sets the probability for a "miss" (will be converted to logodds) - sensor model
References octomap::logodds(), and octomap::AbstractOccupancyOcTree::prob_miss_log.
Referenced by octomap::AbstractOccupancyOcTree::AbstractOccupancyOcTree(), and main().
setResolution()
void octomap::OcTreeBaseImpl< OcTreeNode , I >::setResolution (double r) virtual inherited
Change the resolution of the octree, scaling all voxels. This will not preserve the (metric) scale!
Implements octomap::AbstractOcTree.
size() [1/2]
virtual size_t octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::size inline virtual inherited
Returns
The number of nodes in the tree
size() [2/2]
virtual size_t octomap::AbstractOcTree::size () const pure virtual inherited
Referenced by main(), octomap::AbstractOcTree::read(), octomap::AbstractOccupancyOcTree::readBinary(), octomap::AbstractOccupancyOcTree::readBinaryLegacyHeader(), octomap::AbstractOcTree::readHeader(), octomap::AbstractOcTree::write(), and octomap::AbstractOccupancyOcTree::writeBinaryConst().
swapContent()
void octomap::OcTreeBaseImpl< OcTreeNode , I >::swapContent (OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree > & rhs) inherited
Swap contents of two octrees, i.e., only the underlying pointer / tree structure.
You have to ensure yourself that the metadata (resolution etc) matches. No memory is cleared in this function
toMaxLikelihood()
void octomap::OccupancyOcTreeBase< OcTreeNode >::toMaxLikelihood virtual inherited
Creates the maximum likelihood map by calling toMaxLikelihood on all tree nodes, setting their occupancy to the corresponding occupancy thresholds.
This enables a very efficient compression if you call prune() afterwards.
Implements octomap::AbstractOccupancyOcTree.
toMaxLikelihoodRecurs()
void octomap::OccupancyOcTreeBase< OcTreeNode >::toMaxLikelihoodRecurs (OcTreeNode * node, unsigned int depth, unsigned int max_depth) protected inherited
updateInnerOccupancy()
void octomap::OccupancyOcTreeBase< OcTreeNode >::updateInnerOccupancy inherited
Updates the occupancy of all inner nodes to reflect their children's occupancy.
If you performed batch-updates with lazy evaluation enabled, you must call this before any queries to ensure correct multi-resolution behavior.
updateInnerOccupancyRecurs()
void octomap::OccupancyOcTreeBase< OcTreeNode >::updateInnerOccupancyRecurs (OcTreeNode * node, unsigned int depth) protected inherited
updateNode() [1/6]
OcTreeNode * octomap::OccupancyOcTreeBase< OcTreeNode >::updateNode (const OcTreeKey & key, bool occupied, bool lazy_eval = false) virtual inherited
Integrate occupancy measurement.
Parameters
key OcTreeKey of the NODE that is to be updated
occupied true if the node was measured occupied, else false
lazy_eval whether update of inner nodes is omitted after the update (default: false). This speeds up the insertion, but you need to call updateInnerOccupancy() when done.
Returns
pointer to the updated NODE
Implements octomap::AbstractOccupancyOcTree.
updateNode() [2/6]
OcTreeNode * octomap::OccupancyOcTreeBase< OcTreeNode >::updateNode (const OcTreeKey & key, float log_odds_update, bool lazy_eval = false) virtual inherited
Manipulate log_odds value of a voxel by changing it by log_odds_update (relative).
This only works if key is at the lowest octree level
Parameters
key OcTreeKey of the NODE that is to be updated
log_odds_update value to be added (+) to log_odds value of node
lazy_eval whether update of inner nodes is omitted after the update (default: false). This speeds up the insertion, but you need to call updateInnerOccupancy() when done.
Returns
pointer to the updated NODE
Implements octomap::AbstractOccupancyOcTree.
updateNode() [3/6]
OcTreeNode * octomap::OccupancyOcTreeBase< OcTreeNode >::updateNode (const point3d & value, bool occupied, bool lazy_eval = false) virtual inherited
Integrate occupancy measurement.
Looks up the OcTreeKey corresponding to the coordinate and then calls udpateNode() with it.
Parameters
value 3d coordinate of the NODE that is to be updated
occupied true if the node was measured occupied, else false
lazy_eval whether update of inner nodes is omitted after the update (default: false). This speeds up the insertion, but you need to call updateInnerOccupancy() when done.
Returns
pointer to the updated NODE
Implements octomap::AbstractOccupancyOcTree.
updateNode() [4/6]
OcTreeNode * octomap::OccupancyOcTreeBase< OcTreeNode >::updateNode (const point3d & value, float log_odds_update, bool lazy_eval = false) virtual inherited
Manipulate log_odds value of a voxel by changing it by log_odds_update (relative).
Looks up the OcTreeKey corresponding to the coordinate and then calls updateNode() with it.
Parameters
value 3d coordinate of the NODE that is to be updated
log_odds_update value to be added (+) to log_odds value of node
lazy_eval whether update of inner nodes is omitted after the update (default: false). This speeds up the insertion, but you need to call updateInnerOccupancy() when done.
Returns
pointer to the updated NODE
Implements octomap::AbstractOccupancyOcTree.
updateNode() [5/6]
OcTreeNode * octomap::OccupancyOcTreeBase< OcTreeNode >::updateNode (double x, double y, double z, bool occupied, bool lazy_eval = false) virtual inherited
Integrate occupancy measurement.
Looks up the OcTreeKey corresponding to the coordinate and then calls udpateNode() with it.
Parameters
x
y
z
occupied true if the node was measured occupied, else false
lazy_eval whether update of inner nodes is omitted after the update (default: false). This speeds up the insertion, but you need to call updateInnerOccupancy() when done.
Returns
pointer to the updated NODE
updateNode() [6/6]
OcTreeNode * octomap::OccupancyOcTreeBase< OcTreeNode >::updateNode (double x, double y, double z, float log_odds_update, bool lazy_eval = false) virtual inherited
Manipulate log_odds value of a voxel by changing it by log_odds_update (relative).
Looks up the OcTreeKey corresponding to the coordinate and then calls updateNode() with it.
Parameters
x
y
z
log_odds_update value to be added (+) to log_odds value of node
lazy_eval whether update of inner nodes is omitted after the update (default: false). This speeds up the insertion, but you need to call updateInnerOccupancy() when done.
Returns
pointer to the updated NODE
updateNodeLogOdds()
void octomap::OccupancyOcTreeBase< OcTreeNode >::updateNodeLogOdds (OcTreeNode * occupancyNode, const float & update) const virtual inherited
update logodds value of node by adding to the current value.
updateNodeRecurs()
OcTreeNode * octomap::OccupancyOcTreeBase< OcTreeNode >::updateNodeRecurs (OcTreeNode * node, bool node_just_created, const OcTreeKey & key, unsigned int depth, const float & log_odds_update, bool lazy_eval = false) protected inherited
useBBXLimit()
void octomap::OccupancyOcTreeBase< OcTreeNode >::useBBXLimit (bool enable) inline inherited
use or ignore BBX limit (default: ignore)
volume()
double octomap::OcTreeBaseImpl< OcTreeNode , I >::volume inherited
write() [1/2]
bool octomap::AbstractOcTree::write (const std::string & filename) const inherited
Write file header and complete tree to file (serialization)
References OCTOMAP_ERROR_STR.
Referenced by main().
write() [2/2]
bool octomap::AbstractOcTree::write (std::ostream & s) const inherited
Write file header and complete tree to stream (serialization)
References octomap::AbstractOcTree::fileHeader, octomap::AbstractOcTree::getResolution(), octomap::AbstractOcTree::getTreeType(), octomap::AbstractOcTree::size(), and octomap::AbstractOcTree::writeData().
writeBinary() [1/2]
bool octomap::AbstractOccupancyOcTree::writeBinary (const std::string & filename) inherited
Writes OcTree to a binary file using writeBinary().
The OcTree is first converted to the maximum likelihood estimate and pruned.
Returns
success of operation
References OCTOMAP_ERROR_STR.
Referenced by main().
writeBinary() [2/2]
bool octomap::AbstractOccupancyOcTree::writeBinary (std::ostream & s) inherited
Writes compressed maximum likelihood OcTree to a binary stream.
The OcTree is first converted to the maximum likelihood estimate and pruned for maximum compression.
Returns
success of operation
References octomap::AbstractOcTree::prune(), octomap::AbstractOccupancyOcTree::toMaxLikelihood(), and octomap::AbstractOccupancyOcTree::writeBinaryConst().
writeBinaryConst() [1/2]
bool octomap::AbstractOccupancyOcTree::writeBinaryConst (const std::string & filename) const inherited
Writes OcTree to a binary file using writeBinaryConst().
The OcTree is not changed, in particular not pruned first. Files will be smaller when the tree is pruned first or by using writeBinary() instead.
Returns
success of operation
References OCTOMAP_ERROR_STR.
Referenced by octomap::AbstractOccupancyOcTree::writeBinary().
writeBinaryConst() [2/2]
bool octomap::AbstractOccupancyOcTree::writeBinaryConst (std::ostream & s) const inherited
Writes the maximum likelihood OcTree to a binary stream (const variant).
Files will be smaller when the tree is pruned first or by using writeBinary() instead.
Returns
success of operation
References octomap::AbstractOccupancyOcTree::binaryFileHeader, octomap::AbstractOcTree::getResolution(), octomap::AbstractOcTree::getTreeType(), OCTOMAP_DEBUG, OCTOMAP_WARNING_STR, octomap::AbstractOcTree::size(), and octomap::AbstractOccupancyOcTree::writeBinaryData().
writeBinaryData()
std::ostream & octomap::OccupancyOcTreeBase< OcTreeNode >::writeBinaryData (std::ostream & s) const virtual inherited
Writes the data of the tree (without header) to the stream, recursively calling writeBinaryNode (starting with root)
Implements octomap::AbstractOccupancyOcTree.
writeBinaryNode()
std::ostream & octomap::OccupancyOcTreeBase< OcTreeNode >::writeBinaryNode (std::ostream & s, const OcTreeNode * node) const inherited
Write node to binary stream (max-likelihood value), recursively continue with all children.
This will discard the log_odds_occupancy value, writing all leaves as either free or occupied.
Parameters
s
node OcTreeNode to write out, will recurse to all children
Returns
writeData()
std::ostream & octomap::OcTreeBaseImpl< OcTreeNode , I >::writeData (std::ostream & s) const virtual inherited
Write complete state of tree to stream (without file header) unmodified. Pruning the tree first produces smaller files (lossless compression)
Implements octomap::AbstractOcTree.
writeNodesRecurs()
std::ostream & octomap::OcTreeBaseImpl< OcTreeNode , I >::writeNodesRecurs (const OcTreeNode * node, std::ostream & s) const protected inherited
recursive call of writeData()
Field Documentation
bbx_max
point3d octomap::OccupancyOcTreeBase< OcTreeNode >::bbx_max protected inherited
bbx_max_key
OcTreeKey octomap::OccupancyOcTreeBase< OcTreeNode >::bbx_max_key protected inherited
bbx_min
point3d octomap::OccupancyOcTreeBase< OcTreeNode >::bbx_min protected inherited
bbx_min_key
OcTreeKey octomap::OccupancyOcTreeBase< OcTreeNode >::bbx_min_key protected inherited
binaryFileHeader
const std::string octomap::AbstractOccupancyOcTree::binaryFileHeader = "# Octomap OcTree binary file" static protected inherited
Referenced by octomap::AbstractOccupancyOcTree::readBinary(), and octomap::AbstractOccupancyOcTree::writeBinaryConst().
changed_keys
KeyBoolMap octomap::OccupancyOcTreeBase< OcTreeNode >::changed_keys protected inherited
Set of leaf keys (lowest level) which changed since last resetChangeDetection.
clamping_thres_max
float octomap::AbstractOccupancyOcTree::clamping_thres_max protected inherited
Referenced by octomap::AbstractOccupancyOcTree::getClampingThresMax(), octomap::AbstractOccupancyOcTree::getClampingThresMaxLog(), octomap::OccupancyOcTreeBase< OcTreeNodeStamped >::OccupancyOcTreeBase(), and octomap::AbstractOccupancyOcTree::setClampingThresMax().
clamping_thres_min
float octomap::AbstractOccupancyOcTree::clamping_thres_min protected inherited
Referenced by octomap::AbstractOccupancyOcTree::getClampingThresMin(), octomap::AbstractOccupancyOcTree::getClampingThresMinLog(), octomap::OccupancyOcTreeBase< OcTreeNodeStamped >::OccupancyOcTreeBase(), and octomap::AbstractOccupancyOcTree::setClampingThresMin().
fileHeader
const std::string octomap::AbstractOcTree::fileHeader = "# Octomap OcTree file" static protected inherited
Referenced by octomap::AbstractOcTree::read(), and octomap::AbstractOcTree::write().
keyrays
std::vector<KeyRay> octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::keyrays protected inherited
data structure for ray casting, array for multithreading
leaf_iterator_bbx_end
const leaf_bbx_iterator octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::leaf_iterator_bbx_end protected inherited
leaf_iterator_end
const leaf_iterator octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::leaf_iterator_end protected inherited
max_value
double octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::max_value[3] protected inherited
max in x, y, z
min_value
double octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::min_value[3] protected inherited
min in x, y, z contains the size of a voxel at level i (0: root node). tree_depth+1 levels (incl. 0)
occ_prob_thres_log
float octomap::AbstractOccupancyOcTree::occ_prob_thres_log protected inherited
Referenced by octomap::AbstractOccupancyOcTree::getOccupancyThres(), octomap::AbstractOccupancyOcTree::getOccupancyThresLog(), octomap::OccupancyOcTreeBase< OcTreeNodeStamped >::OccupancyOcTreeBase(), and octomap::AbstractOccupancyOcTree::setOccupancyThres().
ocTreeMemberInit
OcTree::StaticMemberInitializer octomap::OcTree::ocTreeMemberInit static protected
to ensure static initialization (only once)
Referenced by OcTree().
prob_hit_log
float octomap::AbstractOccupancyOcTree::prob_hit_log protected inherited
Referenced by octomap::AbstractOccupancyOcTree::getProbHit(), octomap::AbstractOccupancyOcTree::getProbHitLog(), octomap::OccupancyOcTreeBase< OcTreeNodeStamped >::OccupancyOcTreeBase(), and octomap::AbstractOccupancyOcTree::setProbHit().
prob_miss_log
float octomap::AbstractOccupancyOcTree::prob_miss_log protected inherited
Referenced by octomap::AbstractOccupancyOcTree::getProbMiss(), octomap::AbstractOccupancyOcTree::getProbMissLog(), octomap::OcTreeStamped::integrateMissNoTime(), octomap::OccupancyOcTreeBase< OcTreeNodeStamped >::OccupancyOcTreeBase(), and octomap::AbstractOccupancyOcTree::setProbMiss().
resolution
double octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::resolution protected inherited
in meters
resolution_factor
double octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::resolution_factor protected inherited
= 1. / resolution
root
OcTreeNode * octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::root protected inherited
Pointer to the root NODE, NULL for empty tree.
size_changed
bool octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::size_changed protected inherited
sizeLookupTable
std::vector<double> octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::sizeLookupTable protected inherited
tree_center
point3d octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::tree_center protected inherited
tree_depth
const unsigned int octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::tree_depth protected inherited
Maximum tree depth is fixed to 16 currently.
tree_iterator_end
const tree_iterator octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::tree_iterator_end protected inherited
tree_max_val
const unsigned int octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::tree_max_val protected inherited
tree_size
size_t octomap::OcTreeBaseImpl< OcTreeNode , AbstractOccupancyOcTree >::tree_size protected inherited
number of nodes in tree flag to denote whether the octree extent changed (for lazy min/max eval)
use_bbx_limit
bool octomap::OccupancyOcTreeBase< OcTreeNode >::use_bbx_limit protected inherited
use bounding box for queries (needs to be set)?
use_change_detection
bool octomap::OccupancyOcTreeBase< OcTreeNode >::use_change_detection protected inherited
The documentation for this class was generated from the following files:
include/octomap/OcTree.h
src/OcTree.cpp