octomap: octomap::MapCollection< MAPNODE > Class Template Reference
octomap::MapCollection< MAPNODE > Class Template Reference
Public Types
typedef std::vector< MAPNODE * >::const_iterator const_iterator
typedef std::vector< MAPNODE * >::iterator iterator
Public Member Functions
MAPNODE * addNode (const Pointcloud &cloud, point3d sensor_origin)
void addNode (MAPNODE *node)
iterator begin ()
const_iterator begin () const
bool castRay (const point3d &origin, const point3d &direction, point3d &end, bool ignoreUnknownCells=false, double maxRange=-1.0) const
iterator end ()
const_iterator end () const
double getOccupancy (const point3d &p)
void insertScan (const Pointcloud &scan, const octomap::point3d &sensor_origin, double maxrange=-1., bool pruning=true, bool lazy_eval=false)
bool isOccupied (const point3d &p) const
bool isOccupied (float x, float y, float z) const
MapCollection ()
MapCollection (std::string filename)
MAPNODE * queryNode (const point3d &p)
MAPNODE * queryNode (std::string id)
bool removeNode (const MAPNODE *n)
size_t size () const
bool write (std::string filename)
bool writePointcloud (std::string filename)
~MapCollection ()
Protected Member Functions
MAPNODE * associate (const Pointcloud &scan)
void clear ()
bool read (std::string filename)
std::vector< Pointcloud * > segment (const Pointcloud &scan) const
Static Protected Member Functions
static std::string combinePathAndFilename (std::string path, std::string filename)
static bool readTagValue (std::string tag, std::ifstream &infile, std::string *value)
static void splitPathAndFilename (std::string &filenamefullpath, std::string *path, std::string *filename)
Protected Attributes
std::vector< MAPNODE * > nodes
Member Typedef Documentation
const_iterator
template<class MAPNODE > typedef std::vector<MAPNODE*>::const_iterator octomap::MapCollection< MAPNODE >::const_iterator
iterator
template<class MAPNODE > typedef std::vector<MAPNODE*>::iterator octomap::MapCollection< MAPNODE >::iterator
Constructor & Destructor Documentation
MapCollection() [1/2]
template<class MAPNODE > octomap::MapCollection< MAPNODE >::MapCollection
MapCollection() [2/2]
template<class MAPNODE > octomap::MapCollection< MAPNODE >::MapCollection (std::string filename)
~MapCollection()
template<class MAPNODE > octomap::MapCollection< MAPNODE >::~MapCollection
Member Function Documentation
addNode() [1/2]
template<class MAPNODE > MAPNODE * octomap::MapCollection< MAPNODE >::addNode (const Pointcloud & cloud, point3d sensor_origin)
addNode() [2/2]
template<class MAPNODE > void octomap::MapCollection< MAPNODE >::addNode (MAPNODE * node)
associate()
template<class MAPNODE > MAPNODE * octomap::MapCollection< MAPNODE >::associate (const Pointcloud & scan) protected
begin() [1/2]
template<class MAPNODE > iterator octomap::MapCollection< MAPNODE >::begin () inline
References octomap::MapCollection< MAPNODE >::nodes.
begin() [2/2]
template<class MAPNODE > const_iterator octomap::MapCollection< MAPNODE >::begin () const inline
References octomap::MapCollection< MAPNODE >::nodes.
castRay()
template<class MAPNODE > bool octomap::MapCollection< MAPNODE >::castRay (const point3d & origin, const point3d & direction, point3d & end, bool ignoreUnknownCells = false, double maxRange = -1.0) const
References octomath::Vector3::distance(), octomath::Vector3::x(), octomath::Vector3::y(), and octomath::Vector3::z().
Referenced by main().
clear()
template<class MAPNODE > void octomap::MapCollection< MAPNODE >::clear protected
combinePathAndFilename()
template<class MAPNODE > std::string octomap::MapCollection< MAPNODE >::combinePathAndFilename (std::string path, std::string filename) static protected
end() [1/2]
template<class MAPNODE > iterator octomap::MapCollection< MAPNODE >::end () inline
References octomap::MapCollection< MAPNODE >::nodes.
end() [2/2]
template<class MAPNODE > const_iterator octomap::MapCollection< MAPNODE >::end () const inline
References octomap::MapCollection< MAPNODE >::nodes.
getOccupancy()
template<class MAPNODE > double octomap::MapCollection< MAPNODE >::getOccupancy (const point3d & p)
Referenced by main().
insertScan()
template<class MAPNODE > void octomap::MapCollection< MAPNODE >::insertScan (const Pointcloud & scan, const octomap::point3d & sensor_origin, double maxrange = -1., bool pruning = true, bool lazy_eval = false)
isOccupied() [1/2]
template<class MAPNODE > bool octomap::MapCollection< MAPNODE >::isOccupied (const point3d & p) const
Referenced by main().
isOccupied() [2/2]
template<class MAPNODE > bool octomap::MapCollection< MAPNODE >::isOccupied (float x, float y, float z) const
queryNode() [1/2]
template<class MAPNODE > MAPNODE * octomap::MapCollection< MAPNODE >::queryNode (const point3d & p)
queryNode() [2/2]
template<class MAPNODE > MAPNODE * octomap::MapCollection< MAPNODE >::queryNode (std::string id)
read()
template<class MAPNODE > bool octomap::MapCollection< MAPNODE >::read (std::string filename) protected
References OCTOMAP_ERROR_STR.
readTagValue()
template<class MAPNODE > bool octomap::MapCollection< MAPNODE >::readTagValue (std::string tag, std::ifstream & infile, std::string * value) static protected
removeNode()
template<class MAPNODE > bool octomap::MapCollection< MAPNODE >::removeNode (const MAPNODE * n)
segment()
template<class MAPNODE > std::vector< Pointcloud * > octomap::MapCollection< MAPNODE >::segment (const Pointcloud & scan) const protected
size()
template<class MAPNODE > size_t octomap::MapCollection< MAPNODE >::size () const inline
References octomap::MapCollection< MAPNODE >::nodes.
Referenced by main().
splitPathAndFilename()
template<class MAPNODE > void octomap::MapCollection< MAPNODE >::splitPathAndFilename (std::string & filenamefullpath, std::string * path, std::string * filename) static protected
write()
template<class MAPNODE > bool octomap::MapCollection< MAPNODE >::write (std::string filename)
References octomath::Pose6D::pitch(), octomath::Pose6D::roll(), octomath::Pose6D::x(), octomath::Pose6D::y(), octomath::Pose6D::yaw(), and octomath::Pose6D::z().
Referenced by main().
writePointcloud()
template<class MAPNODE > bool octomap::MapCollection< MAPNODE >::writePointcloud (std::string filename)
References octomap::Pointcloud::push_back(), and octomap::Pointcloud::writeVrml().
Field Documentation
nodes
template<class MAPNODE > std::vector<MAPNODE*> octomap::MapCollection< MAPNODE >::nodes protected
Referenced by octomap::MapCollection< MAPNODE >::begin(), octomap::MapCollection< MAPNODE >::end(), and octomap::MapCollection< MAPNODE >::size().
The documentation for this class was generated from the following files:
include/octomap/MapCollection.h
include/octomap/MapCollection.hxx