octomap: octomap::ColorOcTreeNode Class Reference
octomap::ColorOcTreeNode Class Reference
Data Structures
class Color
Public Types
typedef float DataType
Make the templated data type available from the outside.
Public Member Functions
void addValue (const float &p)
adds p to the node's logOdds value (with no boundary / threshold checking!)
bool childExists (unsigned int i) const
Safe test to check of the i-th child exists, first tests if there are any children.
bool collapsible () const
A node is collapsible if all children exist, don't have children of their own and have the same occupancy value.
ColorOcTreeNode ()
ColorOcTreeNode (const ColorOcTreeNode &rhs)
bool createChild (unsigned int i)
initialize i-th child, allocate children array if needed
void deleteChild (unsigned int i)
Deletes the i-th child of the node.
void expandNode ()
Expands a node (reverse of pruning): All children are created and their occupancy probability is set to the node's value.
ColorOcTreeNode::Color getAverageChildColor () const
ColorOcTreeNode * getChild (unsigned int i)
const ColorOcTreeNode * getChild (unsigned int i) const
Color getColor () const
Color & getColor ()
float getLogOdds () const
float getMaxChildLogOdds () const
double getMeanChildLogOdds () const
double getOccupancy () const
float getValue () const
bool hasChildren () const
bool isColorSet () const
bool operator== (const ColorOcTreeNode &rhs) const
bool operator== (const OcTreeDataNode &rhs) const
Equals operator, compares if the stored value is identical.
bool pruneNode ()
Prunes a node when it is collapsible.
std::istream & readValue (std::istream &s)
Read node from binary stream (incl.
void setColor (Color c)
void setColor (unsigned char r, unsigned char g, unsigned char b)
void setLogOdds (float l)
sets log odds occupancy of node
void setValue (floatv)
sets value to be stored in the node
void updateColorChildren ()
void updateOccupancyChildren ()
update this node's occupancy according to its children's maximum occupancy
std::ostream & writeValue (std::ostream &s) const
Write node to binary stream (incl float value), recursively continue with all children.
Protected Member Functions
void allocChildren ()
Protected Attributes
OcTreeDataNode< float > ** children
pointer to array of children, may be NULL
Color color
float value
stored data (payload)
Member Typedef Documentation
typedef float octomap::OcTreeDataNode< float >::DataType inherited
Make the templated data type available from the outside.
Constructor & Destructor Documentation
octomap::ColorOcTreeNode::ColorOcTreeNode () inline
Referenced by createChild().
octomap::ColorOcTreeNode::ColorOcTreeNode (const ColorOcTreeNode & rhs) inline
Member Function Documentation
void octomap::OcTreeNode::addValue (const float & p) inherited
adds p to the node's logOdds value (with no boundary / threshold checking!)
References octomap::OcTreeDataNode< float >::value.
void octomap::OcTreeDataNode< float >::allocChildren () protected inherited
Referenced by octomap::OcTreeNode::createChild(), octomap::OcTreeNodeStamped::createChild(), and createChild().
bool octomap::OcTreeDataNode< float >::childExists (unsigned int i) const inherited
Safe test to check of the i-th child exists, first tests if there are any children.
Returns
true if the i-th child exists
Referenced by getAverageChildColor(), octomap::OcTreeNode::getMaxChildLogOdds(), octomap::OcTreeNode::getMeanChildLogOdds(), and writeValue().
bool octomap::OcTreeDataNode< float >::collapsible () const inherited
A node is collapsible if all children exist, don't have children of their own and have the same occupancy value.
Referenced by pruneNode().
bool octomap::ColorOcTreeNode::createChild (unsigned int i) inline
initialize i-th child, allocate children array if needed
Reimplemented from octomap::OcTreeNode.
References octomap::OcTreeDataNode< float >::allocChildren(), octomap::OcTreeDataNode< float >::children, and ColorOcTreeNode().
Referenced by expandNode(), and readValue().
void octomap::OcTreeDataNode< float >::deleteChild (unsigned int i) inherited
Deletes the i-th child of the node.
void octomap::ColorOcTreeNode::expandNode ()
Expands a node (reverse of pruning): All children are created and their occupancy probability is set to the node's value.
You need to verify that this is indeed a pruned node (i.e. not a leaf at the lowest level)
Reimplemented from octomap::OcTreeDataNode< float >.
References octomap::OcTreeDataNode< float >::children, color, createChild(), getChild(), octomap::OcTreeDataNode< float >::hasChildren(), setColor(), octomap::OcTreeDataNode< T >::setValue(), and octomap::OcTreeDataNode< float >::value.
ColorOcTreeNode::Color octomap::ColorOcTreeNode::getAverageChildColor () const
References octomap::ColorOcTreeNode::Color::b, octomap::OcTreeDataNode< float >::childExists(), octomap::ColorOcTreeNode::Color::g, getChild(), getColor(), isColorSet(), and octomap::ColorOcTreeNode::Color::r.
Referenced by pruneNode(), and updateColorChildren().
ColorOcTreeNode* octomap::ColorOcTreeNode::getChild (unsigned int i) inline
Returns
a pointer to the i-th child of the node. The child needs to exist.
Reimplemented from octomap::OcTreeNode.
Referenced by expandNode(), getAverageChildColor(), getChild(), pruneNode(), readValue(), octomap::ColorOcTree::updateInnerOccupancyRecurs(), and writeValue().
const ColorOcTreeNode* octomap::ColorOcTreeNode::getChild (unsigned int i) const inline
Returns
a const pointer to the i-th child of the node. The child needs to exist.
Reimplemented from octomap::OcTreeNode.
References getChild().
Color octomap::ColorOcTreeNode::getColor () const inline
References color.
Referenced by octomap::ColorOcTree::averageNodeColor(), getAverageChildColor(), octomap::ColorOcTree::integrateNodeColor(), main(), and print_query_info().
Color& octomap::ColorOcTreeNode::getColor () inline
References color.
float octomap::OcTreeNode::getLogOdds () const inline inherited
Returns
log odds representation of occupancy probability of node
References octomap::OcTreeDataNode< float >::value.
Referenced by octomap::OcTreeNode::getMaxChildLogOdds(), octomap::AbstractOccupancyOcTree::isNodeAtThreshold(), octomap::AbstractOccupancyOcTree::isNodeOccupied(), main(), and pruneNode().
float octomap::OcTreeNode::getMaxChildLogOdds () const inherited
Returns
maximum of children's occupancy probabilities, in log odds
References octomap::OcTreeDataNode< float >::childExists(), octomap::OcTreeNode::getChild(), and octomap::OcTreeNode::getLogOdds().
Referenced by octomap::OcTreeNodeStamped::updateOccupancyChildren(), and octomap::OcTreeNode::updateOccupancyChildren().
double octomap::OcTreeNode::getMeanChildLogOdds () const inherited
Returns
mean of all children's occupancy probabilities, in log odds
References octomap::OcTreeDataNode< float >::childExists(), octomap::OcTreeNode::getChild(), and octomap::OcTreeNode::getOccupancy().
double octomap::OcTreeNode::getOccupancy () const inline inherited
Returns
occupancy probability of node
References octomap::probability(), and octomap::OcTreeDataNode< float >::value.
Referenced by octomap::OcTreeNode::getMeanChildLogOdds(), octomap::ColorOcTree::integrateNodeColor(), main(), and print_query_info().
float octomap::OcTreeDataNode< float >::getValue () const inline inherited
Returns
value stored in the node
bool octomap::OcTreeDataNode< float >::hasChildren () const inherited
Returns
true if the node has at least one child
Referenced by expandNode().
bool octomap::ColorOcTreeNode::isColorSet () const inline
References octomap::ColorOcTreeNode::Color::b, color, octomap::ColorOcTreeNode::Color::g, and octomap::ColorOcTreeNode::Color::r.
Referenced by octomap::ColorOcTree::averageNodeColor(), getAverageChildColor(), octomap::ColorOcTree::integrateNodeColor(), and pruneNode().
bool octomap::ColorOcTreeNode::operator== (const ColorOcTreeNode & rhs) const inline
References color, octomap::OcTreeDataNode< T >::value, and octomap::OcTreeDataNode< float >::value.
bool octomap::OcTreeDataNode< float >::operator== (const OcTreeDataNode< float > & rhs) const inherited
Equals operator, compares if the stored value is identical.
bool octomap::ColorOcTreeNode::pruneNode ()
Prunes a node when it is collapsible.
Returns
true if pruning was successful
Reimplemented from octomap::OcTreeDataNode< float >.
References octomap::OcTreeDataNode< float >::children, octomap::OcTreeDataNode< float >::collapsible(), color, getAverageChildColor(), getChild(), octomap::OcTreeNode::getLogOdds(), isColorSet(), and octomap::OcTreeNode::setLogOdds().
std::istream & octomap::ColorOcTreeNode::readValue (std::istream & s)
Read node from binary stream (incl.
float value), recursively continue with all children.
Parameters
s
Returns
Reimplemented from octomap::OcTreeDataNode< float >.
References octomap::OcTreeDataNode< float >::children, color, createChild(), getChild(), readValue(), and octomap::OcTreeDataNode< float >::value.
Referenced by readValue().
void octomap::ColorOcTreeNode::setColor (Color c) inline
References color.
Referenced by octomap::ColorOcTree::averageNodeColor(), expandNode(), octomap::ColorOcTree::integrateNodeColor(), main(), and octomap::ColorOcTree::setNodeColor().
void octomap::ColorOcTreeNode::setColor (unsigned char r, unsigned char g, unsigned char b) inline
References color.
void octomap::OcTreeNode::setLogOdds (float l) inline inherited
sets log odds occupancy of node
References octomap::OcTreeDataNode< float >::value.
Referenced by pruneNode(), octomap::OcTreeNodeStamped::updateOccupancyChildren(), and octomap::OcTreeNode::updateOccupancyChildren().
void octomap::OcTreeDataNode< float >::setValue (float v) inline inherited
sets value to be stored in the node
void octomap::ColorOcTreeNode::updateColorChildren ()
References color, and getAverageChildColor().
Referenced by octomap::ColorOcTree::updateInnerOccupancyRecurs().
void octomap::OcTreeNode::updateOccupancyChildren () inline inherited
update this node's occupancy according to its children's maximum occupancy
Reimplemented in octomap::OcTreeNodeStamped.
References octomap::OcTreeNode::getMaxChildLogOdds(), and octomap::OcTreeNode::setLogOdds().
Referenced by octomap::ColorOcTree::updateInnerOccupancyRecurs().
std::ostream & octomap::ColorOcTreeNode::writeValue (std::ostream & s) const
Write node to binary stream (incl float value), recursively continue with all children.
This preserves the complete state of the node.
Parameters
s
Returns
Reimplemented from octomap::OcTreeDataNode< float >.
References octomap::OcTreeDataNode< float >::childExists(), octomap::OcTreeDataNode< float >::children, color, getChild(), octomap::OcTreeDataNode< float >::value, and writeValue().
Referenced by writeValue().
Field Documentation
OcTreeDataNode<float >** octomap::OcTreeDataNode< float >::children protected inherited
pointer to array of children, may be NULL
Referenced by octomap::OcTreeNode::createChild(), octomap::OcTreeNodeStamped::createChild(), createChild(), expandNode(), pruneNode(), readValue(), and writeValue().
Color octomap::ColorOcTreeNode::color protected
Referenced by expandNode(), getColor(), isColorSet(), operator==(), pruneNode(), readValue(), setColor(), updateColorChildren(), and writeValue().
float octomap::OcTreeDataNode< float >::value protected inherited
stored data (payload)
Referenced by octomap::OcTreeNode::addValue(), expandNode(), octomap::OcTreeNode::getLogOdds(), octomap::OcTreeNode::getOccupancy(), octomap::OcTreeNodeStamped::operator==(), operator==(), readValue(), octomap::OcTreeNode::setLogOdds(), and writeValue().
The documentation for this class was generated from the following files:
include/octomap/ColorOcTree.h
src/ColorOcTree.cpp