octomap: octomap::Pointcloud Class Reference
octomap::Pointcloud Class Reference
A collection of 3D coordinates (point3d), which are regarded as endpoints of a 3D laser scan.
Public Types
typedef point3d_collection::const_iterator const_iterator
typedef point3d_collection::iterator iterator
Public Member Functions
point3d back ()
iterator begin ()
const_iterator begin () const
void calcBBX (point3d &lowerBound, point3d &upperBound) const
Calculate bounding box of Pointcloud.
void clear ()
void crop (point3d lowerBound, point3d upperBound)
Crop Pointcloud to given bounding box.
iterator end ()
const_iterator end () const
point3d getPoint (unsigned int i) const
Returns a copy of the ith point in point cloud. Use operator[] for direct access to point reference.
void minDist (double thres)
point3d & operator[] (size_t i)
const point3d & operator[] (size_t i) const
Pointcloud ()
Pointcloud (const Pointcloud &other)
Pointcloud (Pointcloud *other)
void push_back (const point3d &p)
void push_back (const Pointcloud &other)
Add points from other Pointcloud.
void push_back (float x, float y, float z)
void push_back (point3d *p)
std::istream & read (std::istream &s)
std::istream & readBinary (std::istream &s)
void reserve (size_t size)
void rotate (double roll, double pitch, double yaw)
Rotate each point in pointcloud.
size_t size () const
void subSampleRandom (unsigned int num_samples, Pointcloud &sample_cloud)
void transform (pose6d transform)
Apply transform to each point.
void transformAbsolute (pose6d transform)
Apply transform to each point, undo previous transforms.
std::ostream & writeBinary (std::ostream &s) const
void writeVrml (std::string filename)
Export the Pointcloud to a VRML file.
~Pointcloud ()
Protected Attributes
pose6d current_inv_transform
point3d_collection points
Detailed Description
A collection of 3D coordinates (point3d), which are regarded as endpoints of a 3D laser scan.
Member Typedef Documentation
const_iterator
typedef point3d_collection::const_iterator octomap::Pointcloud::const_iterator
iterator
typedef point3d_collection::iterator octomap::Pointcloud::iterator
Constructor & Destructor Documentation
Pointcloud() [1/3]
octomap::Pointcloud::Pointcloud ()
~Pointcloud()
octomap::Pointcloud::~Pointcloud ()
References clear().
Pointcloud() [2/3]
octomap::Pointcloud::Pointcloud (const Pointcloud & other)
References begin(), end(), and points.
Pointcloud() [3/3]
octomap::Pointcloud::Pointcloud (Pointcloud * other)
References begin(), end(), and points.
Member Function Documentation
back()
point3d octomap::Pointcloud::back () inline
References points.
begin() [1/2]
iterator octomap::Pointcloud::begin () inline
References points.
Referenced by calcBBX(), crop(), minDist(), Pointcloud(), push_back(), subSampleRandom(), and writeBinary().
begin() [2/2]
const_iterator octomap::Pointcloud::begin () const inline
References points.
calcBBX()
void octomap::Pointcloud::calcBBX (point3d & lowerBound, point3d & upperBound) const
Calculate bounding box of Pointcloud.
References begin(), and end().
clear()
void octomap::Pointcloud::clear ()
References points.
Referenced by crop(), minDist(), and ~Pointcloud().
crop()
void octomap::Pointcloud::crop (point3d lowerBound, point3d upperBound)
Crop Pointcloud to given bounding box.
References begin(), clear(), end(), and push_back().
Referenced by octomap::ScanGraph::crop().
end() [1/2]
iterator octomap::Pointcloud::end () inline
References points.
Referenced by calcBBX(), crop(), minDist(), Pointcloud(), push_back(), subSampleRandom(), and writeBinary().
end() [2/2]
const_iterator octomap::Pointcloud::end () const inline
References points.
getPoint()
point3d octomap::Pointcloud::getPoint (unsigned int i) const
Returns a copy of the ith point in point cloud. Use operator[] for direct access to point reference.
References OCTOMAP_WARNING, and points.
minDist()
void octomap::Pointcloud::minDist (double thres)
References begin(), clear(), end(), and push_back().
operator[]() [1/2]
point3d& octomap::Pointcloud::operator[] (size_t i) inline
References points.
operator[]() [2/2]
const point3d& octomap::Pointcloud::operator[] (size_t i) const inline
References points.
push_back() [1/4]
void octomap::Pointcloud::push_back (const point3d & p) inline
References points.
push_back() [2/4]
void octomap::Pointcloud::push_back (const Pointcloud & other)
Add points from other Pointcloud.
References begin(), end(), and points.
push_back() [3/4]
void octomap::Pointcloud::push_back (float x, float y, float z) inline
References points.
Referenced by octomap::OccupancyOcTreeBase< OcTreeNodeStamped >::computeDiscreteUpdate(), crop(), octomap::MapNode< TREETYPE >::generatePointcloud(), main(), minDist(), read(), readBinary(), octomap::ScanGraph::readPlainASCII(), subSampleRandom(), and octomap::MapCollection< MAPNODE >::writePointcloud().
push_back() [4/4]
void octomap::Pointcloud::push_back (point3d * p) inline
References points.
read()
std::istream & octomap::Pointcloud::read (std::istream & s)
References push_back().
readBinary()
std::istream & octomap::Pointcloud::readBinary (std::istream & s)
References OCTOMAP_DEBUG, OCTOMAP_ERROR, points, push_back(), octomath::Vector3::readBinary(), and size().
Referenced by octomap::ScanNode::readBinary().
reserve()
void octomap::Pointcloud::reserve (size_t size) inline
References points, and size().
Referenced by octomap::OccupancyOcTreeBase< OcTreeNodeStamped >::computeDiscreteUpdate().
rotate()
void octomap::Pointcloud::rotate (double roll, double pitch, double yaw)
Rotate each point in pointcloud.
References points.
size()
size_t octomap::Pointcloud::size () const inline
References points.
Referenced by octomap::OccupancyOcTreeBase< OcTreeNodeStamped >::computeDiscreteUpdate(), octomap::OccupancyOcTreeBase< OcTreeNodeStamped >::computeUpdate(), octomap::OccupancyOcTreeBase< OcTreeNodeStamped >::insertPointCloudRays(), main(), readBinary(), octomap::ScanGraph::readPlainASCII(), reserve(), subSampleRandom(), and writeBinary().
subSampleRandom()
void octomap::Pointcloud::subSampleRandom (unsigned int num_samples, Pointcloud & sample_cloud)
References begin(), end(), push_back(), and size().
transform()
void octomap::Pointcloud::transform (pose6d transform)
Apply transform to each point.
References current_inv_transform, and points.
Referenced by octomap::ScanGraph::crop(), octomap::OccupancyOcTreeBase< OcTreeNodeStamped >::insertPointCloud(), main(), and transformAbsolute().
transformAbsolute()
void octomap::Pointcloud::transformAbsolute (pose6d transform)
Apply transform to each point, undo previous transforms.
References current_inv_transform, points, transform(), and octomath::Pose6D::transform().
Referenced by octomap::ScanGraph::crop().
writeBinary()
std::ostream & octomap::Pointcloud::writeBinary (std::ostream & s) const
References begin(), end(), OCTOMAP_DEBUG, OCTOMAP_ERROR, and size().
Referenced by octomap::ScanNode::writeBinary().
writeVrml()
void octomap::Pointcloud::writeVrml (std::string filename)
Export the Pointcloud to a VRML file.
References OCTOMAP_DEBUG_STR, and points.
Referenced by octomap::MapCollection< MAPNODE >::writePointcloud().
Field Documentation
current_inv_transform
pose6d octomap::Pointcloud::current_inv_transform protected
Referenced by transform(), and transformAbsolute().
points
point3d_collection octomap::Pointcloud::points protected
Referenced by back(), begin(), clear(), end(), getPoint(), operator[](), Pointcloud(), push_back(), readBinary(), reserve(), rotate(), size(), transform(), transformAbsolute(), and writeVrml().
The documentation for this class was generated from the following files:
include/octomap/Pointcloud.h
src/Pointcloud.cpp