octomap: octomap::MapNode< TREETYPE > Class Template Reference
octomap::MapNode< TREETYPE > Class Template Reference
Public Types
typedef TREETYPE TreeType
Public Member Functions
Pointcloud generatePointcloud ()
std::string getId ()
TREETYPE * getMap ()
pose6d getOrigin ()
MapNode ()
MapNode (const Pointcloud &cloud, pose6d origin)
MapNode (std::string filename, pose6d origin)
MapNode (TREETYPE *node_map, pose6d origin)
void setId (std::string newid)
void updateMap (const Pointcloud &cloud, point3d sensor_origin)
bool writeMap (std::string filename)
~MapNode ()
Protected Member Functions
void clear ()
bool readMap (std::string filename)
Protected Attributes
std::string id
TREETYPE * node_map
pose6d origin
Member Typedef Documentation
TreeType
template<class TREETYPE > typedef TREETYPE octomap::MapNode< TREETYPE >::TreeType
Constructor & Destructor Documentation
MapNode() [1/4]
template<class TREETYPE > octomap::MapNode< TREETYPE >::MapNode
MapNode() [2/4]
template<class TREETYPE > octomap::MapNode< TREETYPE >::MapNode (TREETYPE * node_map, pose6d origin)
MapNode() [3/4]
template<class TREETYPE > octomap::MapNode< TREETYPE >::MapNode (std::string filename, pose6d origin)
References octomap::MapNode< TREETYPE >::origin, and octomap::MapNode< TREETYPE >::readMap().
MapNode() [4/4]
template<class TREETYPE > octomap::MapNode< TREETYPE >::MapNode (const Pointcloud & cloud, pose6d origin)
~MapNode()
template<class TREETYPE > octomap::MapNode< TREETYPE >::~MapNode
Member Function Documentation
clear()
template<class TREETYPE > void octomap::MapNode< TREETYPE >::clear protected
generatePointcloud()
template<class TREETYPE > Pointcloud octomap::MapNode< TREETYPE >::generatePointcloud
References octomap::Pointcloud::push_back().
getId()
template<class TREETYPE > std::string octomap::MapNode< TREETYPE >::getId () inline
References octomap::MapNode< TREETYPE >::id.
getMap()
template<class TREETYPE > TREETYPE* octomap::MapNode< TREETYPE >::getMap () inline
References octomap::MapNode< TREETYPE >::node_map.
getOrigin()
template<class TREETYPE > pose6d octomap::MapNode< TREETYPE >::getOrigin () inline
References octomap::MapNode< TREETYPE >::origin.
readMap()
template<class TREETYPE > bool octomap::MapNode< TREETYPE >::readMap (std::string filename) protected
Referenced by octomap::MapNode< TREETYPE >::MapNode().
setId()
template<class TREETYPE > void octomap::MapNode< TREETYPE >::setId (std::string newid) inline
updateMap()
template<class TREETYPE > void octomap::MapNode< TREETYPE >::updateMap (const Pointcloud & cloud, point3d sensor_origin)
writeMap()
template<class TREETYPE > bool octomap::MapNode< TREETYPE >::writeMap (std::string filename)
Field Documentation
id
template<class TREETYPE > std::string octomap::MapNode< TREETYPE >::id protected
Referenced by octomap::MapNode< TREETYPE >::getId().
node_map
template<class TREETYPE > TREETYPE* octomap::MapNode< TREETYPE >::node_map protected
Referenced by octomap::MapNode< TREETYPE >::getMap().
origin
template<class TREETYPE > pose6d octomap::MapNode< TREETYPE >::origin protected
Referenced by octomap::MapNode< TREETYPE >::getOrigin(), and octomap::MapNode< TREETYPE >::MapNode().
The documentation for this class was generated from the following files:
include/octomap/MapNode.h
include/octomap/MapNode.hxx