octomap: octomap::AbstractOccupancyOcTree Class Reference
octomap::AbstractOccupancyOcTree Class Reference abstract
Interface class for all octree types that store occupancy.
Public Member Functions
AbstractOccupancyOcTree ()
virtual void clear ()=0
virtual AbstractOcTree * create () const =0
virtual constructor: creates a new object of same type
virtual void expand ()=0
double getClampingThresMax () const
float getClampingThresMaxLog () const
double getClampingThresMin () const
float getClampingThresMinLog () const
virtual void getMetricMax (double &x, double &y, double &z) const =0
virtual void getMetricMax (double &x, double &y, double &z)=0
virtual void getMetricMin (double &x, double &y, double &z) const =0
virtual void getMetricMin (double &x, double &y, double &z)=0
virtual void getMetricSize (double &x, double &y, double &z)=0
double getOccupancyThres () const
float getOccupancyThresLog () const
double getProbHit () const
float getProbHitLog () const
double getProbMiss () const
float getProbMissLog () const
virtual double getResolution () const =0
virtual std::string getTreeType () const =0
returns actual class name as string for identification
bool isNodeAtThreshold (const OcTreeNode &occupancyNode) const
queries whether a node is at the clamping threshold according to the tree's parameter
bool isNodeAtThreshold (const OcTreeNode *occupancyNode) const
queries whether a node is at the clamping threshold according to the tree's parameter
bool isNodeOccupied (const OcTreeNode &occupancyNode) const
queries whether a node is occupied according to the tree's parameter for "occupancy"
bool isNodeOccupied (const OcTreeNode *occupancyNode) const
queries whether a node is occupied according to the tree's parameter for "occupancy"
virtual size_t memoryUsage () const =0
virtual size_t memoryUsageNode () const =0
virtual void prune ()=0
bool readBinary (const std::string &filename)
Reads OcTree from a binary file.
bool readBinary (std::istream &s)
Reads an OcTree from an input stream.
virtual std::istream & readBinaryData (std::istream &s)=0
Reads the actual data, implemented in OccupancyOcTreeBase::readBinaryData()
virtual std::istream & readData (std::istream &s)=0
Read all nodes from the input stream (without file header), for this the tree needs to be already created.
void setClampingThresMax (double thresProb)
sets the maximum threshold for occupancy clamping (sensor model)
void setClampingThresMin (double thresProb)
sets the minimum threshold for occupancy clamping (sensor model)
void setOccupancyThres (double prob)
sets the threshold for occupancy (sensor model)
void setProbHit (double prob)
sets the probability for a "hit" (will be converted to logodds) - sensor model
void setProbMiss (double prob)
sets the probability for a "miss" (will be converted to logodds) - sensor model
virtual void setResolution (double res)=0
virtual size_t size () const =0
virtual void toMaxLikelihood ()=0
virtual OcTreeNode * updateNode (const OcTreeKey &key, bool occupied, bool lazy_eval=false)=0
Integrate occupancy measurement.
virtual OcTreeNode * updateNode (const OcTreeKey &key, float log_odds_update, bool lazy_eval=false)=0
Manipulate log_odds value of voxel directly.
virtual OcTreeNode * updateNode (const point3d &value, bool occupied, bool lazy_eval=false)=0
Integrate occupancy measurement.
virtual OcTreeNode * updateNode (const point3d &value, float log_odds_update, bool lazy_eval=false)=0
Manipulate log_odds value of voxel directly.
bool write (const std::string &filename) const
Write file header and complete tree to file (serialization)
bool write (std::ostream &s) const
Write file header and complete tree to stream (serialization)
bool writeBinary (const std::string &filename)
Writes OcTree to a binary file using writeBinary().
bool writeBinary (std::ostream &s)
Writes compressed maximum likelihood OcTree to a binary stream.
bool writeBinaryConst (const std::string &filename) const
Writes OcTree to a binary file using writeBinaryConst().
bool writeBinaryConst (std::ostream &s) const
Writes the maximum likelihood OcTree to a binary stream (const variant).
virtual std::ostream & writeBinaryData (std::ostream &s) const =0
Writes the actual data, implemented in OccupancyOcTreeBase::writeBinaryData()
virtual std::ostream & writeData (std::ostream &s) const =0
Write complete state of tree to stream (without file header) unmodified. Pruning the tree first produces smaller files (lossless compression)
virtual ~AbstractOccupancyOcTree ()
Static Public Member Functions
static AbstractOcTree * createTree (const std::string id, double res)
Creates a certain OcTree (factory pattern)
static AbstractOcTree * read (const std::string &filename)
Read the file header, create the appropriate class and deserialize.
static AbstractOcTree * read (std::istream &s)
Read the file header, create the appropriate class and deserialize. This creates a new octree which you need to delete yourself.
Protected Member Functions
bool readBinaryLegacyHeader (std::istream &s, unsigned int &size, double &res)
Try to read the old binary format for conversion, will be removed in the future.
Static Protected Member Functions
static bool readHeader (std::istream &s, std::string &id, unsigned &size, double &res)
static void registerTreeType (AbstractOcTree *tree)
Protected Attributes
float clamping_thres_max
float clamping_thres_min
float occ_prob_thres_log
float prob_hit_log
float prob_miss_log
Static Protected Attributes
static const std::string binaryFileHeader = "# Octomap OcTree binary file"
static const std::string fileHeader = "# Octomap OcTree file"
Detailed Description
Interface class for all octree types that store occupancy.
This serves as a common base class e.g. for polymorphism and contains common code for reading and writing binary trees.
Constructor & Destructor Documentation
AbstractOccupancyOcTree()
octomap::AbstractOccupancyOcTree::AbstractOccupancyOcTree ()
References setClampingThresMax(), setClampingThresMin(), setOccupancyThres(), setProbHit(), and setProbMiss().
~AbstractOccupancyOcTree()
virtual octomap::AbstractOccupancyOcTree::~AbstractOccupancyOcTree () inline virtual
Member Function Documentation
clear()
virtual void octomap::AbstractOcTree::clear () pure virtual inherited
Implemented in octomap::OcTreeBaseImpl< OcTreeNode, AbstractOccupancyOcTree >, octomap::OcTreeBaseImpl< NODE, AbstractOccupancyOcTree >, octomap::OcTreeBaseImpl< CountingOcTreeNode, AbstractOcTree >, octomap::OcTreeBaseImpl< NODE, AbstractOcTree >, octomap::OcTreeBaseImpl< OcTreeNodeStamped, AbstractOccupancyOcTree >, and octomap::OcTreeBaseImpl< ColorOcTreeNode, AbstractOccupancyOcTree >.
Referenced by readBinary(), and readBinaryLegacyHeader().
create()
virtual AbstractOcTree* octomap::AbstractOcTree::create () const pure virtual inherited
virtual constructor: creates a new object of same type
Implemented in octomap::ColorOcTree, octomap::OcTreeStamped, octomap::OcTree, and octomap::OcTreeBase< NODE >.
createTree()
AbstractOcTree * octomap::AbstractOcTree::createTree (const std::string id, double res) static inherited
Creates a certain OcTree (factory pattern)
Parameters
id unique ID of OcTree
res resolution of OcTree
Returns
pointer to newly created OcTree (empty). NULL if the ID is unknown!
References OCTOMAP_ERROR, and octomap::AbstractOcTree::setResolution().
Referenced by octomap::AbstractOcTree::read().
expand()
virtual void octomap::AbstractOcTree::expand () pure virtual inherited
Implemented in octomap::OcTreeBaseImpl< OcTreeNode, AbstractOccupancyOcTree >, octomap::OcTreeBaseImpl< NODE, AbstractOccupancyOcTree >, octomap::OcTreeBaseImpl< CountingOcTreeNode, AbstractOcTree >, octomap::OcTreeBaseImpl< NODE, AbstractOcTree >, octomap::OcTreeBaseImpl< OcTreeNodeStamped, AbstractOccupancyOcTree >, and octomap::OcTreeBaseImpl< ColorOcTreeNode, AbstractOccupancyOcTree >.
getClampingThresMax()
double octomap::AbstractOccupancyOcTree::getClampingThresMax () const inline
Returns
maximum threshold for occupancy clamping in the sensor model (probability)
References clamping_thres_max, and octomap::probability().
Referenced by main().
getClampingThresMaxLog()
float octomap::AbstractOccupancyOcTree::getClampingThresMaxLog () const inline
Returns
maximum threshold for occupancy clamping in the sensor model (logodds)
References clamping_thres_max.
getClampingThresMin()
double octomap::AbstractOccupancyOcTree::getClampingThresMin () const inline
Returns
minimum threshold for occupancy clamping in the sensor model (probability)
References clamping_thres_min, and octomap::probability().
Referenced by main().
getClampingThresMinLog()
float octomap::AbstractOccupancyOcTree::getClampingThresMinLog () const inline
Returns
minimum threshold for occupancy clamping in the sensor model (logodds)
References clamping_thres_min.
getMetricMax() [1/2]
virtual void octomap::AbstractOcTree::getMetricMax (double & x, double & y, double & z) const pure virtual inherited
Implemented in octomap::OcTreeBaseImpl< OcTreeNode, AbstractOccupancyOcTree >, octomap::OcTreeBaseImpl< NODE, AbstractOccupancyOcTree >, octomap::OcTreeBaseImpl< CountingOcTreeNode, AbstractOcTree >, octomap::OcTreeBaseImpl< NODE, AbstractOcTree >, octomap::OcTreeBaseImpl< OcTreeNodeStamped, AbstractOccupancyOcTree >, and octomap::OcTreeBaseImpl< ColorOcTreeNode, AbstractOccupancyOcTree >.
getMetricMax() [2/2]
virtual void octomap::AbstractOcTree::getMetricMax (double & x, double & y, double & z) pure virtual inherited
Implemented in octomap::OcTreeBaseImpl< OcTreeNode, AbstractOccupancyOcTree >, octomap::OcTreeBaseImpl< NODE, AbstractOccupancyOcTree >, octomap::OcTreeBaseImpl< CountingOcTreeNode, AbstractOcTree >, octomap::OcTreeBaseImpl< NODE, AbstractOcTree >, octomap::OcTreeBaseImpl< OcTreeNodeStamped, AbstractOccupancyOcTree >, and octomap::OcTreeBaseImpl< ColorOcTreeNode, AbstractOccupancyOcTree >.
getMetricMin() [1/2]
virtual void octomap::AbstractOcTree::getMetricMin (double & x, double & y, double & z) const pure virtual inherited
Implemented in octomap::OcTreeBaseImpl< OcTreeNode, AbstractOccupancyOcTree >, octomap::OcTreeBaseImpl< NODE, AbstractOccupancyOcTree >, octomap::OcTreeBaseImpl< CountingOcTreeNode, AbstractOcTree >, octomap::OcTreeBaseImpl< NODE, AbstractOcTree >, octomap::OcTreeBaseImpl< OcTreeNodeStamped, AbstractOccupancyOcTree >, and octomap::OcTreeBaseImpl< ColorOcTreeNode, AbstractOccupancyOcTree >.
getMetricMin() [2/2]
virtual void octomap::AbstractOcTree::getMetricMin (double & x, double & y, double & z) pure virtual inherited
Implemented in octomap::OcTreeBaseImpl< OcTreeNode, AbstractOccupancyOcTree >, octomap::OcTreeBaseImpl< NODE, AbstractOccupancyOcTree >, octomap::OcTreeBaseImpl< CountingOcTreeNode, AbstractOcTree >, octomap::OcTreeBaseImpl< NODE, AbstractOcTree >, octomap::OcTreeBaseImpl< OcTreeNodeStamped, AbstractOccupancyOcTree >, and octomap::OcTreeBaseImpl< ColorOcTreeNode, AbstractOccupancyOcTree >.
getMetricSize()
virtual void octomap::AbstractOcTree::getMetricSize (double & x, double & y, double & z) pure virtual inherited
Implemented in octomap::OcTreeBaseImpl< OcTreeNode, AbstractOccupancyOcTree >, octomap::OcTreeBaseImpl< NODE, AbstractOccupancyOcTree >, octomap::OcTreeBaseImpl< CountingOcTreeNode, AbstractOcTree >, octomap::OcTreeBaseImpl< NODE, AbstractOcTree >, octomap::OcTreeBaseImpl< OcTreeNodeStamped, AbstractOccupancyOcTree >, and octomap::OcTreeBaseImpl< ColorOcTreeNode, AbstractOccupancyOcTree >.
getOccupancyThres()
double octomap::AbstractOccupancyOcTree::getOccupancyThres () const inline
Returns
threshold (probability) for occupancy - sensor model
References occ_prob_thres_log, and octomap::probability().
getOccupancyThresLog()
float octomap::AbstractOccupancyOcTree::getOccupancyThresLog () const inline
Returns
threshold (logodds) for occupancy - sensor model
References occ_prob_thres_log.
getProbHit()
double octomap::AbstractOccupancyOcTree::getProbHit () const inline
Returns
probability for a "hit" in the sensor model (probability)
References prob_hit_log, and octomap::probability().
Referenced by main().
getProbHitLog()
float octomap::AbstractOccupancyOcTree::getProbHitLog () const inline
Returns
probability for a "hit" in the sensor model (logodds)
References prob_hit_log.
getProbMiss()
double octomap::AbstractOccupancyOcTree::getProbMiss () const inline
Returns
probability for a "miss" in the sensor model (probability)
References prob_miss_log, and octomap::probability().
Referenced by main().
getProbMissLog()
float octomap::AbstractOccupancyOcTree::getProbMissLog () const inline
Returns
probability for a "miss" in the sensor model (logodds)
References prob_miss_log.
getResolution()
virtual double octomap::AbstractOcTree::getResolution () const pure virtual inherited
Referenced by main(), octomap::AbstractOcTree::write(), and writeBinaryConst().
getTreeType()
virtual std::string octomap::AbstractOcTree::getTreeType () const pure virtual inherited
returns actual class name as string for identification
Implemented in octomap::ColorOcTree, octomap::OcTreeStamped, octomap::OcTree, and octomap::OcTreeBase< NODE >.
Referenced by main(), octomap::AbstractOcTree::registerTreeType(), octomap::AbstractOcTree::write(), and writeBinaryConst().
isNodeAtThreshold() [1/2]
bool octomap::AbstractOccupancyOcTree::isNodeAtThreshold (const OcTreeNode & occupancyNode) const inline
queries whether a node is at the clamping threshold according to the tree's parameter
References octomap::OcTreeNode::getLogOdds().
isNodeAtThreshold() [2/2]
bool octomap::AbstractOccupancyOcTree::isNodeAtThreshold (const OcTreeNode * occupancyNode) const inline
queries whether a node is at the clamping threshold according to the tree's parameter
References octomap::OcTreeNode::getLogOdds().
Referenced by calcThresholdedNodes().
isNodeOccupied() [1/2]
bool octomap::AbstractOccupancyOcTree::isNodeOccupied (const OcTreeNode & occupancyNode) const inline
queries whether a node is occupied according to the tree's parameter for "occupancy"
References octomap::OcTreeNode::getLogOdds().
isNodeOccupied() [2/2]
bool octomap::AbstractOccupancyOcTree::isNodeOccupied (const OcTreeNode * occupancyNode) const inline
queries whether a node is occupied according to the tree's parameter for "occupancy"
References octomap::OcTreeNode::getLogOdds().
Referenced by octomap::OcTreeStamped::degradeOutdatedNodes(), getLeafNodesRecurs(), main(), and printChanges().
memoryUsage()
virtual size_t octomap::AbstractOcTree::memoryUsage () const pure virtual inherited
memoryUsageNode()
virtual size_t octomap::AbstractOcTree::memoryUsageNode () const pure virtual inherited
prune()
virtual void octomap::AbstractOcTree::prune () pure virtual inherited
Implemented in octomap::OcTreeBaseImpl< OcTreeNode, AbstractOccupancyOcTree >, octomap::OcTreeBaseImpl< NODE, AbstractOccupancyOcTree >, octomap::OcTreeBaseImpl< CountingOcTreeNode, AbstractOcTree >, octomap::OcTreeBaseImpl< NODE, AbstractOcTree >, octomap::OcTreeBaseImpl< OcTreeNodeStamped, AbstractOccupancyOcTree >, and octomap::OcTreeBaseImpl< ColorOcTreeNode, AbstractOccupancyOcTree >.
Referenced by writeBinary().
read() [1/2]
AbstractOcTree * octomap::AbstractOcTree::read (const std::string & filename) static inherited
Read the file header, create the appropriate class and deserialize.
This creates a new octree which you need to delete yourself. If you expect or requre a specific kind of octree, use dynamic_cast afterwards:
AbstractOcTree* tree = AbstractOcTree::read("filename.ot");
OcTree* octree = dynamic_cast<OcTree*>(tree);
References OCTOMAP_ERROR_STR.
read() [2/2]
AbstractOcTree * octomap::AbstractOcTree::read (std::istream & s) static inherited
Read the file header, create the appropriate class and deserialize. This creates a new octree which you need to delete yourself.
References octomap::AbstractOcTree::createTree(), octomap::AbstractOcTree::fileHeader, OCTOMAP_DEBUG_STR, OCTOMAP_ERROR_STR, octomap::AbstractOcTree::readData(), octomap::AbstractOcTree::readHeader(), and octomap::AbstractOcTree::size().
readBinary() [1/2]
bool octomap::AbstractOccupancyOcTree::readBinary (const std::string & filename)
Reads OcTree from a binary file.
Existing nodes of the tree are deleted before the tree is read.
Returns
success of operation
References OCTOMAP_ERROR_STR, and readBinary().
readBinary() [2/2]
bool octomap::AbstractOccupancyOcTree::readBinary (std::istream & s)
Reads an OcTree from an input stream.
Existing nodes of the tree are deleted before the tree is read.
Returns
success of operation
References binaryFileHeader, octomap::AbstractOcTree::clear(), OCTOMAP_DEBUG_STR, OCTOMAP_ERROR, OCTOMAP_ERROR_STR, OCTOMAP_WARNING_STR, readBinaryData(), readBinaryLegacyHeader(), octomap::AbstractOcTree::readHeader(), octomap::AbstractOcTree::setResolution(), and octomap::AbstractOcTree::size().
Referenced by main(), octomap::OcTree::OcTree(), and readBinary().
readBinaryData()
virtual std::istream& octomap::AbstractOccupancyOcTree::readBinaryData (std::istream & s) pure virtual
Reads the actual data, implemented in OccupancyOcTreeBase::readBinaryData()
Implemented in octomap::OccupancyOcTreeBase< NODE >, octomap::OccupancyOcTreeBase< ColorOcTreeNode >, octomap::OccupancyOcTreeBase< OcTreeNode >, and octomap::OccupancyOcTreeBase< OcTreeNodeStamped >.
Referenced by readBinary().
readBinaryLegacyHeader()
bool octomap::AbstractOccupancyOcTree::readBinaryLegacyHeader (std::istream & s, unsigned int & size, double & res) protected
Try to read the old binary format for conversion, will be removed in the future.
References octomap::AbstractOcTree::clear(), OCTOMAP_ERROR, OCTOMAP_ERROR_STR, OCTOMAP_WARNING_STR, and octomap::AbstractOcTree::size().
Referenced by readBinary().
readData()
virtual std::istream& octomap::AbstractOcTree::readData (std::istream & s) pure virtual inherited
Read all nodes from the input stream (without file header), for this the tree needs to be already created.
For general file IO, you should probably use AbstractOcTree::read() instead.
Implemented in octomap::OcTreeBaseImpl< OcTreeNode, AbstractOccupancyOcTree >, octomap::OcTreeBaseImpl< NODE, AbstractOccupancyOcTree >, octomap::OcTreeBaseImpl< CountingOcTreeNode, AbstractOcTree >, octomap::OcTreeBaseImpl< NODE, AbstractOcTree >, octomap::OcTreeBaseImpl< OcTreeNodeStamped, AbstractOccupancyOcTree >, and octomap::OcTreeBaseImpl< ColorOcTreeNode, AbstractOccupancyOcTree >.
Referenced by octomap::AbstractOcTree::read().
readHeader()
bool octomap::AbstractOcTree::readHeader (std::istream & s, std::string & id, unsigned & size, double & res) static protected inherited
References OCTOMAP_ERROR_STR, OCTOMAP_WARNING, OCTOMAP_WARNING_STR, and octomap::AbstractOcTree::size().
Referenced by octomap::AbstractOcTree::read(), and readBinary().
registerTreeType()
void octomap::AbstractOcTree::registerTreeType (AbstractOcTree * tree) static protected inherited
References octomap::AbstractOcTree::getTreeType().
Referenced by octomap::OcTree::StaticMemberInitializer::StaticMemberInitializer(), octomap::CountingOcTree::StaticMemberInitializer::StaticMemberInitializer(), octomap::OcTreeStamped::StaticMemberInitializer::StaticMemberInitializer(), and octomap::ColorOcTree::StaticMemberInitializer::StaticMemberInitializer().
setClampingThresMax()
void octomap::AbstractOccupancyOcTree::setClampingThresMax (double thresProb) inline
sets the maximum threshold for occupancy clamping (sensor model)
References clamping_thres_max, and octomap::logodds().
Referenced by AbstractOccupancyOcTree(), and main().
setClampingThresMin()
void octomap::AbstractOccupancyOcTree::setClampingThresMin (double thresProb) inline
sets the minimum threshold for occupancy clamping (sensor model)
References clamping_thres_min, and octomap::logodds().
Referenced by AbstractOccupancyOcTree(), and main().
setOccupancyThres()
void octomap::AbstractOccupancyOcTree::setOccupancyThres (double prob) inline
sets the threshold for occupancy (sensor model)
References octomap::logodds(), and occ_prob_thres_log.
Referenced by AbstractOccupancyOcTree().
setProbHit()
void octomap::AbstractOccupancyOcTree::setProbHit (double prob) inline
sets the probability for a "hit" (will be converted to logodds) - sensor model
References octomap::logodds(), and prob_hit_log.
Referenced by AbstractOccupancyOcTree(), and main().
setProbMiss()
void octomap::AbstractOccupancyOcTree::setProbMiss (double prob) inline
sets the probability for a "miss" (will be converted to logodds) - sensor model
References octomap::logodds(), and prob_miss_log.
Referenced by AbstractOccupancyOcTree(), and main().
setResolution()
virtual void octomap::AbstractOcTree::setResolution (double res) pure virtual inherited
Implemented in octomap::OcTreeBaseImpl< OcTreeNode, AbstractOccupancyOcTree >, octomap::OcTreeBaseImpl< NODE, AbstractOccupancyOcTree >, octomap::OcTreeBaseImpl< CountingOcTreeNode, AbstractOcTree >, octomap::OcTreeBaseImpl< NODE, AbstractOcTree >, octomap::OcTreeBaseImpl< OcTreeNodeStamped, AbstractOccupancyOcTree >, and octomap::OcTreeBaseImpl< ColorOcTreeNode, AbstractOccupancyOcTree >.
Referenced by octomap::AbstractOcTree::createTree(), and readBinary().
size()
virtual size_t octomap::AbstractOcTree::size () const pure virtual inherited
Referenced by main(), octomap::AbstractOcTree::read(), readBinary(), readBinaryLegacyHeader(), octomap::AbstractOcTree::readHeader(), octomap::AbstractOcTree::write(), and writeBinaryConst().
toMaxLikelihood()
virtual void octomap::AbstractOccupancyOcTree::toMaxLikelihood () pure virtual
Implemented in octomap::OccupancyOcTreeBase< NODE >, octomap::OccupancyOcTreeBase< ColorOcTreeNode >, octomap::OccupancyOcTreeBase< OcTreeNode >, and octomap::OccupancyOcTreeBase< OcTreeNodeStamped >.
Referenced by writeBinary().
updateNode() [1/4]
virtual OcTreeNode* octomap::AbstractOccupancyOcTree::updateNode (const OcTreeKey & key, bool occupied, bool lazy_eval = false) pure virtual
Integrate occupancy measurement.
Parameters
key of the NODE that is to be updated
occupied true if the node was measured occupied, else false
lazy_eval whether update of inner nodes is omitted after the update (default: false). This speeds up the insertion, but you need to call updateInnerOccupancy() when done.
Returns
pointer to the updated NODE
Implemented in octomap::OccupancyOcTreeBase< NODE >, octomap::OccupancyOcTreeBase< ColorOcTreeNode >, octomap::OccupancyOcTreeBase< OcTreeNode >, and octomap::OccupancyOcTreeBase< OcTreeNodeStamped >.
updateNode() [2/4]
virtual OcTreeNode* octomap::AbstractOccupancyOcTree::updateNode (const OcTreeKey & key, float log_odds_update, bool lazy_eval = false) pure virtual
Manipulate log_odds value of voxel directly.
Parameters
key of the NODE that is to be updated
log_odds_update value to be added (+) to log_odds value of node
lazy_eval whether update of inner nodes is omitted after the update (default: false). This speeds up the insertion, but you need to call updateInnerOccupancy() when done.
Returns
pointer to the updated NODE
Implemented in octomap::OccupancyOcTreeBase< NODE >, octomap::OccupancyOcTreeBase< ColorOcTreeNode >, octomap::OccupancyOcTreeBase< OcTreeNode >, and octomap::OccupancyOcTreeBase< OcTreeNodeStamped >.
updateNode() [3/4]
virtual OcTreeNode* octomap::AbstractOccupancyOcTree::updateNode (const point3d & value, bool occupied, bool lazy_eval = false) pure virtual
Integrate occupancy measurement.
Looks up the OcTreeKey corresponding to the coordinate and then calls udpateNode() with it.
Parameters
value 3d coordinate of the NODE that is to be updated
occupied true if the node was measured occupied, else false
lazy_eval whether update of inner nodes is omitted after the update (default: false). This speeds up the insertion, but you need to call updateInnerOccupancy() when done.
Returns
pointer to the updated NODE
Implemented in octomap::OccupancyOcTreeBase< NODE >, octomap::OccupancyOcTreeBase< ColorOcTreeNode >, octomap::OccupancyOcTreeBase< OcTreeNode >, and octomap::OccupancyOcTreeBase< OcTreeNodeStamped >.
updateNode() [4/4]
virtual OcTreeNode* octomap::AbstractOccupancyOcTree::updateNode (const point3d & value, float log_odds_update, bool lazy_eval = false) pure virtual
Manipulate log_odds value of voxel directly.
Looks up the OcTreeKey corresponding to the coordinate and then calls udpateNode() with it.
Parameters
value 3d coordinate of the NODE that is to be updated
log_odds_update value to be added (+) to log_odds value of node
lazy_eval whether update of inner nodes is omitted after the update (default: false). This speeds up the insertion, but you need to call updateInnerOccupancy() when done.
Returns
pointer to the updated NODE
Implemented in octomap::OccupancyOcTreeBase< NODE >, octomap::OccupancyOcTreeBase< ColorOcTreeNode >, octomap::OccupancyOcTreeBase< OcTreeNode >, and octomap::OccupancyOcTreeBase< OcTreeNodeStamped >.
write() [1/2]
bool octomap::AbstractOcTree::write (const std::string & filename) const inherited
Write file header and complete tree to file (serialization)
References OCTOMAP_ERROR_STR.
Referenced by main().
write() [2/2]
bool octomap::AbstractOcTree::write (std::ostream & s) const inherited
Write file header and complete tree to stream (serialization)
References octomap::AbstractOcTree::fileHeader, octomap::AbstractOcTree::getResolution(), octomap::AbstractOcTree::getTreeType(), octomap::AbstractOcTree::size(), and octomap::AbstractOcTree::writeData().
writeBinary() [1/2]
bool octomap::AbstractOccupancyOcTree::writeBinary (const std::string & filename)
Writes OcTree to a binary file using writeBinary().
The OcTree is first converted to the maximum likelihood estimate and pruned.
Returns
success of operation
References OCTOMAP_ERROR_STR.
Referenced by main().
writeBinary() [2/2]
bool octomap::AbstractOccupancyOcTree::writeBinary (std::ostream & s)
Writes compressed maximum likelihood OcTree to a binary stream.
The OcTree is first converted to the maximum likelihood estimate and pruned for maximum compression.
Returns
success of operation
References octomap::AbstractOcTree::prune(), toMaxLikelihood(), and writeBinaryConst().
writeBinaryConst() [1/2]
bool octomap::AbstractOccupancyOcTree::writeBinaryConst (const std::string & filename) const
Writes OcTree to a binary file using writeBinaryConst().
The OcTree is not changed, in particular not pruned first. Files will be smaller when the tree is pruned first or by using writeBinary() instead.
Returns
success of operation
References OCTOMAP_ERROR_STR.
Referenced by writeBinary().
writeBinaryConst() [2/2]
bool octomap::AbstractOccupancyOcTree::writeBinaryConst (std::ostream & s) const
Writes the maximum likelihood OcTree to a binary stream (const variant).
Files will be smaller when the tree is pruned first or by using writeBinary() instead.
Returns
success of operation
References binaryFileHeader, octomap::AbstractOcTree::getResolution(), octomap::AbstractOcTree::getTreeType(), OCTOMAP_DEBUG, OCTOMAP_WARNING_STR, octomap::AbstractOcTree::size(), and writeBinaryData().
writeBinaryData()
virtual std::ostream& octomap::AbstractOccupancyOcTree::writeBinaryData (std::ostream & s) const pure virtual
Writes the actual data, implemented in OccupancyOcTreeBase::writeBinaryData()
Implemented in octomap::OccupancyOcTreeBase< NODE >, octomap::OccupancyOcTreeBase< ColorOcTreeNode >, octomap::OccupancyOcTreeBase< OcTreeNode >, and octomap::OccupancyOcTreeBase< OcTreeNodeStamped >.
Referenced by writeBinaryConst().
writeData()
virtual std::ostream& octomap::AbstractOcTree::writeData (std::ostream & s) const pure virtual inherited
Write complete state of tree to stream (without file header) unmodified. Pruning the tree first produces smaller files (lossless compression)
Implemented in octomap::OcTreeBaseImpl< OcTreeNode, AbstractOccupancyOcTree >, octomap::OcTreeBaseImpl< NODE, AbstractOccupancyOcTree >, octomap::OcTreeBaseImpl< CountingOcTreeNode, AbstractOcTree >, octomap::OcTreeBaseImpl< NODE, AbstractOcTree >, octomap::OcTreeBaseImpl< OcTreeNodeStamped, AbstractOccupancyOcTree >, and octomap::OcTreeBaseImpl< ColorOcTreeNode, AbstractOccupancyOcTree >.
Referenced by octomap::AbstractOcTree::write().
Field Documentation
binaryFileHeader
const std::string octomap::AbstractOccupancyOcTree::binaryFileHeader = "# Octomap OcTree binary file" static protected
Referenced by readBinary(), and writeBinaryConst().
clamping_thres_max
float octomap::AbstractOccupancyOcTree::clamping_thres_max protected
Referenced by getClampingThresMax(), getClampingThresMaxLog(), octomap::OccupancyOcTreeBase< OcTreeNodeStamped >::OccupancyOcTreeBase(), and setClampingThresMax().
clamping_thres_min
float octomap::AbstractOccupancyOcTree::clamping_thres_min protected
Referenced by getClampingThresMin(), getClampingThresMinLog(), octomap::OccupancyOcTreeBase< OcTreeNodeStamped >::OccupancyOcTreeBase(), and setClampingThresMin().
fileHeader
const std::string octomap::AbstractOcTree::fileHeader = "# Octomap OcTree file" static protected inherited
Referenced by octomap::AbstractOcTree::read(), and octomap::AbstractOcTree::write().
occ_prob_thres_log
float octomap::AbstractOccupancyOcTree::occ_prob_thres_log protected
Referenced by getOccupancyThres(), getOccupancyThresLog(), octomap::OccupancyOcTreeBase< OcTreeNodeStamped >::OccupancyOcTreeBase(), and setOccupancyThres().
prob_hit_log
float octomap::AbstractOccupancyOcTree::prob_hit_log protected
Referenced by getProbHit(), getProbHitLog(), octomap::OccupancyOcTreeBase< OcTreeNodeStamped >::OccupancyOcTreeBase(), and setProbHit().
prob_miss_log
float octomap::AbstractOccupancyOcTree::prob_miss_log protected
Referenced by getProbMiss(), getProbMissLog(), octomap::OcTreeStamped::integrateMissNoTime(), octomap::OccupancyOcTreeBase< OcTreeNodeStamped >::OccupancyOcTreeBase(), and setProbMiss().
The documentation for this class was generated from the following files:
include/octomap/AbstractOccupancyOcTree.h
src/AbstractOccupancyOcTree.cpp