octomap: octomap::ScanNode Class Reference
octomap::ScanNode Class Reference
A 3D scan as Pointcloud, performed from a Pose6D.
Public Member Functions
bool operator== (const ScanNode &other)
std::istream & readBinary (std::istream &s)
std::istream & readPoseASCII (std::istream &s)
ScanNode ()
ScanNode (Pointcloud *_scan, pose6d _pose, unsigned int _id)
std::ostream & writeBinary (std::ostream &s) const
std::ostream & writePoseASCII (std::ostream &s) const
~ScanNode ()
Data Fields
unsigned int id
pose6d pose
6D pose from which the scan was performed
Pointcloud * scan
Detailed Description
A 3D scan as Pointcloud, performed from a Pose6D.
Constructor & Destructor Documentation
ScanNode() [1/2]
octomap::ScanNode::ScanNode (Pointcloud * _scan, pose6d _pose, unsigned int _id) inline
ScanNode() [2/2]
octomap::ScanNode::ScanNode () inline
~ScanNode()
octomap::ScanNode::~ScanNode ()
References scan.
Member Function Documentation
operator==()
bool octomap::ScanNode::operator== (const ScanNode & other) inline
References id.
readBinary()
std::istream & octomap::ScanNode::readBinary (std::istream & s)
References pose, octomap::Pointcloud::readBinary(), octomath::Pose6D::readBinary(), and scan.
Referenced by octomap::ScanGraph::readBinary().
readPoseASCII()
std::istream & octomap::ScanNode::readPoseASCII (std::istream & s)
References OCTOMAP_ERROR, pose, octomath::Vector3::read(), octomath::Pose6D::rot(), and octomath::Pose6D::trans().
writeBinary()
std::ostream & octomap::ScanNode::writeBinary (std::ostream & s) const
References id, pose, scan, octomap::Pointcloud::writeBinary(), and octomath::Pose6D::writeBinary().
writePoseASCII()
std::ostream & octomap::ScanNode::writePoseASCII (std::ostream & s) const
References id, pose, octomath::Pose6D::rot(), octomath::Quaternion::toEuler(), octomath::Pose6D::trans(), and octomath::Vector3::write().
Field Documentation
id
unsigned int octomap::ScanNode::id
Referenced by octomap::ScanGraph::getNeighborIDs(), main(), operator==(), octomap::ScanEdge::writeASCII(), writeBinary(), octomap::ScanEdge::writeBinary(), and writePoseASCII().
pose
pose6d octomap::ScanNode::pose
6D pose from which the scan was performed
Referenced by octomap::ScanGraph::addEdge(), octomap::ScanGraph::connectPrevious(), octomap::OccupancyOcTreeBase< OcTreeNodeStamped >::insertPointCloud(), main(), readBinary(), octomap::ScanGraph::readNodePosesASCII(), octomap::ScanGraph::readPlainASCII(), readPoseASCII(), writeBinary(), and writePoseASCII().
scan
Pointcloud* octomap::ScanNode::scan
Referenced by octomap::OccupancyOcTreeBase< OcTreeNodeStamped >::insertPointCloud(), main(), readBinary(), octomap::ScanGraph::readPlainASCII(), writeBinary(), and ~ScanNode().
The documentation for this class was generated from the following files:
include/octomap/ScanGraph.h
src/ScanGraph.cpp