octomap: octomap::CountingOcTree Class Reference
octomap::CountingOcTree Class Reference abstract
An AbstractOcTree which stores an internal counter per node / volume.
Data Structures
class StaticMemberInitializer
Static member object which ensures that this OcTree's prototype ends up in the classIDMapping only once.
Public Types
typedef leaf_iterator iterator
typedef CountingOcTreeNode NodeType
Make the templated NODE type available from the outside.
Public Member Functions
OcTreeKey adjustKeyAtDepth (const OcTreeKey &key, unsigned int depth) const
Adjusts a 3D key from the lowest level to correspond to a higher depth (by shifting the key values)
key_type adjustKeyAtDepth (key_type key, unsigned int depth) const
Adjusts a single key value from the lowest level to correspond to a higher depth (by shifting the key value)
iterator begin (unsigned char maxDepth=0) const
leaf_iterator begin_leafs (unsigned char maxDepth=0) const
leaf_bbx_iterator begin_leafs_bbx (const OcTreeKey &min, const OcTreeKey &max, unsigned char maxDepth=0) const
leaf_bbx_iterator begin_leafs_bbx (const point3d &min, const point3d &max, unsigned char maxDepth=0) const
tree_iterator begin_tree (unsigned char maxDepth=0) const
size_t calcNumNodes () const
Traverses the tree to calculate the total number of nodes.
void clear ()
Deletes the complete tree structure.
void clearKeyRays ()
Clear KeyRay vector to minimize unneeded memory.
bool computeRay (const point3d &origin, const point3d &end, std::vector< point3d > &ray)
Traces a ray from origin to end (excluding), returning the coordinates of all nodes traversed by the beam.
bool computeRayKeys (const point3d &origin, const point3d &end, KeyRay &ray) const
Traces a ray from origin to end (excluding), returning an OcTreeKey of all nodes traversed by the beam.
OcTreeKey coordToKey (const point3d &coord) const
Converts from a 3D coordinate into a 3D addressing key.
OcTreeKey coordToKey (const point3d &coord, unsigned depth) const
Converts from a 3D coordinate into a 3D addressing key at a given depth.
key_type coordToKey (double coordinate) const
Converts from a single coordinate into a discrete key.
key_type coordToKey (double coordinate, unsigned depth) const
Converts from a single coordinate into a discrete key at a given depth.
OcTreeKey coordToKey (double x, double y, double z) const
Converts from a 3D coordinate into a 3D addressing key.
OcTreeKey coordToKey (double x, double y, double z, unsigned depth) const
Converts from a 3D coordinate into a 3D addressing key at a given depth.
bool coordToKeyChecked (const point3d &coord, OcTreeKey &key) const
Converts a 3D coordinate into a 3D OcTreeKey, with boundary checking.
bool coordToKeyChecked (const point3d &coord, unsigned depth, OcTreeKey &key) const
Converts a 3D coordinate into a 3D OcTreeKey at a certain depth, with boundary checking.
bool coordToKeyChecked (double coordinate, key_type &key) const
Converts a single coordinate into a discrete addressing key, with boundary checking.
bool coordToKeyChecked (double coordinate, unsigned depth, key_type &key) const
Converts a single coordinate into a discrete addressing key, with boundary checking.
bool coordToKeyChecked (double x, double y, double z, OcTreeKey &key) const
Converts a 3D coordinate into a 3D OcTreeKey, with boundary checking.
bool coordToKeyChecked (double x, double y, double z, unsigned depth, OcTreeKey &key) const
Converts a 3D coordinate into a 3D OcTreeKey at a certain depth, with boundary checking.
CountingOcTree (double resolution)
Default constructor, sets resolution of leafs.
OcTreeBase< CountingOcTreeNode > * create () const
virtual constructor: creates a new object of same type (Covariant return type requires an up-to-date compiler)
virtual AbstractOcTree * create () const =0
virtual constructor: creates a new object of same type
CountingOcTreeNode * createNodeChild (CountingOcTreeNode *node, unsigned int childIdx)
Creates (allocates) the i-th child of the node.
bool deleteNode (const OcTreeKey &key, unsigned int depth=0)
Delete a node (if exists) given an addressing key.
bool deleteNode (const point3d &value, unsigned int depth=0)
Delete a node (if exists) given a 3d point.
bool deleteNode (double x, double y, double z, unsigned int depth=0)
Delete a node (if exists) given a 3d point.
void deleteNodeChild (CountingOcTreeNode *node, unsigned int childIdx)
Deletes the i-th child of the node.
const iterator end () const
const leaf_iterator end_leafs () const
const leaf_bbx_iterator end_leafs_bbx () const
const tree_iterator end_tree () const
virtual void expand ()
Expands all pruned nodes (reverse of prune())
virtual void expandNode (CountingOcTreeNode *node)
Expands a node (reverse of pruning): All children are created and their occupancy probability is set to the node's value.
void getCentersMinHits (point3d_list &node_centers, unsigned int min_hits) const
virtual void getMetricMax (double &x, double &y, double &z)
maximum value of the bounding box of all known space in x, y, z
void getMetricMax (double &x, double &y, double &z) const
maximum value of the bounding box of all known space in x, y, z
virtual void getMetricMin (double &x, double &y, double &z)
minimum value of the bounding box of all known space in x, y, z
void getMetricMin (double &x, double &y, double &z) const
minimum value of the bounding box of all known space in x, y, z
virtual void getMetricSize (double &x, double &y, double &z)
Size of OcTree (all known space) in meters for x, y and z dimension.
virtual void getMetricSize (double &x, double &y, double &z) const
Size of OcTree (all known space) in meters for x, y and z dimension.
const CountingOcTreeNode * getNodeChild (const CountingOcTreeNode *node, unsigned int childIdx) const
CountingOcTreeNode * getNodeChild (CountingOcTreeNode *node, unsigned int childIdx) const
double getNodeSize (unsigned depth) const
size_t getNumLeafNodes () const
Traverses the tree to calculate the total number of leaf nodes.
double getResolution () const
virtual double getResolution () const =0
CountingOcTreeNode * getRoot () const
unsigned int getTreeDepth () const
std::string getTreeType () const
returns actual class name as string for identification
virtual std::string getTreeType () const =0
returns actual class name as string for identification
void getUnknownLeafCenters (point3d_list &node_centers, point3d pmin, point3d pmax, unsigned int depth=0) const
return centers of leafs that do NOT exist (but could) in a given bounding box
virtual bool isNodeCollapsible (const CountingOcTreeNode *node) const
A node is collapsible if all children exist, don't have children of their own and have the same occupancy value.
point3d keyToCoord (const OcTreeKey &key) const
converts from an addressing key at the lowest tree level into a coordinate corresponding to the key's center
point3d keyToCoord (const OcTreeKey &key, unsigned depth) const
converts from an addressing key at a given depth into a coordinate corresponding to the key's center
double keyToCoord (key_type key) const
converts from a discrete key at the lowest tree level into a coordinate corresponding to the key's center
double keyToCoord (key_type key, unsigned depth) const
converts from a discrete key at a given depth into a coordinate corresponding to the key's center
unsigned long long memoryFullGrid () const
virtual size_t memoryUsage () const
virtual size_t memoryUsage () const =0
virtual size_t memoryUsageNode () const
virtual size_t memoryUsageNode () const =0
bool nodeChildExists (const CountingOcTreeNode *node, unsigned int childIdx) const
Safe test if node has a child at index childIdx.
bool nodeHasChildren (const CountingOcTreeNode *node) const
Safe test if node has any children.
bool operator== (const OcTreeBaseImpl< CountingOcTreeNode, AbstractOcTree > &rhs) const
Comparison between two octrees, all meta data, all nodes, and the structure must be identical.
virtual void prune ()
Lossless compression of the octree: A node will replace all of its eight children if they have identical values.
virtual bool pruneNode (CountingOcTreeNode *node)
Prunes a node when it is collapsible.
std::istream & readData (std::istream &s)
Read all nodes from the input stream (without file header), for this the tree needs to be already created.
CountingOcTreeNode * search (const OcTreeKey &key, unsigned int depth=0) const
Search a node at specified depth given an addressing key (depth=0: search full tree depth) You need to check if the returned node is NULL, since it can be in unknown space.
CountingOcTreeNode * search (const point3d &value, unsigned int depth=0) const
Search node at specified depth given a 3d point (depth=0: search full tree depth) You need to check if the returned node is NULL, since it can be in unknown space.
CountingOcTreeNode * search (double x, double y, double z, unsigned int depth=0) const
Search node at specified depth given a 3d point (depth=0: search full tree depth).
void setResolution (double r)
Change the resolution of the octree, scaling all voxels. This will not preserve the (metric) scale!
virtual size_t size () const
virtual size_t size () const =0
void swapContent (OcTreeBaseImpl< CountingOcTreeNode, AbstractOcTree > &rhs)
Swap contents of two octrees, i.e., only the underlying pointer / tree structure.
CountingOcTreeNode * updateNode (const OcTreeKey &k)
virtual CountingOcTreeNode * updateNode (const point3d &value)
double volume ()
bool write (const std::string &filename) const
Write file header and complete tree to file (serialization)
bool write (std::ostream &s) const
Write file header and complete tree to stream (serialization)
std::ostream & writeData (std::ostream &s) const
Write complete state of tree to stream (without file header) unmodified. Pruning the tree first produces smaller files (lossless compression)
Static Public Member Functions
static AbstractOcTree * createTree (const std::string id, double res)
Creates a certain OcTree (factory pattern)
static AbstractOcTree * read (const std::string &filename)
Read the file header, create the appropriate class and deserialize.
static AbstractOcTree * read (std::istream &s)
Read the file header, create the appropriate class and deserialize. This creates a new octree which you need to delete yourself.
Protected Member Functions
void allocNodeChildren (CountingOcTreeNode *node)
void calcMinMax ()
recalculates min and max in x, y, z. Does nothing when tree size didn't change.
void calcNumNodesRecurs (CountingOcTreeNode *node, size_t &num_nodes) const
void deleteNodeRecurs (CountingOcTreeNode *node)
Recursively delete a node and all children. Deallocates memory but does NOT set the node ptr to NULL nor updates tree size.
bool deleteNodeRecurs (CountingOcTreeNode *node, unsigned int depth, unsigned int max_depth, const OcTreeKey &key)
recursive call of deleteNode()
void expandRecurs (CountingOcTreeNode *node, unsigned int depth, unsigned int max_depth)
recursive call of expand()
void getCentersMinHitsRecurs (point3d_list &node_centers, unsigned int &min_hits, unsigned int max_depth, CountingOcTreeNode *node, unsigned int depth, const OcTreeKey &parent_key) const
size_t getNumLeafNodesRecurs (const CountingOcTreeNode *parent) const
void init ()
initialize non-trivial members, helper for constructors
void pruneRecurs (CountingOcTreeNode *node, unsigned int depth, unsigned int max_depth, unsigned int &num_pruned)
recursive call of prune()
std::istream & readNodesRecurs (CountingOcTreeNode *, std::istream &s)
recursive call of readData()
std::ostream & writeNodesRecurs (const CountingOcTreeNode *, std::ostream &s) const
recursive call of writeData()
Static Protected Member Functions
static bool readHeader (std::istream &s, std::string &id, unsigned &size, double &res)
static void registerTreeType (AbstractOcTree *tree)
Protected Attributes
std::vector< KeyRay > keyrays
data structure for ray casting, array for multithreading
const leaf_bbx_iterator leaf_iterator_bbx_end
const leaf_iterator leaf_iterator_end
double max_value [3]
max in x, y, z
double min_value [3]
min in x, y, z contains the size of a voxel at level i (0: root node). tree_depth+1 levels (incl. 0)
double resolution
in meters
double resolution_factor
= 1. / resolution
CountingOcTreeNode * root
Pointer to the root NODE, NULL for empty tree.
bool size_changed
std::vector< double > sizeLookupTable
point3d tree_center
const unsigned int tree_depth
Maximum tree depth is fixed to 16 currently.
const tree_iterator tree_iterator_end
const unsigned int tree_max_val
size_t tree_size
number of nodes in tree flag to denote whether the octree extent changed (for lazy min/max eval)
Static Protected Attributes
static StaticMemberInitializer countingOcTreeMemberInit
static member to ensure static initialization (only once)
static const std::string fileHeader = "# Octomap OcTree file"
Detailed Description
An AbstractOcTree which stores an internal counter per node / volume.
Count is recursive, parent nodes have the summed count of their children.
Note
Was only used internally, not used anymore
Member Typedef Documentation
iterator
typedef leaf_iterator octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::iterator inherited
NodeType
typedef CountingOcTreeNode octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::NodeType inherited
Make the templated NODE type available from the outside.
Constructor & Destructor Documentation
CountingOcTree()
octomap::CountingOcTree::CountingOcTree (double resolution)
Default constructor, sets resolution of leafs.
implementation of CountingOcTree -----------------------------------—
References countingOcTreeMemberInit, and octomap::CountingOcTree::StaticMemberInitializer::ensureLinking().
Referenced by octomap::CountingOcTree::StaticMemberInitializer::StaticMemberInitializer().
Member Function Documentation
adjustKeyAtDepth() [1/2]
OcTreeKey octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::adjustKeyAtDepth (const OcTreeKey & key, unsigned int depth) const inline inherited
Adjusts a 3D key from the lowest level to correspond to a higher depth (by shifting the key values)
Parameters
key Input key, at the lowest tree level
depth Target depth level for the new key
Returns
Key for the new depth level
adjustKeyAtDepth() [2/2]
key_type octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::adjustKeyAtDepth (key_type key, unsigned int depth) const inherited
Adjusts a single key value from the lowest level to correspond to a higher depth (by shifting the key value)
Parameters
key Input key, at the lowest tree level
depth Target depth level for the new key
Returns
Key for the new depth level
allocNodeChildren()
void octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::allocNodeChildren (CountingOcTreeNode * node) protected inherited
begin()
iterator octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::begin (unsigned char maxDepth = 0) const inline inherited
Returns
beginning of the tree as leaf iterator
begin_leafs()
leaf_iterator octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::begin_leafs (unsigned char maxDepth = 0) const inline inherited
Returns
beginning of the tree as leaf iterator
begin_leafs_bbx() [1/2]
leaf_bbx_iterator octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::begin_leafs_bbx (const OcTreeKey & min, const OcTreeKey & max, unsigned char maxDepth = 0) const inline inherited
Returns
beginning of the tree as leaf iterator in a bounding box
begin_leafs_bbx() [2/2]
leaf_bbx_iterator octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::begin_leafs_bbx (const point3d & min, const point3d & max, unsigned char maxDepth = 0) const inline inherited
Returns
beginning of the tree as leaf iterator in a bounding box
begin_tree()
tree_iterator octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::begin_tree (unsigned char maxDepth = 0) const inline inherited
Returns
beginning of the tree as iterator to all nodes (incl. inner)
calcMinMax()
void octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::calcMinMax protected inherited
recalculates min and max in x, y, z. Does nothing when tree size didn't change.
calcNumNodes()
size_t octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::calcNumNodes inherited
Traverses the tree to calculate the total number of nodes.
calcNumNodesRecurs()
void octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::calcNumNodesRecurs (CountingOcTreeNode * node, size_t & num_nodes) const protected inherited
clear()
void octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::clear virtual inherited
Deletes the complete tree structure.
Implements octomap::AbstractOcTree.
clearKeyRays()
void octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::clearKeyRays inline inherited
Clear KeyRay vector to minimize unneeded memory.
This is only useful for the StaticMemberInitializer classes, don't call it for an octree that is actually used.
computeRay()
bool octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::computeRay (const point3d & origin, const point3d & end, std::vector< point3d > & ray) inherited
Traces a ray from origin to end (excluding), returning the coordinates of all nodes traversed by the beam.
You still need to check if a node at that coordinate exists (e.g. with search()).
Note
: use the faster computeRayKeys method if possible.
Parameters
origin start coordinate of ray
end end coordinate of ray
ray KeyRay structure that holds the keys of all nodes traversed by the ray, excluding "end"
Returns
Success of operation. Returning false usually means that one of the coordinates is out of the OcTree's range
computeRayKeys()
bool octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::computeRayKeys (const point3d & origin, const point3d & end, KeyRay & ray) const inherited
Traces a ray from origin to end (excluding), returning an OcTreeKey of all nodes traversed by the beam.
You still need to check if a node at that coordinate exists (e.g. with search()).
Parameters
origin start coordinate of ray
end end coordinate of ray
ray KeyRay structure that holds the keys of all nodes traversed by the ray, excluding "end"
Returns
Success of operation. Returning false usually means that one of the coordinates is out of the OcTree's range
coordToKey() [1/6]
OcTreeKey octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::coordToKey (const point3d & coord) const inline inherited
Converts from a 3D coordinate into a 3D addressing key.
coordToKey() [2/6]
OcTreeKey octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::coordToKey (const point3d & coord, unsigned depth) const inline inherited
Converts from a 3D coordinate into a 3D addressing key at a given depth.
coordToKey() [3/6]
key_type octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::coordToKey (double coordinate) const inline inherited
Converts from a single coordinate into a discrete key.
coordToKey() [4/6]
key_type octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::coordToKey (double coordinate, unsigned depth) const inline inherited
Converts from a single coordinate into a discrete key at a given depth.
coordToKey() [5/6]
OcTreeKey octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::coordToKey (double x, double y, double z) const inline inherited
Converts from a 3D coordinate into a 3D addressing key.
coordToKey() [6/6]
OcTreeKey octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::coordToKey (double x, double y, double z, unsigned depth) const inline inherited
Converts from a 3D coordinate into a 3D addressing key at a given depth.
coordToKeyChecked() [1/6]
bool octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::coordToKeyChecked (const point3d & coord, OcTreeKey & key) const inherited
Converts a 3D coordinate into a 3D OcTreeKey, with boundary checking.
Parameters
coord 3d coordinate of a point
key values that will be computed, an array of fixed size 3.
Returns
true if point is within the octree (valid), false otherwise
coordToKeyChecked() [2/6]
bool octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::coordToKeyChecked (const point3d & coord, unsigned depth, OcTreeKey & key) const inherited
Converts a 3D coordinate into a 3D OcTreeKey at a certain depth, with boundary checking.
Parameters
coord 3d coordinate of a point
depth level of the key from the top
key values that will be computed, an array of fixed size 3.
Returns
true if point is within the octree (valid), false otherwise
coordToKeyChecked() [3/6]
bool octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::coordToKeyChecked (double coordinate, key_type & key) const inherited
Converts a single coordinate into a discrete addressing key, with boundary checking.
Parameters
coordinate 3d coordinate of a point
key discrete 16 bit adressing key, result
Returns
true if coordinate is within the octree bounds (valid), false otherwise
coordToKeyChecked() [4/6]
bool octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::coordToKeyChecked (double coordinate, unsigned depth, key_type & key) const inherited
Converts a single coordinate into a discrete addressing key, with boundary checking.
Parameters
coordinate 3d coordinate of a point
depth level of the key from the top
key discrete 16 bit adressing key, result
Returns
true if coordinate is within the octree bounds (valid), false otherwise
coordToKeyChecked() [5/6]
bool octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::coordToKeyChecked (double x, double y, double z, OcTreeKey & key) const inherited
Converts a 3D coordinate into a 3D OcTreeKey, with boundary checking.
Parameters
x
y
z
key values that will be computed, an array of fixed size 3.
Returns
true if point is within the octree (valid), false otherwise
coordToKeyChecked() [6/6]
bool octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::coordToKeyChecked (double x, double y, double z, unsigned depth, OcTreeKey & key) const inherited
Converts a 3D coordinate into a 3D OcTreeKey at a certain depth, with boundary checking.
Parameters
x
y
z
depth level of the key from the top
key values that will be computed, an array of fixed size 3.
Returns
true if point is within the octree (valid), false otherwise
create() [1/2]
OcTreeBase<CountingOcTreeNode >* octomap::OcTreeBase< CountingOcTreeNode >::create inline inherited
virtual constructor: creates a new object of same type (Covariant return type requires an up-to-date compiler)
create() [2/2]
virtual AbstractOcTree* octomap::AbstractOcTree::create () const pure virtual inherited
virtual constructor: creates a new object of same type
Implemented in octomap::ColorOcTree, octomap::OcTreeStamped, octomap::OcTree, and octomap::OcTreeBase< NODE >.
createNodeChild()
CountingOcTreeNode * octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::createNodeChild (CountingOcTreeNode * node, unsigned int childIdx) inherited
Creates (allocates) the i-th child of the node.
Returns
ptr to newly create NODE
createTree()
AbstractOcTree * octomap::AbstractOcTree::createTree (const std::string id, double res) static inherited
Creates a certain OcTree (factory pattern)
Parameters
id unique ID of OcTree
res resolution of OcTree
Returns
pointer to newly created OcTree (empty). NULL if the ID is unknown!
References OCTOMAP_ERROR, and octomap::AbstractOcTree::setResolution().
Referenced by octomap::AbstractOcTree::read().
deleteNode() [1/3]
bool octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::deleteNode (const OcTreeKey & key, unsigned int depth = 0) inherited
Delete a node (if exists) given an addressing key.
Will always delete at the lowest level unless depth !=0, and expand pruned inner nodes as needed. Pruned nodes at level "depth" will directly be deleted as a whole.
deleteNode() [2/3]
bool octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::deleteNode (const point3d & value, unsigned int depth = 0) inherited
Delete a node (if exists) given a 3d point.
Will always delete at the lowest level unless depth !=0, and expand pruned inner nodes as needed. Pruned nodes at level "depth" will directly be deleted as a whole.
deleteNode() [3/3]
bool octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::deleteNode (double x, double y, double z, unsigned int depth = 0) inherited
Delete a node (if exists) given a 3d point.
Will always delete at the lowest level unless depth !=0, and expand pruned inner nodes as needed. Pruned nodes at level "depth" will directly be deleted as a whole.
deleteNodeChild()
void octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::deleteNodeChild (CountingOcTreeNode * node, unsigned int childIdx) inherited
Deletes the i-th child of the node.
deleteNodeRecurs() [1/2]
void octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::deleteNodeRecurs (CountingOcTreeNode * node) protected inherited
Recursively delete a node and all children. Deallocates memory but does NOT set the node ptr to NULL nor updates tree size.
deleteNodeRecurs() [2/2]
bool octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::deleteNodeRecurs (CountingOcTreeNode * node, unsigned int depth, unsigned int max_depth, const OcTreeKey & key) protected inherited
recursive call of deleteNode()
end()
const iterator octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::end inline inherited
Returns
end of the tree as leaf iterator
end_leafs()
const leaf_iterator octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::end_leafs inline inherited
Returns
end of the tree as leaf iterator
end_leafs_bbx()
const leaf_bbx_iterator octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::end_leafs_bbx inline inherited
Returns
end of the tree as leaf iterator in a bounding box
end_tree()
const tree_iterator octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::end_tree inline inherited
Returns
end of the tree as iterator to all nodes (incl. inner)
expand()
void octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::expand virtual inherited
Expands all pruned nodes (reverse of prune())
Note
This is an expensive operation, especially when the tree is nearly empty!
Implements octomap::AbstractOcTree.
expandNode()
void octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::expandNode (CountingOcTreeNode * node) virtual inherited
Expands a node (reverse of pruning): All children are created and their occupancy probability is set to the node's value.
You need to verify that this is indeed a pruned node (i.e. not a leaf at the lowest level)
expandRecurs()
void octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::expandRecurs (CountingOcTreeNode * node, unsigned int depth, unsigned int max_depth) protected inherited
recursive call of expand()
getCentersMinHits()
void octomap::CountingOcTree::getCentersMinHits (point3d_list & node_centers, unsigned int min_hits) const
References getCentersMinHitsRecurs(), octomap::OcTreeBaseImpl< CountingOcTreeNode, AbstractOcTree >::root, octomap::OcTreeBaseImpl< CountingOcTreeNode, AbstractOcTree >::tree_depth, and octomap::OcTreeBaseImpl< CountingOcTreeNode, AbstractOcTree >::tree_max_val.
getCentersMinHitsRecurs()
void octomap::CountingOcTree::getCentersMinHitsRecurs (point3d_list & node_centers, unsigned int & min_hits, unsigned int max_depth, CountingOcTreeNode * node, unsigned int depth, const OcTreeKey & parent_key) const protected
References octomap::computeChildKey(), octomap::CountingOcTreeNode::getCount(), octomap::OcTreeBaseImpl< CountingOcTreeNode, AbstractOcTree >::getNodeChild(), octomap::OcTreeBaseImpl< CountingOcTreeNode, AbstractOcTree >::keyToCoord(), octomap::OcTreeBaseImpl< CountingOcTreeNode, AbstractOcTree >::nodeChildExists(), octomap::OcTreeBaseImpl< CountingOcTreeNode, AbstractOcTree >::nodeHasChildren(), and octomap::OcTreeBaseImpl< CountingOcTreeNode, AbstractOcTree >::tree_max_val.
Referenced by getCentersMinHits().
getMetricMax() [1/2]
void octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::getMetricMax (double & x, double & y, double & z) virtual inherited
maximum value of the bounding box of all known space in x, y, z
Implements octomap::AbstractOcTree.
getMetricMax() [2/2]
void octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::getMetricMax (double & x, double & y, double & z) const virtual inherited
maximum value of the bounding box of all known space in x, y, z
Implements octomap::AbstractOcTree.
getMetricMin() [1/2]
void octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::getMetricMin (double & x, double & y, double & z) virtual inherited
minimum value of the bounding box of all known space in x, y, z
Implements octomap::AbstractOcTree.
getMetricMin() [2/2]
void octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::getMetricMin (double & x, double & y, double & z) const virtual inherited
minimum value of the bounding box of all known space in x, y, z
Implements octomap::AbstractOcTree.
getMetricSize() [1/2]
void octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::getMetricSize (double & x, double & y, double & z) virtual inherited
Size of OcTree (all known space) in meters for x, y and z dimension.
Implements octomap::AbstractOcTree.
getMetricSize() [2/2]
void octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::getMetricSize (double & x, double & y, double & z) const virtual inherited
Size of OcTree (all known space) in meters for x, y and z dimension.
getNodeChild() [1/2]
const CountingOcTreeNode * octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::getNodeChild (const CountingOcTreeNode * node, unsigned int childIdx) const inherited
Returns
const ptr to child number childIdx of node
getNodeChild() [2/2]
CountingOcTreeNode * octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::getNodeChild (CountingOcTreeNode * node, unsigned int childIdx) const inherited
Returns
ptr to child number childIdx of node
getNodeSize()
double octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::getNodeSize (unsigned depth) const inline inherited
getNumLeafNodes()
size_t octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::getNumLeafNodes inherited
Traverses the tree to calculate the total number of leaf nodes.
getNumLeafNodesRecurs()
size_t octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::getNumLeafNodesRecurs (const CountingOcTreeNode * parent) const protected inherited
getResolution() [1/2]
double octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::getResolution inline inherited
getResolution() [2/2]
virtual double octomap::AbstractOcTree::getResolution () const pure virtual inherited
Referenced by main(), octomap::AbstractOcTree::write(), and octomap::AbstractOccupancyOcTree::writeBinaryConst().
getRoot()
CountingOcTreeNode * octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::getRoot inline inherited
Returns
Pointer to the root node of the tree. This pointer should not be modified or deleted externally, the OcTree manages its memory itself. In an empty tree, root is NULL.
getTreeDepth()
unsigned int octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::getTreeDepth inline inherited
getTreeType() [1/2]
std::string octomap::OcTreeBase< CountingOcTreeNode >::getTreeType inline inherited
returns actual class name as string for identification
getTreeType() [2/2]
virtual std::string octomap::AbstractOcTree::getTreeType () const pure virtual inherited
returns actual class name as string for identification
Implemented in octomap::ColorOcTree, octomap::OcTreeStamped, octomap::OcTree, and octomap::OcTreeBase< NODE >.
Referenced by main(), octomap::AbstractOcTree::registerTreeType(), octomap::AbstractOcTree::write(), and octomap::AbstractOccupancyOcTree::writeBinaryConst().
getUnknownLeafCenters()
void octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::getUnknownLeafCenters (point3d_list & node_centers, point3d pmin, point3d pmax, unsigned int depth = 0) const inherited
return centers of leafs that do NOT exist (but could) in a given bounding box
init()
void octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::init protected inherited
initialize non-trivial members, helper for constructors
isNodeCollapsible()
bool octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::isNodeCollapsible (const CountingOcTreeNode * node) const virtual inherited
A node is collapsible if all children exist, don't have children of their own and have the same occupancy value.
keyToCoord() [1/4]
point3d octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::keyToCoord (const OcTreeKey & key) const inline inherited
converts from an addressing key at the lowest tree level into a coordinate corresponding to the key's center
keyToCoord() [2/4]
point3d octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::keyToCoord (const OcTreeKey & key, unsigned depth) const inline inherited
converts from an addressing key at a given depth into a coordinate corresponding to the key's center
keyToCoord() [3/4]
double octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::keyToCoord (key_type key) const inline inherited
converts from a discrete key at the lowest tree level into a coordinate corresponding to the key's center
keyToCoord() [4/4]
double octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::keyToCoord (key_type key, unsigned depth) const inherited
converts from a discrete key at a given depth into a coordinate corresponding to the key's center
memoryFullGrid()
unsigned long long octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::memoryFullGrid inherited
Returns
Memory usage of a full grid of the same size as the OcTree in bytes (for comparison)
Note
this can be larger than the adressable memory - size_t may not be enough to hold it!
memoryUsage() [1/2]
size_t octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::memoryUsage virtual inherited
Returns
Memory usage of the complete octree in bytes (may vary between architectures)
memoryUsage() [2/2]
virtual size_t octomap::AbstractOcTree::memoryUsage () const pure virtual inherited
memoryUsageNode() [1/2]
virtual size_t octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::memoryUsageNode inline virtual inherited
Returns
Memory usage of a single octree node
memoryUsageNode() [2/2]
virtual size_t octomap::AbstractOcTree::memoryUsageNode () const pure virtual inherited
nodeChildExists()
bool octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::nodeChildExists (const CountingOcTreeNode * node, unsigned int childIdx) const inherited
Safe test if node has a child at index childIdx.
First tests if there are any children. Replaces node->childExists(...)
Returns
true if the child at childIdx exists
nodeHasChildren()
bool octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::nodeHasChildren (const CountingOcTreeNode * node) const inherited
Safe test if node has any children.
Replaces node->hasChildren(...)
Returns
true if node has at least one child
operator==()
bool octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::operator== (const OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree > & rhs) const inherited
Comparison between two octrees, all meta data, all nodes, and the structure must be identical.
prune()
void octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::prune virtual inherited
Lossless compression of the octree: A node will replace all of its eight children if they have identical values.
You usually don't have to call prune() after a regular occupancy update, updateNode() incrementally prunes all affected nodes.
Implements octomap::AbstractOcTree.
pruneNode()
bool octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::pruneNode (CountingOcTreeNode * node) virtual inherited
Prunes a node when it is collapsible.
Returns
true if pruning was successful
pruneRecurs()
void octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::pruneRecurs (CountingOcTreeNode * node, unsigned int depth, unsigned int max_depth, unsigned int & num_pruned) protected inherited
recursive call of prune()
read() [1/2]
AbstractOcTree * octomap::AbstractOcTree::read (const std::string & filename) static inherited
Read the file header, create the appropriate class and deserialize.
This creates a new octree which you need to delete yourself. If you expect or requre a specific kind of octree, use dynamic_cast afterwards:
AbstractOcTree* tree = AbstractOcTree::read("filename.ot");
OcTree* octree = dynamic_cast<OcTree*>(tree);
References OCTOMAP_ERROR_STR.
read() [2/2]
AbstractOcTree * octomap::AbstractOcTree::read (std::istream & s) static inherited
Read the file header, create the appropriate class and deserialize. This creates a new octree which you need to delete yourself.
References octomap::AbstractOcTree::createTree(), octomap::AbstractOcTree::fileHeader, OCTOMAP_DEBUG_STR, OCTOMAP_ERROR_STR, octomap::AbstractOcTree::readData(), octomap::AbstractOcTree::readHeader(), and octomap::AbstractOcTree::size().
readData()
std::istream & octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::readData (std::istream & s) virtual inherited
Read all nodes from the input stream (without file header), for this the tree needs to be already created.
For general file IO, you should probably use AbstractOcTree::read() instead.
Implements octomap::AbstractOcTree.
readHeader()
bool octomap::AbstractOcTree::readHeader (std::istream & s, std::string & id, unsigned & size, double & res) static protected inherited
References OCTOMAP_ERROR_STR, OCTOMAP_WARNING, OCTOMAP_WARNING_STR, and octomap::AbstractOcTree::size().
Referenced by octomap::AbstractOcTree::read(), and octomap::AbstractOccupancyOcTree::readBinary().
readNodesRecurs()
std::istream & octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::readNodesRecurs (CountingOcTreeNode * node, std::istream & s) protected inherited
recursive call of readData()
registerTreeType()
void octomap::AbstractOcTree::registerTreeType (AbstractOcTree * tree) static protected inherited
References octomap::AbstractOcTree::getTreeType().
Referenced by octomap::OcTree::StaticMemberInitializer::StaticMemberInitializer(), octomap::CountingOcTree::StaticMemberInitializer::StaticMemberInitializer(), octomap::OcTreeStamped::StaticMemberInitializer::StaticMemberInitializer(), and octomap::ColorOcTree::StaticMemberInitializer::StaticMemberInitializer().
search() [1/3]
CountingOcTreeNode * octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::search (const OcTreeKey & key, unsigned int depth = 0) const inherited
Search a node at specified depth given an addressing key (depth=0: search full tree depth) You need to check if the returned node is NULL, since it can be in unknown space.
Returns
pointer to node if found, NULL otherwise
search() [2/3]
CountingOcTreeNode * octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::search (const point3d & value, unsigned int depth = 0) const inherited
Search node at specified depth given a 3d point (depth=0: search full tree depth) You need to check if the returned node is NULL, since it can be in unknown space.
Returns
pointer to node if found, NULL otherwise
search() [3/3]
CountingOcTreeNode * octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::search (double x, double y, double z, unsigned int depth = 0) const inherited
Search node at specified depth given a 3d point (depth=0: search full tree depth).
You need to check if the returned node is NULL, since it can be in unknown space.
Returns
pointer to node if found, NULL otherwise
setResolution()
void octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::setResolution (double r) virtual inherited
Change the resolution of the octree, scaling all voxels. This will not preserve the (metric) scale!
Implements octomap::AbstractOcTree.
size() [1/2]
virtual size_t octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::size inline virtual inherited
Returns
The number of nodes in the tree
size() [2/2]
virtual size_t octomap::AbstractOcTree::size () const pure virtual inherited
Referenced by main(), octomap::AbstractOcTree::read(), octomap::AbstractOccupancyOcTree::readBinary(), octomap::AbstractOccupancyOcTree::readBinaryLegacyHeader(), octomap::AbstractOcTree::readHeader(), octomap::AbstractOcTree::write(), and octomap::AbstractOccupancyOcTree::writeBinaryConst().
swapContent()
void octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::swapContent (OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree > & rhs) inherited
Swap contents of two octrees, i.e., only the underlying pointer / tree structure.
You have to ensure yourself that the metadata (resolution etc) matches. No memory is cleared in this function
updateNode() [1/2]
CountingOcTreeNode * octomap::CountingOcTree::updateNode (const OcTreeKey & k)
References octomap::computeChildIdx(), octomap::OcTreeBaseImpl< CountingOcTreeNode, AbstractOcTree >::createNodeChild(), octomap::OcTreeBaseImpl< CountingOcTreeNode, AbstractOcTree >::getNodeChild(), octomap::CountingOcTreeNode::increaseCount(), octomap::OcTreeBaseImpl< CountingOcTreeNode, AbstractOcTree >::nodeChildExists(), octomap::OcTreeBaseImpl< CountingOcTreeNode, AbstractOcTree >::root, octomap::OcTreeBaseImpl< CountingOcTreeNode, AbstractOcTree >::tree_depth, and octomap::OcTreeBaseImpl< CountingOcTreeNode, AbstractOcTree >::tree_size.
updateNode() [2/2]
CountingOcTreeNode * octomap::CountingOcTree::updateNode (const point3d & value) virtual
References octomap::OcTreeBaseImpl< CountingOcTreeNode, AbstractOcTree >::coordToKeyChecked().
volume()
double octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::volume inherited
write() [1/2]
bool octomap::AbstractOcTree::write (const std::string & filename) const inherited
Write file header and complete tree to file (serialization)
References OCTOMAP_ERROR_STR.
Referenced by main().
write() [2/2]
bool octomap::AbstractOcTree::write (std::ostream & s) const inherited
Write file header and complete tree to stream (serialization)
References octomap::AbstractOcTree::fileHeader, octomap::AbstractOcTree::getResolution(), octomap::AbstractOcTree::getTreeType(), octomap::AbstractOcTree::size(), and octomap::AbstractOcTree::writeData().
writeData()
std::ostream & octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::writeData (std::ostream & s) const virtual inherited
Write complete state of tree to stream (without file header) unmodified. Pruning the tree first produces smaller files (lossless compression)
Implements octomap::AbstractOcTree.
writeNodesRecurs()
std::ostream & octomap::OcTreeBaseImpl< CountingOcTreeNode , I >::writeNodesRecurs (const CountingOcTreeNode * node, std::ostream & s) const protected inherited
recursive call of writeData()
Field Documentation
countingOcTreeMemberInit
CountingOcTree::StaticMemberInitializer octomap::CountingOcTree::countingOcTreeMemberInit static protected
static member to ensure static initialization (only once)
Referenced by CountingOcTree().
fileHeader
const std::string octomap::AbstractOcTree::fileHeader = "# Octomap OcTree file" static protected inherited
Referenced by octomap::AbstractOcTree::read(), and octomap::AbstractOcTree::write().
keyrays
std::vector<KeyRay> octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::keyrays protected inherited
data structure for ray casting, array for multithreading
leaf_iterator_bbx_end
const leaf_bbx_iterator octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::leaf_iterator_bbx_end protected inherited
leaf_iterator_end
const leaf_iterator octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::leaf_iterator_end protected inherited
max_value
double octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::max_value[3] protected inherited
max in x, y, z
min_value
double octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::min_value[3] protected inherited
min in x, y, z contains the size of a voxel at level i (0: root node). tree_depth+1 levels (incl. 0)
resolution
double octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::resolution protected inherited
in meters
resolution_factor
double octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::resolution_factor protected inherited
= 1. / resolution
root
CountingOcTreeNode * octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::root protected inherited
Pointer to the root NODE, NULL for empty tree.
size_changed
bool octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::size_changed protected inherited
sizeLookupTable
std::vector<double> octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::sizeLookupTable protected inherited
tree_center
point3d octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::tree_center protected inherited
tree_depth
const unsigned int octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::tree_depth protected inherited
Maximum tree depth is fixed to 16 currently.
tree_iterator_end
const tree_iterator octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::tree_iterator_end protected inherited
tree_max_val
const unsigned int octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::tree_max_val protected inherited
tree_size
size_t octomap::OcTreeBaseImpl< CountingOcTreeNode , AbstractOcTree >::tree_size protected inherited
number of nodes in tree flag to denote whether the octree extent changed (for lazy min/max eval)
The documentation for this class was generated from the following files:
include/octomap/CountingOcTree.h
src/CountingOcTree.cpp