octomap: octomap::KeyRay Class Reference
octomap::KeyRay Class Reference
Public Types
typedef std::vector< OcTreeKey >::const_iterator const_iterator
typedef std::vector< OcTreeKey >::iterator iterator
typedef std::vector< OcTreeKey >::reverse_iterator reverse_iterator
Public Member Functions
void addKey (const OcTreeKey &k)
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
KeyRay ()
KeyRay (const KeyRay &other)
reverse_iterator rbegin ()
reverse_iterator rend ()
void reset ()
size_t size () const
size_t sizeMax () const
Member Typedef Documentation
const_iterator
typedef std::vector<OcTreeKey>::const_iterator octomap::KeyRay::const_iterator
iterator
typedef std::vector<OcTreeKey>::iterator octomap::KeyRay::iterator
reverse_iterator
typedef std::vector<OcTreeKey>::reverse_iterator octomap::KeyRay::reverse_iterator
Constructor & Destructor Documentation
KeyRay() [1/2]
octomap::KeyRay::KeyRay () inline
References reset().
KeyRay() [2/2]
octomap::KeyRay::KeyRay (const KeyRay & other) inline
References begin(), and end().
Member Function Documentation
addKey()
void octomap::KeyRay::addKey (const OcTreeKey & k) inline
Referenced by octomap::OcTreeBaseImpl< ColorOcTreeNode, AbstractOccupancyOcTree >::computeRayKeys().
begin() [1/2]
iterator octomap::KeyRay::begin () inline
Referenced by octomap::OccupancyOcTreeBase< OcTreeNodeStamped >::computeUpdate(), octomap::OccupancyOcTreeBase< OcTreeNodeStamped >::insertPointCloudRays(), KeyRay(), and reset().
begin() [2/2]
const_iterator octomap::KeyRay::begin () const inline
end() [1/2]
iterator octomap::KeyRay::end () inline
Referenced by octomap::OccupancyOcTreeBase< OcTreeNodeStamped >::computeUpdate(), octomap::OccupancyOcTreeBase< OcTreeNodeStamped >::insertPointCloudRays(), and KeyRay().
end() [2/2]
const_iterator octomap::KeyRay::end () const inline
rbegin()
reverse_iterator octomap::KeyRay::rbegin () inline
Referenced by octomap::OccupancyOcTreeBase< OcTreeNodeStamped >::computeUpdate().
rend()
reverse_iterator octomap::KeyRay::rend () inline
Referenced by octomap::OccupancyOcTreeBase< OcTreeNodeStamped >::computeUpdate().
reset()
void octomap::KeyRay::reset () inline
References begin().
Referenced by octomap::OcTreeBaseImpl< ColorOcTreeNode, AbstractOccupancyOcTree >::computeRayKeys(), and KeyRay().
size()
size_t octomap::KeyRay::size () const inline
Referenced by octomap::OcTreeBaseImpl< ColorOcTreeNode, AbstractOccupancyOcTree >::computeRayKeys().
sizeMax()
size_t octomap::KeyRay::sizeMax () const inline
Referenced by octomap::OcTreeBaseImpl< ColorOcTreeNode, AbstractOccupancyOcTree >::computeRayKeys().
The documentation for this class was generated from the following file:
include/octomap/OcTreeKey.h