octomap: octomap::OcTreeStamped::StaticMemberInitializer Class Reference
octomap::OcTreeStamped::StaticMemberInitializer Class Reference
Static member object which ensures that this OcTree's prototype ends up in the classIDMapping only once.
Public Member Functions
void ensureLinking ()
Dummy function to ensure that MSVC does not drop the StaticMemberInitializer, causing this tree failing to register.
StaticMemberInitializer ()
Detailed Description
Static member object which ensures that this OcTree's prototype ends up in the classIDMapping only once.
You need this as a static member in any derived octree class in order to read .ot files through the AbstractOcTree factory. You should also call ensureLinking() once from the constructor.
Constructor & Destructor Documentation
octomap::OcTreeStamped::StaticMemberInitializer::StaticMemberInitializer () inline
References octomap::OcTreeBaseImpl< NODE, INTERFACE >::clearKeyRays(), octomap::OcTreeStamped::OcTreeStamped(), and octomap::AbstractOcTree::registerTreeType().
Member Function Documentation
void octomap::OcTreeStamped::StaticMemberInitializer::ensureLinking () inline
Dummy function to ensure that MSVC does not drop the StaticMemberInitializer, causing this tree failing to register.
Needs to be called from the constructor of this octree.
Referenced by octomap::OcTreeStamped::OcTreeStamped().
The documentation for this class was generated from the following file:
include/octomap/OcTreeStamped.h