octomap: src/compare_octrees.cpp File Reference
compare_octrees.cpp File Reference
Functions
int main (int argc, char **argv)
void printUsage (char *self)
Function Documentation
main()
int main (int argc, char ** argv)
References octomap::OcTreeBaseImpl< NODE, INTERFACE >::begin_leafs(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::end_leafs(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::expand(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::getMetricSize(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::getNumLeafNodes(), octomap::OcTreeNode::getOccupancy(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::getResolution(), OCTOMAP_ERROR, OCTOMAP_ERROR_STR, OCTOMAP_WARNING, printUsage(), and octomap::OcTreeBaseImpl< NODE, INTERFACE >::search().
printUsage()
void printUsage (char * self)
Referenced by main().