octomap: src/convert_octree.cpp File Reference
convert_octree.cpp File Reference
Functions
int main (int argc, char **argv)
void printUsage (char *self)
Function Documentation
main()
int main (int argc, char ** argv)
References octomap::AbstractOcTree::getTreeType(), OCTOMAP_ERROR_STR, OCTOMAP_WARNING_STR, printUsage(), octomap::AbstractOccupancyOcTree::readBinary(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::readData(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::size(), octomap::AbstractOcTree::write(), and octomap::AbstractOccupancyOcTree::writeBinary().
printUsage()
void printUsage (char * self)
Referenced by main().