octomap: src/edit_octree.cpp File Reference
edit_octree.cpp File Reference
Typedefs
typedef unsigned char byte
Functions
int main (int argc, char **argv)
Typedef Documentation
typedef unsigned char byte
Function Documentation
int main (int argc, char ** argv)
References octomap::OcTreeBaseImpl< NODE, INTERFACE >::getResolution(), OCTOMAP_ERROR, OCTOMAP_WARNING_STR, octomap::AbstractOccupancyOcTree::readBinary(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::setResolution(), and octomap::AbstractOccupancyOcTree::writeBinary().