octomap: src/eval_octree_accuracy.cpp File Reference
eval_octree_accuracy.cpp File Reference
Functions
int main (int argc, char **argv)
void printUsage (char *self)
Function Documentation
main()
int main (int argc, char ** argv)
References octomap::ScanGraph::begin(), octomap::OccupancyOcTreeBase< NODE >::computeUpdate(), octomap::ScanGraph::end(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::expand(), octomap::ScanGraph::getNumPoints(), octomap::OccupancyOcTreeBase< NODE >::insertPointCloud(), octomath::Pose6D::inv(), octomap::AbstractOccupancyOcTree::isNodeOccupied(), printUsage(), octomap::ScanGraph::readBinary(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::search(), octomap::Pointcloud::size(), octomap::ScanGraph::size(), octomap::Pointcloud::transform(), and octomath::Pose6D::transform().
printUsage()
void printUsage (char * self)
Referenced by main().