octomap: src/graph2tree.cpp File Reference
graph2tree.cpp File Reference
Functions
void calcThresholdedNodes (const OcTree *tree, unsigned int &num_thresholded, unsigned int &num_other)
int main (int argc, char **argv)
void outputStatistics (const OcTree *tree)
void printUsage (char *self)
Function Documentation
void calcThresholdedNodes (const OcTree * tree, unsigned int & num_thresholded, unsigned int & num_other)
References octomap::OcTreeBaseImpl< NODE, INTERFACE >::begin_tree(), and octomap::OcTreeBaseImpl< NODE, INTERFACE >::end_tree().
Referenced by outputStatistics().
int main (int argc, char ** argv)
References octomap::ScanGraph::begin(), octomap::ScanGraph::end(), octomap::ScanGraph::getNumPoints(), octomap::OccupancyOcTreeBase< NODE >::insertPointCloud(), octomap::OccupancyOcTreeBase< NODE >::insertPointCloudRays(), octomath::Pose6D::inv(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::memoryFullGrid(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::memoryUsage(), OCTOMAP_ERROR, OCTOMAP_WARNING, outputStatistics(), printUsage(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::prune(), octomap::ScanGraph::readBinary(), octomap::ScanGraph::size(), octomap::OccupancyOcTreeBase< NODE >::toMaxLikelihood(), and octomath::Pose6D::transform().
void outputStatistics (const OcTree * tree)
References calcThresholdedNodes(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::getMetricSize(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::getNumLeafNodes(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::memoryFullGrid(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::memoryUsage(), and octomap::OcTreeBaseImpl< NODE, INTERFACE >::size().
Referenced by main().
void printUsage (char * self)