octomap: src/intersection_example.cpp File Reference
intersection_example.cpp File Reference
Functions
int main (int, char **)
Function Documentation
main()
int main (int , char **)
References octomap::OccupancyOcTreeBase< NODE >::castRay(), octomap::OccupancyOcTreeBase< NODE >::getRayIntersection(), and octomap::OccupancyOcTreeBase< NODE >::updateNode().