octomap: src/log2graph.cpp File Reference
log2graph.cpp File Reference
Functions
int main (int argc, char **argv)
void printUsage (char *self)
Function Documentation
main()
int main (int argc, char ** argv)
References printUsage(), octomap::ScanGraph::readPlainASCII(), and octomap::ScanGraph::writeBinary().
printUsage()
void printUsage (char * self)
Referenced by main().