octomap: octomap Namespace Reference
octomap Namespace Reference
Namespace the OctoMap library and visualization tools.
Data Structures
class AbstractOccupancyOcTree
Interface class for all octree types that store occupancy.
class AbstractOcTree
This abstract class is an interface to all octrees and provides a factory design pattern for readin and writing all kinds of OcTrees to files (see read()).
class AbstractOcTreeNode
class ColorOcTree
class ColorOcTreeNode
class CountingOcTree
An AbstractOcTree which stores an internal counter per node / volume.
class CountingOcTreeNode
An Octree-node which stores an internal counter per node / volume.
struct equal_keys
comparator for keys
struct hash_key
class KeyRay
class MapCollection
class MapNode
class OccupancyOcTreeBase
Base implementation for Occupancy Octrees (e.g.
class OcTree
octomap main map data structure, stores 3D occupancy grid map in an OcTree.
class OcTreeBase
class OcTreeBaseImpl
OcTree base class, to be used with with any kind of OcTreeDataNode.
class OcTreeBaseSE
class OcTreeDataNode
Basic node in the OcTree that can hold arbitrary data of type T in value.
class OcTreeKey
OcTreeKey is a container class for internal key addressing.
class OcTreeLUT
Implements a lookup table that allows to computer keys of neighbor cells directly, see: Samet 1989, "Implementing ray tracing with octrees and neighbor finding".
class OcTreeNode
Nodes to be used in OcTree.
class OcTreeNodeStamped
class OcTreeStamped
class Pointcloud
A collection of 3D coordinates (point3d), which are regarded as endpoints of a 3D laser scan.
class ScanEdge
A connection between two ScanNodes.
class ScanGraph
A ScanGraph is a collection of ScanNodes, connected by ScanEdges.
class ScanNode
A 3D scan as Pointcloud, performed from a Pose6D.
Typedefs
typedef
std::tr1::unordered_map
< OcTreeKey, bool,
OcTreeKey::KeyHash > KeyBoolMap
Data structrure to efficiently track changed nodes as a combination of OcTreeKeys and a bool flag (to denote newly created nodes)
typedef
std::tr1::unordered_set
< OcTreeKey,
OcTreeKey::KeyHash > KeySet
Data structure to efficiently compute the nodes to update from a scan insertion using a hash set.
typedef std::pair< point3d,
double > OcTreeVolume
A voxel defined by its center point3d and its side length.
typedef octomath::Vector3 point3d
Use Vector3 (float precision) as a point3d in octomap.
typedef std::vector
< octomath::Vector3 > point3d_collection
typedef std::list
< octomath::Vector3 > point3d_list
typedef octomath::Pose6D pose6d
Use our Pose6D (float precision) as pose6d in octomap.
Functions
unsigned char computeChildIdx (const OcTreeKey &key, int depth)
generate child index (between 0 and 7) from key at given tree depth
void computeChildKey (const unsigned int &pos, const unsigned short int &center_offset_key, const OcTreeKey &parent_key, OcTreeKey &child_key)
Computes the key of a child node while traversing the octree, given child index and current key.
OcTreeKey computeIndexKey (unsigned short int level, const OcTreeKey &key)
Generates a unique key for all keys on a certain level of the tree.
float logodds (double probability)
compute log-odds from probability:
std::ostream & operator<< (std::ostream &out, ColorOcTreeNode::Color const &c)
user friendly output in format (r g b)
double probability (double logodds)
compute probability from logodds:
Detailed Description
Namespace the OctoMap library and visualization tools.
Typedef Documentation
typedef std::tr1::unordered_map<OcTreeKey, bool, OcTreeKey::KeyHash> octomap::KeyBoolMap
Data structrure to efficiently track changed nodes as a combination of OcTreeKeys and a bool flag (to denote newly created nodes)
typedef std::tr1::unordered_set<OcTreeKey, OcTreeKey::KeyHash> octomap::KeySet
Data structure to efficiently compute the nodes to update from a scan insertion using a hash set.
Note
you need to use boost::unordered_set instead if your compiler does not yet support tr1!
typedef std::pair<point3d, double> octomap::OcTreeVolume
A voxel defined by its center point3d and its side length.
typedef octomath::Vector3 octomap::point3d
Use Vector3 (float precision) as a point3d in octomap.
typedef std::vector<octomath::Vector3> octomap::point3d_collection
typedef std::list<octomath::Vector3> octomap::point3d_list
typedef octomath::Pose6D octomap::pose6d
Use our Pose6D (float precision) as pose6d in octomap.
Function Documentation
unsigned char octomap::computeChildIdx (const OcTreeKey & key, int depth) inline
generate child index (between 0 and 7) from key at given tree depth
References octomap::OcTreeKey::k.
Referenced by octomap::OcTreeBaseImpl< NODE, INTERFACE >::deleteNodeRecurs(), octomap::OcTreeBaseImpl< CountingOcTreeNode, AbstractOcTree >::DEPRECATED(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::search(), octomap::CountingOcTree::updateNode(), and octomap::OccupancyOcTreeBase< NODE >::updateNodeRecurs().
void octomap::computeChildKey (const unsigned int & pos, const unsigned short int & center_offset_key, const OcTreeKey & parent_key, OcTreeKey & child_key) inline
Computes the key of a child node while traversing the octree, given child index and current key.
Parameters
[in] pos index of child node (0..7)
[in] center_offset_key constant offset of octree keys
[in] parent_key current (parent) key
[out] child_key computed child key
Referenced by octomap::CountingOcTree::getCentersMinHitsRecurs(), octomap::OccupancyOcTreeBase< NODE >::getOccupiedLeafsBBXRecurs(), iterator_base::singleIncrement(), and leaf_bbx_iterator::singleIncrement().
OcTreeKey octomap::computeIndexKey (unsigned short int level, const OcTreeKey & key) inline
Generates a unique key for all keys on a certain level of the tree.
Parameters
level from the bottom (= tree_depth - depth of key)
key input indexing key (at lowest resolution / level)
Returns
key corresponding to the input key at the given level
Referenced by iterator_base::getIndexKey().
float octomap::logodds (double probability) inline
compute log-odds from probability:
Referenced by main(), octomap::AbstractOccupancyOcTree::setClampingThresMax(), octomap::AbstractOccupancyOcTree::setClampingThresMin(), octomap::AbstractOccupancyOcTree::setOccupancyThres(), octomap::AbstractOccupancyOcTree::setProbHit(), and octomap::AbstractOccupancyOcTree::setProbMiss().
std::ostream & octomap::operator<< (std::ostream & out, ColorOcTreeNode::Color const & c)
user friendly output in format (r g b)
References octomap::ColorOcTreeNode::Color::b, octomap::ColorOcTreeNode::Color::g, and octomap::ColorOcTreeNode::Color::r.
double octomap::probability (double logodds) inline
compute probability from logodds:
Referenced by octomap::AbstractOccupancyOcTree::getClampingThresMax(), octomap::AbstractOccupancyOcTree::getClampingThresMin(), octomap::OcTreeNode::getOccupancy(), octomap::AbstractOccupancyOcTree::getOccupancyThres(), octomap::AbstractOccupancyOcTree::getProbHit(), octomap::AbstractOccupancyOcTree::getProbMiss(), and main().