octomap: octomath Namespace Reference
octomath Namespace Reference
Namespace of the math library in OctoMap.
Data Structures
class Pose6D
This class represents a tree-dimensional pose of an object.
class Quaternion
This class represents a Quaternion.
class Vector3
This class represents a three-dimensional vector.
Functions
Quaternion operator* (const Vector3 &v, const Quaternion &q)
std::ostream & operator<< (std::ostream &s, const Quaternion &q)
user friendly output in format (u x y z)
std::ostream & operator<< (std::ostream &s, const Pose6D &p)
user friendly output in format (x y z, u x y z) which is (translation, rotation)
std::ostream & operator<< (std::ostream &out, octomath::Vector3 const &v)
user friendly output in format (x y z)
Detailed Description
Namespace of the math library in OctoMap.
Function Documentation
Quaternion octomath::operator* (const Vector3 & v, const Quaternion & q)
Returns
(0, v) * q
std::ostream & octomath::operator<< (std::ostream & s, const Quaternion & q)
user friendly output in format (u x y z)
References octomath::Quaternion::u(), octomath::Quaternion::x(), octomath::Quaternion::y(), and octomath::Quaternion::z().
std::ostream & octomath::operator<< (std::ostream & s, const Pose6D & p)
user friendly output in format (x y z, u x y z) which is (translation, rotation)
References octomath::Pose6D::rot(), octomath::Quaternion::u(), octomath::Pose6D::x(), octomath::Quaternion::x(), octomath::Pose6D::y(), octomath::Quaternion::y(), octomath::Pose6D::z(), and octomath::Quaternion::z().
std::ostream & octomath::operator<< (std::ostream & out, octomath::Vector3 const & v)
user friendly output in format (x y z)
References octomath::Vector3::x(), octomath::Vector3::y(), and octomath::Vector3::z().