octomap: src/normals_example.cpp File Reference
normals_example.cpp File Reference
Functions
int main (int argc, char **argv)
void print_query_info (point3d query, OcTreeNode *node)
Function Documentation
int main (int argc, char ** argv)
References octomap::OccupancyOcTreeBase< NODE >::getNormals(), print_query_info(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::search(), and octomap::OccupancyOcTreeBase< NODE >::updateNode().
void print_query_info (point3d query, OcTreeNode * node)
References octomap::OcTreeNode::getOccupancy().
Referenced by main().