octomap: src/octree2pointcloud.cpp File Reference
octree2pointcloud.cpp File Reference
Functions
int main (int argc, char **argv)
void printUsage (char *self)
Function Documentation
main()
int main (int argc, char ** argv)
References octomap::OcTreeBaseImpl< NODE, INTERFACE >::begin(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::end(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::expandNode(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::getTreeDepth(), octomap::AbstractOccupancyOcTree::isNodeOccupied(), OCTOMAP_ERROR, printUsage(), and octomap::AbstractOccupancyOcTree::readBinary().
printUsage()
void printUsage (char * self)
Referenced by main().