octomap: src/offset_graph.cpp File Reference
offset_graph.cpp File Reference
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References octomap::ScanGraph::begin(), octomap::ScanGraph::end(), octomath::Pose6D::inv(), octomap::ScanGraph::readBinary(), and octomap::ScanGraph::writeBinary().