octomap: src/simple_example.cpp File Reference
simple_example.cpp File Reference
Functions
int main (int, char **)
void print_query_info (point3d query, OcTreeNode *node)
Function Documentation
main()
int main (int , char **)
References print_query_info(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::search(), octomap::OccupancyOcTreeBase< NODE >::updateNode(), and octomap::AbstractOccupancyOcTree::writeBinary().
print_query_info()
void print_query_info (point3d query, OcTreeNode * node)
References octomap::OcTreeNode::getOccupancy().
Referenced by main().