octomap: src/testing/test_scans.cpp File Reference
test_scans.cpp File Reference
Functions
int main (int argc, char **argv)
void printUsage (char *self)
Function Documentation
main()
int main (int argc, char ** argv)
References octomap::ScanGraph::addNode(), octomap::ScanGraph::begin(), DEG2RAD, EXPECT_EQ, EXPECT_TRUE, octomap::ScanNode::id, octomap::OccupancyOcTreeBase< NODE >::insertPointCloud(), octomap::ScanNode::pose, printUsage(), octomap::Pointcloud::push_back(), octomap::ScanGraph::readBinary(), octomath::Vector3::rotate_IP(), octomap::ScanNode::scan, octomap::Pointcloud::size(), octomap::ScanGraph::size(), octomath::Pose6D::trans(), octomap::AbstractOccupancyOcTree::writeBinary(), and octomap::ScanGraph::writeBinary().
printUsage()
void printUsage (char * self)
Referenced by main().