octomap: src/testing/test_mapcollection.cpp File Reference
test_mapcollection.cpp File Reference
Functions
OcTree * generateSphereTree (point3d origin, float radius)
int main (int, char **argv)
Function Documentation
generateSphereTree()
OcTree* generateSphereTree (point3d origin, float radius)
References DEG2RAD, octomap::OccupancyOcTreeBase< NODE >::insertRay(), octomath::Vector3::rotate_IP(), and octomath::Vector3::x().
main()
int main (int , char ** argv)
References octomap::MapCollection< MAPNODE >::castRay(), EXPECT_TRUE, octomap::MapCollection< MAPNODE >::getOccupancy(), octomap::MapCollection< MAPNODE >::isOccupied(), octomap::MapCollection< MAPNODE >::size(), octomap::MapCollection< MAPNODE >::write(), octomath::Vector3::x(), octomath::Vector3::y(), and octomath::Vector3::z().