octomap: src/testing/test_io.cpp File Reference
test_io.cpp File Reference
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, octomap::ColorOcTreeNode::getColor(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::getResolution(), octomap::AbstractOcTree::getTreeType(), octomap::OcTreeStamped::getTreeType(), octomap::ColorOcTree::getTreeType(), octomap::AbstractOccupancyOcTree::isNodeOccupied(), octomap::AbstractOccupancyOcTree::readBinary(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::search(), octomap::ColorOcTreeNode::setColor(), octomap::ColorOcTree::setNodeColor(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::setResolution(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::size(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::swapContent(), octomap::OccupancyOcTreeBase< NODE >::updateNode(), octomap::AbstractOcTree::write(), and octomap::AbstractOccupancyOcTree::writeBinary().