octomap: src/testing/test_raycasting.cpp File Reference
test_raycasting.cpp File Reference
Functions
int main (int argc, char **argv)
Function Documentation
int main (int argc, char ** argv)
References octomap::OccupancyOcTreeBase< NODE >::castRay(), DEG2RAD, EXPECT_EQ, EXPECT_FALSE, EXPECT_FLOAT_EQ, EXPECT_NEAR, EXPECT_TRUE, octomap::OccupancyOcTreeBase< NODE >::insertPointCloud(), octomap::OccupancyOcTreeBase< NODE >::insertRay(), octomap::AbstractOccupancyOcTree::isNodeOccupied(), M_PI, octomap::Pointcloud::push_back(), octomath::Vector3::rotate_IP(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::search(), octomap::OccupancyOcTreeBase< NODE >::updateNode(), octomap::AbstractOccupancyOcTree::writeBinary(), octomath::Vector3::x(), octomath::Vector3::y(), and octomath::Vector3::z().