octomap: src/testing/test_color_tree.cpp File Reference
test_color_tree.cpp File Reference
Functions
int main (int, char **)
void print_query_info (point3d query, ColorOcTreeNode *node)
Function Documentation
main()
int main (int , char **)
References octomap::OcTreeBaseImpl< NODE, INTERFACE >::calcNumNodes(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::deleteNodeChild(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::expand(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::expandNode(), EXPECT_EQ, EXPECT_FALSE, EXPECT_FLOAT_EQ, EXPECT_TRUE, octomap::ColorOcTreeNode::getColor(), octomap::OcTreeNode::getLogOdds(), octomap::AbstractOcTree::getResolution(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::getResolution(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::getTreeDepth(), octomap::AbstractOcTree::getTreeType(), octomap::ColorOcTree::getTreeType(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::nodeChildExists(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::nodeHasChildren(), print_query_info(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::prune(), octomap::ColorOcTree::pruneNode(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::search(), octomap::ColorOcTreeNode::setColor(), octomap::AbstractOcTree::size(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::size(), octomap::ColorOcTree::updateInnerOccupancy(), octomap::OccupancyOcTreeBase< NODE >::updateNode(), and octomap::AbstractOcTree::write().
print_query_info()
void print_query_info (point3d query, ColorOcTreeNode * node)
References octomap::ColorOcTreeNode::getColor(), and octomap::OcTreeNode::getOccupancy().
Referenced by main().