octomap: src/testing/test_pruning.cpp File Reference
test_pruning.cpp File Reference
Functions
int main (int, char **)
Function Documentation
main()
int main (int , char **)
References octomap::OcTreeBaseImpl< NODE, INTERFACE >::calcNumNodes(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::clear(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::coordToKeyChecked(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::createNodeChild(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::deleteNodeChild(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::expand(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::expandNode(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, octomap::OcTreeBaseImpl< NODE, INTERFACE >::getTreeDepth(), octomap::AbstractOccupancyOcTree::isNodeOccupied(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::nodeChildExists(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::nodeHasChildren(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::prune(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::pruneNode(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::search(), octomap::OcTreeDataNode< T >::setValue(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::size(), octomap::OccupancyOcTreeBase< NODE >::updateNode(), and octomap::AbstractOcTree::write().