octomap: src/testing/test_changedkeys.cpp File Reference
test_changedkeys.cpp File Reference
Functions
int main (int, char **)
void printChanges (OcTree &tree)
Function Documentation
main()
int main (int , char **)
References DEG2RAD, octomap::OccupancyOcTreeBase< NODE >::enableChangeDetection(), octomap::OccupancyOcTreeBase< NODE >::insertPointCloud(), octomap::OccupancyOcTreeBase< NODE >::insertRay(), printChanges(), octomap::Pointcloud::push_back(), octomath::Vector3::rotate_IP(), and octomap::OccupancyOcTreeBase< NODE >::updateNode().
printChanges()
void printChanges (OcTree & tree)
References octomap::OcTreeBaseImpl< NODE, INTERFACE >::begin_tree(), octomap::OccupancyOcTreeBase< NODE >::changedKeysBegin(), octomap::OccupancyOcTreeBase< NODE >::changedKeysEnd(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::end_tree(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::expand(), octomap::AbstractOccupancyOcTree::isNodeOccupied(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::prune(), and octomap::OcTreeBaseImpl< NODE, INTERFACE >::search().
Referenced by main().