octomap: src/testing/test_iterators.cpp File Reference
test_iterators.cpp File Reference
Functions
void boundingBoxTest (OcTree *tree)
void compareResults (const std::list< OcTreeVolume > &list_iterator, const std::list< OcTreeVolume > &list_depr)
compare two lists of octree nodes on equality
void computeChildCenter (const unsigned int &pos, const float &center_offset, const point3d &parent_center, point3d &child_center)
void getLeafNodesRecurs (std::list< OcTreeVolume > &voxels, unsigned int max_depth, OcTreeNode *node, unsigned int depth, const point3d &parent_center, const point3d &tree_center, OcTree *tree, bool occupied)
mimics old deprecated behavior to compare against
void getVoxelsRecurs (std::list< OcTreeVolume > &voxels, unsigned int max_depth, OcTreeNode *node, unsigned int depth, const point3d &parent_center, const point3d &tree_center, OcTree *tree)
mimics old deprecated behavior to compare against
int main (int argc, char **argv)
bool OcTreeVolumeSortPredicate (const OcTreeVolume &lhs, const OcTreeVolume &rhs)
void printUsage (char *self)
double timediff (const timeval &start, const timeval &stop)
Function Documentation
boundingBoxTest()
void boundingBoxTest (OcTree * tree)
References octomap::OcTreeBaseImpl< NODE, INTERFACE >::begin(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::begin_leafs(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::begin_leafs_bbx(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::coordToKeyChecked(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::end(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::end_leafs(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::end_leafs_bbx(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::expand(), EXPECT_EQ, EXPECT_FALSE, EXPECT_TRUE, octomap::OcTreeBaseImpl< NODE, INTERFACE >::getMetricMax(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::getMetricMin(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::nodeHasChildren(), and octomap::OcTreeBaseImpl< NODE, INTERFACE >::search().
Referenced by main().
compareResults()
void compareResults (const std::list< OcTreeVolume > & list_iterator, const std::list< OcTreeVolume > & list_depr)
compare two lists of octree nodes on equality
References EXPECT_EQ, and EXPECT_NEAR.
Referenced by main().
computeChildCenter()
void computeChildCenter (const unsigned int & pos, const float & center_offset, const point3d & parent_center, point3d & child_center)
Referenced by getLeafNodesRecurs(), and getVoxelsRecurs().
getLeafNodesRecurs()
void getLeafNodesRecurs (std::list< OcTreeVolume > & voxels, unsigned int max_depth, OcTreeNode * node, unsigned int depth, const point3d & parent_center, const point3d & tree_center, OcTree * tree, bool occupied)
mimics old deprecated behavior to compare against
References computeChildCenter(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::getNodeChild(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::getResolution(), octomap::AbstractOccupancyOcTree::isNodeOccupied(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::nodeChildExists(), and octomap::OcTreeBaseImpl< NODE, INTERFACE >::nodeHasChildren().
Referenced by main().
getVoxelsRecurs()
void getVoxelsRecurs (std::list< OcTreeVolume > & voxels, unsigned int max_depth, OcTreeNode * node, unsigned int depth, const point3d & parent_center, const point3d & tree_center, OcTree * tree)
mimics old deprecated behavior to compare against
References computeChildCenter(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::getNodeChild(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::getResolution(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::nodeChildExists(), and octomap::OcTreeBaseImpl< NODE, INTERFACE >::nodeHasChildren().
Referenced by main().
main()
int main (int argc, char ** argv)
get number of nodes:
get all occupied leafs
get all free leafs
get all volumes
bounding box tests
References octomap::OcTreeBaseImpl< NODE, INTERFACE >::begin(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::begin_leafs(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::begin_leafs_bbx(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::begin_tree(), boundingBoxTest(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::calcNumNodes(), compareResults(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::end(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::end_leafs(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::end_leafs_bbx(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::end_tree(), EXPECT_EQ, EXPECT_TRUE, getLeafNodesRecurs(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::getNumLeafNodes(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::getResolution(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::getRoot(), getVoxelsRecurs(), octomap::AbstractOccupancyOcTree::isNodeOccupied(), OcTreeVolumeSortPredicate(), printUsage(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::size(), timediff(), and octomap::OccupancyOcTreeBase< NODE >::updateNode().
OcTreeVolumeSortPredicate()
bool OcTreeVolumeSortPredicate (const OcTreeVolume & lhs, const OcTreeVolume & rhs)
Referenced by main().
printUsage()
void printUsage (char * self)
Referenced by main().
timediff()
double timediff (const timeval & start, const timeval & stop)
Referenced by main().