octomap: src/testing/unit_tests.cpp File Reference
unit_tests.cpp File Reference
Functions
int main (int argc, char **argv)
Function Documentation
main()
int main (int argc, char ** argv)
References octomap::ScanGraph::addNode(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::coordToKeyChecked(), DEG2RAD, EXPECT_EQ, EXPECT_FLOAT_EQ, EXPECT_TRUE, octomap::OcTreeStamped::getLastUpdateTime(), octomap::OcTreeNodeStamped::getTimestamp(), octomap::OccupancyOcTreeBase< NODE >::insertPointCloud(), octomap::OccupancyOcTreeBase< NODE >::insertRay(), octomap::OcTreeStamped::integrateMissNoTime(), octomath::Pose6D::inv(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::keyToCoord(), octomap::logodds(), M_PI, octomap::probability(), octomap::Pointcloud::push_back(), octomap::ScanGraph::readBinary(), octomath::Vector3::rotate_IP(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::search(), octomap::AbstractOccupancyOcTree::setProbHit(), octomap::AbstractOccupancyOcTree::setProbMiss(), octomap::OcTreeBaseImpl< NODE, INTERFACE >::size(), octomath::Pose6D::transform(), octomap::OccupancyOcTreeBase< NODE >::updateNode(), octomap::AbstractOccupancyOcTree::writeBinary(), octomap::ScanGraph::writeBinary(), octomath::Vector3::x(), octomath::Vector3::y(), octomath::Pose6D::yaw(), and octomath::Vector3::z().